; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_File_CompareSize
	.import		_File_CompareName
	.import		_File_CompareFileTypeID
	.export		_App_ShowProgressBar
	.export		_App_HideProgressBar
	.export		_App_UpdateProgressBar
	.export		_App_EMDataCopy
	.export		_App_DisplayTime
	.export		_App_Exit
	.export		_App_LoadOverlay

	.import		_Buffer_Initialize
	.import		_Buffer_Clear
	.import		_Buffer_NewMessage
	.import		_General_GetString
	.import		_General_Strlcpy
	.import		_snprintf
	.import		_sprintf
	.import		_Folder_NewOrReset
	.import		_Folder_GetCurrentFileType
	.import		_MemSys_NewOrReset
	.import		_MemSys_GetCurrentRowKUPState
	.import		_Panel_Initialize
	.import		_Panel_SwitchDevice
	.import		_Panel_SetCurrentDevice
	.import		_Panel_ToggleActiveState
	.import		_Panel_MakeDir
	.import		_Panel_FormatDrive
	.import		_Panel_Refresh
	.import		_Panel_RenameCurrentFile
	.import		_Panel_DeleteCurrentFile
	.import		_Panel_OpenCurrentFileOrFolder
	.import		_Panel_CopyCurrentFile
	.import		_Panel_ViewCurrentFile
	.import		_Panel_SelectPrevFile
	.import		_Panel_SelectNextFile
	.import		_Panel_RenderContents
	.import		_Panel_SortAndDisplay
	.import		_Panel_FillCurrentBank
	.import		_Panel_ClearCurrentBank
	.import		_Panel_SearchCurrentBank
	.import		_Panel_OpenMeatloafURL
	.import		_Keyboard_InitiateMinuteHand
	.import		_Memory_SwapInNewBank
	.import		_Text_FillBox
	.import		_Text_SetCharAndColorAtXY
	.import		_Text_DrawHLine
	.import		_Text_DrawStringAtXY
	.import		_EM_SearchMemory
	.import		_Startup_LoadString
	.import		_Startup_ShowLogo
	.import		_Startup_InitializeRandomNumGen
	.import		_App_InitializeDialogBox
	.import		_Screen_SwapCopyDirectionIndicator
	.import		_Screen_Render
	.import		_Screen_SetInitialMenuStates
	.import		_Screen_GetValidUserInput
	.import		_Screen_UpdateMenuStates
	.import		_Screen_RenderMenu
	.import		_Screen_ShowAppAboutInfo
	.import		_Screen_GetStringFromUser
	.import		_Screen_ShowUserTwoButtonDialog
	.import		_Sys_InitSystem
	.import		_Sys_EnableTextModeCursor
	.import		_Sys_SetBorderSize
	.import		_Sys_SwapIOPage
	.import		_Sys_RestoreIOPage
	.import		_Sys_UpdateRTC
	.import		_memcpy
	.import		_Kernel_OpenDir
	.import		_Kernel_CloseDir
	.import		_kernel_init
	.import		_Kernal_RunNamed
	.export		_app_search_phrase_human_readable_storage
	.export		_app_search_phrase_storage
	.export		_global_search_phrase_human_readable
	.export		_global_search_phrase
	.export		_global_search_phrase_len
	.export		_global_named_app_dos
	.export		_global_named_app_basic
	.export		_global_connected_device
	.export		_global_started_from_flash
	.export		_global_clock_is_visible
	.export		_global_find_next_enabled
	.export		_app_file_panel
	.export		_global_dlg
	.export		_global_dlg_title
	.export		_global_dlg_body_msg
	.export		_global_dlg_button
	.export		_global_string_buff1
	.export		_global_string_buff2
	.export		_global_temp_path_1_buffer
	.export		_global_temp_path_2_buffer
	.export		_global_temp_path_1
	.export		_global_temp_path_2
	.export		_global_retrieved_em_filename_buffer
	.export		_global_retrieved_em_filename
	.export		_temp_screen_buffer_char
	.export		_temp_screen_buffer_attr
	.importzp	_zp_bank_num
	.export		_App_SwapActivePanel
	.export		_App_ScanDevices
	.export		_App_Initialize
	.export		_App_InitializePanelForDisk
	.export		_App_InitializePanelForMemory
	.export		_App_MainLoop
	.export		_main

.segment	"DATA"

_app_progress_bar_char:
	.byte	$20
	.byte	$CF
	.byte	$D0
	.byte	$D1
	.byte	$D2
	.byte	$D3
	.byte	$D4
	.byte	$D5
_global_search_phrase_human_readable:
	.addr	_app_search_phrase_human_readable_storage
_global_search_phrase:
	.addr	_app_search_phrase_storage
_global_named_app_dos:
	.addr	L0029
_global_named_app_basic:
	.addr	L002B
_global_find_next_enabled:
	.byte	$00
_global_string_buff1:
	.word	$0600
_global_string_buff2:
	.word	$06CC
_global_temp_path_2_buffer:
	.byte	$00
	.res	254,$00
_global_temp_path_1:
	.addr	_global_temp_path_1_buffer
_global_temp_path_2:
	.addr	_global_temp_path_2_buffer
_global_retrieved_em_filename:
	.addr	_global_retrieved_em_filename_buffer

.segment	"RODATA"

L02D3:
	.byte	$32,$30,$25,$30,$32,$58,$2D,$25,$30,$32,$58,$2D,$25,$30,$32,$58
	.byte	$20,$25,$30,$32,$58,$3A,$25,$30,$32,$58,$00
L002B:
	.byte	$62,$61,$73,$69,$63,$00
L00B5:
	.byte	$25,$75,$3A,$00
L0067	:=	L00B5+0
L0029:
	.byte	$64,$6F,$73,$00

.segment	"BSS"

_app_menu_enabler:
	.res	8,$00
_app_active_panel_id:
	.res	1,$00
_app_connected_drive_count:
	.res	1,$00
_app_search_phrase_human_readable_storage:
	.res	33,$00
_app_search_phrase_storage:
	.res	33,$00
_global_search_phrase_len:
	.res	1,$00
_global_connected_device:
	.res	4,$00
_global_started_from_flash:
	.res	1,$00
_global_clock_is_visible:
	.res	1,$00
_app_file_panel:
	.res	34,$00
_global_dlg:
	.res	27,$00
_global_dlg_title:
	.res	36,$00
_global_dlg_body_msg:
	.res	70,$00
_global_dlg_button:
	.res	30,$00
_global_temp_path_1_buffer:
	.res	255,$00
_global_retrieved_em_filename_buffer:
	.res	32,$00
_temp_screen_buffer_char:
	.res	396,$00
_temp_screen_buffer_attr:
	.res	396,$00

; ---------------------------------------------------------------
; void __near__ App_ShowProgressBar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_ShowProgressBar: near

.segment	"CODE"

;
; Text_DrawHLine(UI_MIDDLE_AREA_START_X, PROGRESS_BAR_Y - 1, UI_MIDDLE_AREA_WIDTH, CH_UNDERSCORE, MENU_ACCENT_COLOR, APP_BACKGROUND_COLOR, CHAR_AND_ATTR);
;
	lda     #$23
	jsr     pusha
	lda     #$2F
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$94
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawHLine
;
; Text_DrawHLine(UI_MIDDLE_AREA_START_X, PROGRESS_BAR_Y,     UI_MIDDLE_AREA_WIDTH, CH_SPACE,      MENU_ACCENT_COLOR, APP_BACKGROUND_COLOR, CHAR_AND_ATTR);
;
	lda     #$23
	jsr     pusha
	lda     #$30
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawHLine
;
; Text_DrawHLine(UI_MIDDLE_AREA_START_X, PROGRESS_BAR_Y + 1, UI_MIDDLE_AREA_WIDTH, CH_OVERSCORE,  MENU_ACCENT_COLOR, APP_BACKGROUND_COLOR, CHAR_AND_ATTR);
;
	lda     #$23
	jsr     pusha
	lda     #$31
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$02
	jmp     _Text_DrawHLine

.endproc

; ---------------------------------------------------------------
; void __near__ App_HideProgressBar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_HideProgressBar: near

.segment	"CODE"

;
; Text_FillBox(UI_MIDDLE_AREA_START_X, PROGRESS_BAR_Y - 1, (UI_MIDDLE_AREA_START_X + UI_MIDDLE_AREA_WIDTH - 1), PROGRESS_BAR_Y + 1, CH_SPACE, MENU_ACCENT_COLOR, APP_BACKGROUND_COLOR);
;
	lda     #$23
	jsr     pusha
	lda     #$2F
	jsr     pusha
	lda     #$2C
	jsr     pusha
	lda     #$31
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jmp     _Text_FillBox

.endproc

; ---------------------------------------------------------------
; void __near__ App_UpdateProgressBar (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_UpdateProgressBar: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; progress_bar_total = (progress_bar_total > 100) ? 100 : progress_bar_total;
;
	jsr     decsp4
	ldy     #$04
	lda     (sp),y
	cmp     #$65
	bcc     L038C
	lda     #$64
	bra     L038E
L038C:	lda     (sp),y
L038E:	sta     (sp),y
;
; progress_bar_total = (uint16_t)progress_bar_total * (PROGRESS_BAR_WIDTH * PROGRESS_BAR_DIVISOR) / 100;
;
	jsr     pusha0
	lda     #$50
	jsr     tosumula0
	jsr     pushax
	lda     #$64
	jsr     tosudiva0
	ldy     #$04
	sta     (sp),y
;
; full_blocks = progress_bar_total / PROGRESS_BAR_DIVISOR;
;
	lsr     a
	lsr     a
	lsr     a
	ldy     #$02
	sta     (sp),y
;
; progress_bar_char_index = progress_bar_total % PROGRESS_BAR_DIVISOR; // remainders will be 0-7: index to app_progress_bar_char[]
;
	ldy     #$04
	lda     (sp),y
	and     #$07
	sta     (sp)
;
; for (i = 0; i < PROGRESS_BAR_WIDTH; i++)
;
	lda     #$00
	dey
L0395:	sta     (sp),y
	cmp     #$0A
	bcs     L0287
;
; if (i < full_blocks)
;
	ldx     #$00
	lda     (sp),y
	dey
	cmp     (sp),y
	bcs     L028E
;
; the_char_code = CH_PROGRESS_BAR_FULL;
;
	lda     #$C7
;
; else if (i == full_blocks && progress_bar_char_index > 0)
;
	bra     L0394
L028E:	iny
	lda     (sp),y
	dey
	cmp     (sp),y
	bne     L0393
	lda     (sp)
	beq     L0393
;
; the_char_code = app_progress_bar_char[progress_bar_char_index];
;
	tay
	lda     _app_progress_bar_char,y
;
; else
;
	bra     L0394
;
; the_char_code = CH_SPACE;
;
L0393:	lda     #$20
L0394:	ldy     #$01
	sta     (sp),y
;
; Text_SetCharAndColorAtXY(PROGRESS_BAR_START_X + i, PROGRESS_BAR_Y, the_char_code, COLOR_PROGRESS_BAR, COLOR_BLACK);
;
	ldy     #$03
	lda     (sp),y
	ldy     #$23
	jsr     incaxy
	jsr     pusha
	lda     #$30
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #$00
	jsr     _Text_SetCharAndColorAtXY
;
; for (i = 0; i < PROGRESS_BAR_WIDTH; i++)
;
	ldy     #$03
	lda     (sp),y
	ina
	bra     L0395
;
; }
;
L0287:	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ App_EMDataCopy (__near__ unsigned char *, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_EMDataCopy: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; em_slot = em_bank_num + (page_num / 32);
;
	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	iny
	adc     (sp),y
	ldy     #$03
	sta     (sp),y
;
; em_cpu_addr = (uint8_t*)((uint16_t)EM_STORAGE_START_CPU_ADDR + ((page_num % 32) * 256));
;
	ldy     #$05
	lda     (sp),y
	and     #$1F
	sta     ptr1+1
	lda     #$00
	clc
	pha
	lda     #$A0
	adc     ptr1+1
	tax
	pla
	ldy     #$01
	jsr     staxysp
;
; zp_bank_num = em_slot;
;
	ldy     #$03
	lda     (sp),y
	sta     _zp_bank_num
;
; previous_overlay_bank_num = Memory_SwapInNewBank(EM_STORAGE_START_SLOT);
;
	lda     #$05
	jsr     _Memory_SwapInNewBank
	sta     (sp)
;
; if (to_em == true)
;
	ldy     #$04
	lda     (sp),y
	cmp     #$01
	bne     L02B3
;
; memcpy(em_cpu_addr, cpu_addr, 256);
;
	jsr     pushwysp
	ldy     #$0A
;
; else
;
	bra     L039B
;
; memcpy(cpu_addr, em_cpu_addr, 256);
;
L02B3:	ldy     #$0A
	jsr     pushwysp
	ldy     #$04
L039B:	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$00
	jsr     _memcpy
;
; zp_bank_num = previous_overlay_bank_num;
;
	lda     (sp)
	sta     _zp_bank_num
;
; previous_overlay_bank_num = Memory_SwapInNewBank(EM_STORAGE_START_SLOT);
;
	lda     #$05
	jsr     _Memory_SwapInNewBank
	sta     (sp)
;
; }
;
	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ App_DisplayTime (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_DisplayTime: near

.segment	"CODE"

;
; if (global_clock_is_visible != true)
;
	jsr     decsp1
	lda     _global_clock_is_visible
	cmp     #$01
;
; return;
;
	bne     L02C3
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	dea
	jsr     _Sys_SwapIOPage
;
; old_rtc_control = R8(RTC_CONTROL);
;
	lda     $D69E
	sta     (sp)
;
; R8(RTC_CONTROL) = old_rtc_control | 0x08; // stop it from updating external registers
;
	ora     #$08
	sta     $D69E
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "20%02X-%02X-%02X %02X:%02X", R8(RTC_YEAR), R8(RTC_MONTH), R8(RTC_DAY), R8(RTC_HOURS), R8(RTC_MINUTES));
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L02D3)
	ldx     #>(L02D3)
	jsr     pushax
	lda     $D69A
	jsr     pusha0
	lda     $D699
	jsr     pusha0
	lda     $D696
	jsr     pusha0
	lda     $D694
	jsr     pusha0
	lda     $D692
	jsr     pusha0
	ldy     #$10
	jsr     _snprintf
;
; R8(RTC_CONTROL) = old_rtc_control;
;
	lda     (sp)
	sta     $D69E
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; Text_DrawStringAtXY(64, 3, global_string_buff1, COLOR_BRIGHT_YELLOW, COLOR_BLACK);
;
	lda     #$40
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$0E
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; }
;
L02C3:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ App_Exit (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_Exit: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (the_error_number != ERROR_NO_ERROR)
;
	lda     (sp)
	beq     L0342
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_FATAL_ERROR), the_error_number);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$6D
	jsr     _General_GetString
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	jsr     _snprintf
;
; global_string_buff1,
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
;
; ID_STR_MSG_FATAL_ERROR_BODY,
;
	lda     #$70
	jsr     pusha
;
; ID_STR_DLG_OK,
;
	lda     #$09
	jsr     pusha
;
; );
;
	jsr     _Screen_ShowUserTwoButtonDialog
;
; Sys_EnableTextModeCursor(true);
;
L0342:	lda     #$01
	jsr     _Sys_EnableTextModeCursor
;
; R8(MMU_IO_CTRL) = 0;
;
	stz     $0001
;
; R8(0xD6A2) = 0xDE;
;
	lda     #$DE
	sta     $D6A2
;
; R8(0xD6A3) = 0xAD;
;
	lda     #$AD
	sta     $D6A3
;
; R8(0xD6A0) = 0xF0;
;
	lda     #$F0
	sta     $D6A0
;
; R8(0xD6A0) = 0x00;
;
	ldx     #$00
	txa
	stz     $D6A0
;
; asm("JMP ($FFFC)");
;
	jmp     ($FFFC)

.endproc

; ---------------------------------------------------------------
; void __near__ App_LoadOverlay (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_LoadOverlay: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; zp_bank_num = the_overlay_em_bank_number;
;
	lda     (sp)
	sta     _zp_bank_num
;
; Memory_SwapInNewBank(OVERLAY_CPU_BANK);
;
	lda     #$05
	jsr     _Memory_SwapInNewBank
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ App_GetFilenameFromEM (__near__ struct WB2KFileObject *)
; ---------------------------------------------------------------

.segment	"CODE"



; ---------------------------------------------------------------
; void __near__ App_SetFilenameInEM (__near__ struct WB2KFileObject *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"



; ---------------------------------------------------------------
; void __near__ App_SwapActivePanel (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_SwapActivePanel: near

.segment	"CODE"

;
; Panel_ToggleActiveState(&app_file_panel[PANEL_ID_LEFT]);
;
	lda     #<(_app_file_panel)
	ldx     #>(_app_file_panel)
	jsr     _Panel_ToggleActiveState
;
; Panel_ToggleActiveState(&app_file_panel[PANEL_ID_RIGHT]);
;
	lda     #<(_app_file_panel+17)
	ldx     #>(_app_file_panel+17)
	jsr     _Panel_ToggleActiveState
;
; ++app_active_panel_id;
;
	inc     _app_active_panel_id
;
; app_active_panel_id = app_active_panel_id % 2;
;
	lda     #$FE
	trb     _app_active_panel_id
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; signed char __near__ App_ScanDevices (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_ScanDevices: near

.segment	"CODE"

;
; uint8_t  drive_num = 0;
;
	lda     #$00
	jsr     pusha
;
; char*  the_drive_path = drive_path;
;
	jsr     decsp6
	lda     sp
	ldx     sp+1
	jsr     pushax
;
; app_connected_drive_count = 0;
;
	lda     #$00
	stz     _app_connected_drive_count
;
; for (device = DEVICE_LOWEST_DEVICE_NUM; device <= DEVICE_HIGHEST_DEVICE_NUM; device++)
;
	ldy     #$07
L039E:	sta     (sp),y
	cmp     #$04
	bcs     L005E
;
; sprintf(the_drive_path, "%u:", device);
;
	jsr     pushw0sp
	lda     #<(L0067)
	ldx     #>(L0067)
	jsr     pushax
	ldy     #$0B
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
;
; dir = Kernel_OpenDir(the_drive_path);
;
	jsr     ldax0sp
	jsr     _Kernel_OpenDir
	ldy     #$05
	jsr     staxysp
;
; if (dir)
;
	ldy     #$06
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L005F
;
; global_connected_device[drive_num] = device;
;
	lda     #<(_global_connected_device)
	ldx     #>(_global_connected_device)
	ldy     #$08
	clc
	adc     (sp),y
	bcc     L0071
	inx
L0071:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (sp),y
	sta     (ptr1)
;
; ++drive_num;
;
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; if (Kernel_CloseDir(dir) == -1)
;
	ldy     #$06
	jsr     ldaxysp
	jsr     _Kernel_CloseDir
	cpx     #$FF
	bne     L0078
	cmp     #$FF
L0078:	jsr     booleq
;
; for (device = DEVICE_LOWEST_DEVICE_NUM; device <= DEVICE_HIGHEST_DEVICE_NUM; device++)
;
L005F:	ldy     #$07
	lda     (sp),y
	ina
	bra     L039E
;
; return drive_num;
;
L005E:	iny
	ldx     #$00
	lda     (sp),y
	bpl     L0057
	dex
;
; }
;
L0057:	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ App_Initialize (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_Initialize: near

.segment	"CODE"

;
; Buffer_Clear();
;
	jsr     _Buffer_Clear
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_ShowAppAboutInfo();
;
	jsr     _Screen_ShowAppAboutInfo
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_SCANNING));
;
	lda     #$43
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; app_connected_drive_count = App_ScanDevices();
;
	jsr     _App_ScanDevices
	sta     _app_connected_drive_count
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_SHOW_DRIVE_COUNT), app_connected_drive_count);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$44
	jsr     _General_GetString
	jsr     pushax
	lda     _app_connected_drive_count
	jsr     pusha0
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; Screen_SetInitialMenuStates(app_connected_drive_count);
;
	lda     _app_connected_drive_count
	jsr     _Screen_SetInitialMenuStates
;
; app_active_panel_id = PANEL_ID_LEFT;
;
	stz     _app_active_panel_id
;
; if (app_connected_drive_count < 1)
;
	lda     _app_connected_drive_count
	bne     L0091
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_NO_DRIVES_AVAILABLE));
;
	lda     #$71
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; App_InitializePanelForMemory(PANEL_ID_LEFT, false); // TODO: replace with macro defines
;
	lda     #$00
	jsr     pusha
	jsr     _App_InitializePanelForMemory
;
; App_InitializePanelForMemory(PANEL_ID_RIGHT, true);
;
	lda     #$01
	jsr     pusha
;
; else
;
	bra     L039F
;
; App_InitializePanelForDisk(PANEL_ID_LEFT);
;
L0091:	lda     #$00
	jsr     _App_InitializePanelForDisk
;
; if (app_connected_drive_count > 1)
;
	lda     _app_connected_drive_count
	cmp     #$02
	bcc     L009F
;
; App_InitializePanelForDisk(PANEL_ID_RIGHT);
;
	lda     #$01
	jsr     _App_InitializePanelForDisk
;
; else
;
	bra     L009C
;
; App_InitializePanelForMemory(PANEL_ID_RIGHT, false);
;
L009F:	lda     #$01
	jsr     pusha
	dea
L039F:	jsr     _App_InitializePanelForMemory
;
; app_file_panel[PANEL_ID_LEFT].active_ = true; // we always start out with left panel being the active one
;
L009C:	lda     #$01
	sta     _app_file_panel+13
;
; app_file_panel[PANEL_ID_RIGHT].active_ = false; // we always start out with left panel being the active one
;
	stz     _app_file_panel+30
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ App_InitializePanelForDisk (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_InitializePanelForDisk: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t    the_drive_index = panel_id;
;
	lda     (sp)
	jsr     pusha
;
; char*    the_drive_path = drive_path;
;
	jsr     decsp4
	lda     sp
	ldx     sp+1
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; sprintf(the_drive_path, "%u:", global_connected_device[the_drive_index]);
;
	jsr     pushw0sp
	lda     #<(L00B5)
	ldx     #>(L00B5)
	jsr     pushax
	lda     #<(_global_connected_device)
	ldx     #>(_global_connected_device)
	ldy     #$0A
	clc
	adc     (sp),y
	bcc     L00B9
	inx
L00B9:	ldy     #$00
	jsr     ldaidx
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; if ( (app_file_panel[panel_id].root_folder_ = Folder_NewOrReset(app_file_panel[panel_id].root_folder_, global_connected_device[the_drive_index], the_drive_path) ) == NULL)
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushw
	ldy     #$0A
	lda     (sp),y
	tay
	lda     _global_connected_device,y
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	jsr     _Folder_NewOrReset
	ldy     #$00
	jsr     staxspidx
	cpx     #$00
	bne     L00BA
	cmp     #$00
	bne     L00BA
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ALLOC_FAIL));
;
	lda     #$80
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; App_Exit(ERROR_COULD_NOT_CREATE_ROOT_FOLDER_OBJ);
;
	lda     #$7D
	jsr     _App_Exit
;
; panel_x_offset = UI_RIGHT_PANEL_X_DELTA * panel_id; // panel id is either 0 or 1.
;
L00BA:	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$2D
	jsr     tosumula0
	ldy     #$05
	sta     (sp),y
;
; panel_id,
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
;
; &app_file_panel[panel_id],
;
	ldy     #$08
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushax
;
; PARAM_INITIALIZE_FOR_DISK,
;
	lda     #$01
	jsr     pusha
;
; (UI_LEFT_PANEL_BODY_X1 + panel_x_offset + 1), (UI_VIEW_PANEL_BODY_Y1 + 2),
;
	ldy     #$09
	lda     (sp),y
	ina
	jsr     pusha
	lda     #$08
	jsr     pusha
;
; (UI_VIEW_PANEL_BODY_WIDTH - 2), (UI_VIEW_PANEL_BODY_HEIGHT - 3)
;
	lda     #$21
	jsr     pusha
;
; );
;
	lda     #$29
	jsr     _Panel_Initialize
;
; Panel_SetCurrentDevice(&app_file_panel[panel_id], global_connected_device[the_drive_index]);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushax
	lda     #<(_global_connected_device)
	ldx     #>(_global_connected_device)
	ldy     #$08
	clc
	adc     (sp),y
	bcc     L00E2
	inx
L00E2:	ldy     #$00
	jsr     ldaidx
	ldx     #$00
	cmp     #$80
	bcc     L00E3
	dex
L00E3:	jsr     _Panel_SetCurrentDevice
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ App_InitializePanelForMemory (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_InitializePanelForMemory: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	jsr     decsp1
	lda     #$0C
	jsr     _App_LoadOverlay
;
; if ( (app_file_panel[panel_id].memory_system_ = MemSys_NewOrReset(app_file_panel[panel_id].memory_system_, for_flash)) == NULL)
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	ldy     #$03
	jsr     pushwidx
	ldy     #$05
	lda     (sp),y
	jsr     _MemSys_NewOrReset
	ldy     #$02
	jsr     staxspidx
	cpx     #$00
	bne     L03A3
	cmp     #$00
	bne     L03A3
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ALLOC_FAIL));
;
	lda     #$80
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; App_Exit(ERROR_COULD_NOT_CREATE_OR_RESET_MEMSYS_OBJ);
;
	lda     #$84
	jsr     _App_Exit
;
; panel_x_offset = UI_RIGHT_PANEL_X_DELTA * panel_id; // panel id is either 0 or 1.
;
	ldy     #$02
L03A3:	lda     (sp),y
	jsr     pusha0
	lda     #$2D
	jsr     tosumula0
	sta     (sp)
;
; panel_id,
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
;
; &app_file_panel[panel_id],
;
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     pushax
;
; PARAM_INITIALIZE_FOR_MEMORY,
;
	lda     #$00
	jsr     pusha
;
; (UI_LEFT_PANEL_BODY_X1 + panel_x_offset + 1), (UI_VIEW_PANEL_BODY_Y1 + 2),
;
	ldy     #$04
	lda     (sp),y
	ina
	jsr     pusha
	lda     #$08
	jsr     pusha
;
; (UI_VIEW_PANEL_BODY_WIDTH - 2), (UI_VIEW_PANEL_BODY_HEIGHT - 3)
;
	lda     #$21
	jsr     pusha
;
; );
;
	lda     #$29
	jsr     _Panel_Initialize
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ App_MainLoop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_App_MainLoop: near

.segment	"CODE"

;
; bool    exit_main_loop = false;
;
	jsr     decsp2
	lda     #$00
	jsr     pusha
;
; while (exit_main_loop == false)
;
	jsr     decsp3
	jmp     L0113
;
; Sys_EnableTextModeCursor(false);
;
L03A6:	jsr     _Sys_EnableTextModeCursor
;
; the_panel = &app_file_panel[app_active_panel_id];
;
	lda     _app_active_panel_id
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     stax0sp
;
; if (the_panel->for_disk_ == true)
;
L0112:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0115
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; app_menu_enabler.file_type_ = Folder_GetCurrentFileType(the_panel->root_folder_);
;
	jsr     ldax0sp
	jsr     ldaxi
	jsr     _Folder_GetCurrentFileType
	sta     _app_menu_enabler
;
; app_menu_enabler.for_flash_ = false;
;
	stz     _app_menu_enabler+2
;
; app_menu_enabler.is_kup_ = false;
;
	stz     _app_menu_enabler+3
;
; app_menu_enabler.is_meatloaf_ = the_panel->root_folder_->is_meatloaf_;
;
	jsr     ldax0sp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
;
; else
;
	bra     L03A4
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0115:	lda     #$0C
	jsr     _App_LoadOverlay
;
; app_menu_enabler.file_type_ = 0;
;
	stz     _app_menu_enabler
;
; app_menu_enabler.for_flash_ = the_panel->memory_system_->is_flash_;
;
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     _app_menu_enabler+2
;
; app_menu_enabler.is_kup_ = MemSys_GetCurrentRowKUPState(the_panel->memory_system_);
;
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentRowKUPState
	sta     _app_menu_enabler+3
;
; app_menu_enabler.is_meatloaf_ = false;
;
	lda     #$00
L03A4:	sta     _app_menu_enabler+4
;
; app_menu_enabler.for_disk_ = the_panel->for_disk_;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	sta     _app_menu_enabler+1
;
; app_menu_enabler.other_panel_for_disk_ = app_file_panel[(app_active_panel_id + 1) % 2].for_disk_;
;
	lda     _app_active_panel_id
	ina
	and     #$01
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	sta     ptr1
	txa
	adc     #>(_app_file_panel)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	sta     _app_menu_enabler+6
;
; app_menu_enabler.other_panel_for_flash_ = !app_menu_enabler.other_panel_for_disk_ && app_file_panel[(app_active_panel_id + 1) % 2].memory_system_->is_flash_;
;
	lda     _app_menu_enabler+6
	bne     L03A9
	lda     _app_active_panel_id
	ina
	and     #$01
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L03AA
L03A9:	lda     #$00
	bra     L013B
L03AA:	lda     #$01
L013B:	sta     _app_menu_enabler+7
;
; app_menu_enabler.other_panel_is_meatloaf_ = app_menu_enabler.other_panel_for_disk_ && app_file_panel[(app_active_panel_id + 1) % 2].root_folder_->is_meatloaf_;
;
	lda     _app_menu_enabler+6
	beq     L0142
	lda     _app_active_panel_id
	ina
	and     #$01
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0142
	lda     #$01
L0142:	sta     _app_menu_enabler+5
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_UpdateMenuStates(&app_menu_enabler);
;
	lda     #<(_app_menu_enabler)
	ldx     #>(_app_menu_enabler)
	jsr     _Screen_UpdateMenuStates
;
; Screen_RenderMenu(PARAM_ONLY_RENDER_CHANGED_ITEMS);
;
	lda     #$01
	jsr     _Screen_RenderMenu
;
; user_input = Screen_GetValidUserInput();
;
	jsr     _Screen_GetValidUserInput
	ldy     #$05
	sta     (sp),y
;
; switch (user_input)
;
	ldx     #$00
	lda     (sp),y
;
; }
;
	cmp     #$02
	jeq     L03B4
	cmp     #$06
	jeq     L03B5
	cmp     #$08
	jeq     L019D
	cmp     #$09
	jeq     L01C2
	cmp     #$0D
	jeq     L01A4
	cmp     #$0E
	jeq     L0215
	cmp     #$10
	jeq     L0210
	cmp     #$22
	jeq     L01E1
	cmp     #$30
	jeq     L03B3
	cmp     #$31
	jeq     L03B3
	cmp     #$32
	jeq     L03B3
	cmp     #$33
	jeq     L03B3
	cmp     #$38
	jeq     L03B3
	cmp     #$39
	jeq     L03B3
	cmp     #$43
	jeq     L01F4
	cmp     #$46
	jeq     L01AB
	cmp     #$4D
	jeq     L01EA
	cmp     #$4E
	jeq     L0151
	cmp     #$52
	jeq     L01DD
	cmp     #$53
	jeq     L0157
	cmp     #$54
	jeq     L015D
	cmp     #$61
	jeq     L020D
	cmp     #$62
	jeq     L0230
	cmp     #$63
	jeq     L0189
	cmp     #$64
	jeq     L0237
	cmp     #$66
	jeq     L01B5
	cmp     #$67
	jeq     L01BA
	cmp     #$68
	jeq     L03AF
	cmp     #$6C
	jeq     L01A4
	cmp     #$6D
	jeq     L01EF
	cmp     #$70
	jeq     L0192
	cmp     #$71
	jeq     L023E
	cmp     #$72
	jeq     L0198
	cmp     #$74
	jeq     L03B0
	cmp     #$78
	jeq     L019D
	cmp     #$7A
	jeq     L01B0
	cmp     #$FF
	jeq     L03B8
	jmp     L03B6
;
; the_panel->sort_compare_function_ = (void*)&File_CompareName;
;
L0151:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #<(_File_CompareName)
	ldy     #$0F
	sta     (ptr1),y
	iny
	lda     #>(_File_CompareName)
	sta     (ptr1),y
;
; Panel_SortAndDisplay(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_SortAndDisplay
;
; break;
;
	jmp     L014D
;
; the_panel->sort_compare_function_ = (void*)&File_CompareSize;
;
L0157:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #<(_File_CompareSize)
	ldy     #$0F
	sta     (ptr1),y
	iny
	lda     #>(_File_CompareSize)
	sta     (ptr1),y
;
; Panel_SortAndDisplay(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_SortAndDisplay
;
; break;
;
	jmp     L014D
;
; the_panel->sort_compare_function_ = (void*)&File_CompareFileTypeID;
;
L015D:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #<(_File_CompareFileTypeID)
	ldy     #$0F
	sta     (ptr1),y
	iny
	lda     #>(_File_CompareFileTypeID)
	sta     (ptr1),y
;
; Panel_SortAndDisplay(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_SortAndDisplay
;
; break;
;
	jmp     L014D
;
; global_clock_is_visible = false;
;
L03AF:	stz     _global_clock_is_visible
;
; success = Panel_ViewCurrentFile(the_panel, PARAM_VIEW_AS_HEX);
;
	jsr     pushw0sp
	lda     #$00
	jsr     _Panel_ViewCurrentFile
	ldy     #$02
	sta     (sp),y
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_Render(); // the hex view has completely overwritten the screen
;
	jsr     _Screen_Render
;
; Screen_RenderMenu(PARAM_RENDER_ALL_MENU_ITEMS);
;
	lda     #$00
	jsr     _Screen_RenderMenu
;
; Panel_RenderContents(&app_file_panel[PANEL_ID_LEFT]);
;
	lda     #<(_app_file_panel)
	ldx     #>(_app_file_panel)
	jsr     _Panel_RenderContents
;
; Panel_RenderContents(&app_file_panel[PANEL_ID_RIGHT]);
;
	lda     #<(_app_file_panel+17)
	ldx     #>(_app_file_panel+17)
	jsr     _Panel_RenderContents
;
; break;
;
	jmp     L014D
;
; global_clock_is_visible = false;
;
L03B0:	stz     _global_clock_is_visible
;
; success = Panel_ViewCurrentFile(the_panel, PARAM_VIEW_AS_TEXT);
;
	jsr     pushw0sp
	lda     #$01
	jsr     _Panel_ViewCurrentFile
	ldy     #$02
	sta     (sp),y
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_Render(); // the hex view has completely overwritten the screen
;
	jsr     _Screen_Render
;
; Screen_RenderMenu(PARAM_RENDER_ALL_MENU_ITEMS);
;
	lda     #$00
	jsr     _Screen_RenderMenu
;
; Panel_RenderContents(&app_file_panel[PANEL_ID_LEFT]);
;
	lda     #<(_app_file_panel)
	ldx     #>(_app_file_panel)
	jsr     _Panel_RenderContents
;
; Panel_RenderContents(&app_file_panel[PANEL_ID_RIGHT]);
;
	lda     #<(_app_file_panel+17)
	ldx     #>(_app_file_panel+17)
	jsr     _Panel_RenderContents
;
; break;
;
	jmp     L014D
;
; success = Panel_CopyCurrentFile(the_panel, &app_file_panel[(app_active_panel_id + 1) % 2]);
;
L0189:	jsr     pushw0sp
	lda     _app_active_panel_id
	ina
	and     #$01
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     _Panel_CopyCurrentFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_CopyCurrentFile(the_panel, the_panel); // to duplicate, we just pass same panel as target.
;
L0192:	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	jsr     _Panel_CopyCurrentFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_RenameCurrentFile(the_panel);
;
L0198:	jsr     ldax0sp
	jsr     _Panel_RenameCurrentFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_DeleteCurrentFile(the_panel);
;
L019D:	jsr     ldax0sp
	jsr     _Panel_DeleteCurrentFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_OpenCurrentFileOrFolder(the_panel);
;
L01A4:	jsr     ldax0sp
	jsr     _Panel_OpenCurrentFileOrFolder
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_FillCurrentBank(the_panel);
;
L01AB:	jsr     ldax0sp
	jsr     _Panel_FillCurrentBank
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_ClearCurrentBank(the_panel);
;
L01B0:	jsr     ldax0sp
	jsr     _Panel_ClearCurrentBank
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_SearchCurrentBank(the_panel);
;
L01B5:	jsr     ldax0sp
	jsr     _Panel_SearchCurrentBank
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; App_LoadOverlay(OVERLAY_EM);
;
L01BA:	lda     #$0A
	jsr     _App_LoadOverlay
;
; success = global_find_next_enabled = EM_SearchMemory(PARAM_START_AFTER_LAST_HIT);
;
	lda     #$00
	jsr     _EM_SearchMemory
	sta     _global_find_next_enabled
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; App_SwapActivePanel();
;
L01C2:	jsr     _App_SwapActivePanel
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_SwapCopyDirectionIndicator();
;
	jsr     _Screen_SwapCopyDirectionIndicator
;
; the_panel = &app_file_panel[app_active_panel_id];
;
	lda     _app_active_panel_id
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     stax0sp
;
; break;
;
	jmp     L014D
;
; new_device_num = user_input - 48;
;
L03B3:	lda     (sp),y
	ldy     #$30
	jsr     decaxy
	ldy     #$04
	sta     (sp),y
;
; success = Panel_SwitchDevice(the_panel, new_device_num);
;
	jsr     pushw0sp
	ldy     #$06
	lda     (sp),y
	ldx     #$00
	jsr     _Panel_SwitchDevice
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; Panel_Refresh(the_panel);
;
L01DD:	jsr     ldax0sp
	jsr     _Panel_Refresh
;
; break;
;
	jmp     L014D
;
; success = Panel_FormatDrive(the_panel);
;
L01E1:	jsr     ldax0sp
	jsr     _Panel_FormatDrive
	ldy     #$02
	sta     (sp),y
;
; if (success)
;
	lda     (sp),y
	jeq     L014D
;
; Panel_Refresh(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_Refresh
;
; break;
;
	jmp     L014D
;
; success = Panel_OpenMeatloafURL(the_panel);
;
L01EA:	jsr     ldax0sp
	jsr     _Panel_OpenMeatloafURL
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_MakeDir(the_panel);
;
L01EF:	jsr     ldax0sp
	jsr     _Panel_MakeDir
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
L01F4:	lda     #$08
	jsr     _App_LoadOverlay
;
; General_Strlcpy(global_string_buff1, General_GetString(ID_STR_DLG_SET_CLOCK_TITLE), APP_DIALOG_WIDTH);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$0C
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$2A
	jsr     _General_Strlcpy
;
; *global_string_buff2 = 0; // don't provide a default value, show empty string
;
	lda     _global_string_buff2+1
	sta     ptr1+1
	lda     _global_string_buff2
	sta     ptr1
	lda     #$00
	sta     (ptr1)
;
; global_string_buff1,
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
;
; General_GetString(ID_STR_DLG_SET_CLOCK_BODY),
;
	lda     #$0D
	jsr     _General_GetString
	jsr     pushax
;
; global_string_buff2,
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
;
; 14) != NULL)
;
	lda     #$0E
	jsr     _Screen_GetStringFromUser
	cpx     #$00
	bne     L03B9
	cmp     #$00
	beq     L01FE
;
; success = Sys_UpdateRTC(global_string_buff2);
;
L03B9:	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     _Sys_UpdateRTC
	ldy     #$02
	sta     (sp),y
;
; App_DisplayTime();
;
	jsr     _App_DisplayTime
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
L01FE:	lda     #$09
	jsr     _App_LoadOverlay
;
; break;
;
	jmp     L014D
;
; Screen_ShowAppAboutInfo();
;
L020D:	jsr     _Screen_ShowAppAboutInfo
;
; break;
;
	jmp     L014D
;
; success = Panel_SelectPrevFile(the_panel);
;
L0210:	jsr     ldax0sp
	jsr     _Panel_SelectPrevFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; success = Panel_SelectNextFile(the_panel);
;
L0215:	jsr     ldax0sp
	jsr     _Panel_SelectNextFile
	ldy     #$02
;
; break;
;
	jmp     L03A5
;
; if (app_active_panel_id == PANEL_ID_RIGHT)
;
L03B4:	lda     _app_active_panel_id
	cmp     #$01
	jne     L03B8
;
; App_SwapActivePanel();
;
	jsr     _App_SwapActivePanel
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_SwapCopyDirectionIndicator();
;
	jsr     _Screen_SwapCopyDirectionIndicator
;
; the_panel = &app_file_panel[app_active_panel_id];
;
	lda     _app_active_panel_id
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     stax0sp
;
; break;
;
	bra     L014D
;
; if (app_active_panel_id == PANEL_ID_LEFT)
;
L03B5:	lda     _app_active_panel_id
	bne     L03B8
;
; App_SwapActivePanel();
;
	jsr     _App_SwapActivePanel
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_SwapCopyDirectionIndicator();
;
	jsr     _Screen_SwapCopyDirectionIndicator
;
; the_panel = &app_file_panel[app_active_panel_id];
;
	lda     _app_active_panel_id
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_app_file_panel)
	tay
	txa
	adc     #>(_app_file_panel)
	tax
	tya
	jsr     stax0sp
;
; break;
;
	bra     L014D
;
; Kernal_RunNamed(global_named_app_basic, 5); // this will only ever return in an error condition.
;
L0230:	lda     _global_named_app_basic
	ldx     _global_named_app_basic+1
	jsr     pushax
	lda     #$05
	jsr     _Kernal_RunNamed
;
; success = false;
;
	lda     #$00
	ldy     #$02
;
; break;
;
	bra     L03A5
;
; Kernal_RunNamed(global_named_app_dos, 3); // this will only ever return in an error condition.
;
L0237:	lda     _global_named_app_dos
	ldx     _global_named_app_dos+1
	jsr     pushax
	lda     #$03
	jsr     _Kernal_RunNamed
;
; success = false;
;
	lda     #$00
	ldy     #$02
;
; break;
;
	bra     L03A5
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
L023E:	lda     #$08
	jsr     _App_LoadOverlay
;
; General_GetString(ID_STR_DLG_ARE_YOU_SURE),
;
	lda     #$01
	jsr     _General_GetString
	jsr     pushax
;
; ID_STR_DLG_QUIT_CONFIRM,
;
	lda     #$00
	jsr     pusha
;
; ID_STR_DLG_YES,
;
	lda     #$07
	jsr     pusha
;
; ) == 1)
;
	ina
	jsr     _Screen_ShowUserTwoButtonDialog
	cmp     #$01
	bne     L014D
;
; exit_main_loop = true;
;
	ldy     #$03
;
; continue;
;
	bra     L03A5
;
; user_input = ACTION_INVALID_INPUT;
;
L03B6:	lda     #$FF
L03A5:	sta     (sp),y
;
; } while (user_input == ACTION_INVALID_INPUT);
;
L014D:	ldy     #$05
L03B8:	lda     (sp),y
	cmp     #$FF
	jeq     L0112
;
; while (exit_main_loop == false)
;
L0113:	ldy     #$03
	lda     (sp),y
	jeq     L03A6
;
; return 0;
;
	ldx     #$00
	txa
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; kernel_init();
;
	jsr     _kernel_init
;
; App_LoadOverlay(OVERLAY_STARTUP);
;
	lda     #$0B
	jsr     _App_LoadOverlay
;
; if (Sys_InitSystem() == false)
;
	jsr     _Sys_InitSystem
	cmp     #$00
	bne     L036D
;
; App_Exit(ERROR_COULD_NOT_INIT_SYSTEM);
;
	lda     #$85
	jsr     _App_Exit
;
; Sys_SetBorderSize(0, 0); // want all 80 cols and 60 rows!
;
L036D:	lda     #$00
	jsr     pusha
	jsr     _Sys_SetBorderSize
;
; Buffer_Initialize();
;
	jsr     _Buffer_Initialize
;
; Startup_InitializeRandomNumGen();
;
	jsr     _Startup_InitializeRandomNumGen
;
; Startup_LoadString();
;
	jsr     _Startup_LoadString
;
; Startup_ShowLogo();
;
	jsr     _Startup_ShowLogo
;
; App_InitializeDialogBox();
;
	jsr     _App_InitializeDialogBox
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_Render();
;
	jsr     _Screen_Render
;
; App_Initialize();
;
	jsr     _App_Initialize
;
; Panel_Refresh(&app_file_panel[PANEL_ID_LEFT]);
;
	lda     #<(_app_file_panel)
	ldx     #>(_app_file_panel)
	jsr     _Panel_Refresh
;
; Panel_Refresh(&app_file_panel[PANEL_ID_RIGHT]);
;
	lda     #<(_app_file_panel+17)
	ldx     #>(_app_file_panel+17)
	jsr     _Panel_Refresh
;
; Keyboard_InitiateMinuteHand();
;
	jsr     _Keyboard_InitiateMinuteHand
;
; App_DisplayTime();
;
	jsr     _App_DisplayTime
;
; App_MainLoop();
;
	jsr     _App_MainLoop
;
; App_Exit(ERROR_NO_ERROR); // ERROR_NO_ERROR
;
	lda     #$00
	jsr     _App_Exit
;
; return 0;
;
	ldx     #$00
	txa
;
; }
;
	rts

.endproc
