; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_free
	.import		_App_EMDataCopy
	.import		_App_Exit
	.export		_Bank_Init
	.export		_Bank_Reset
	.export		_Bank_UpdatePos
	.export		_Bank_IsSelected
	.export		_Bank_Clear
	.export		_Bank_Fill
	.export		_Bank_AskForFillValue
	.export		_Bank_MarkSelected
	.export		_Bank_MarkUnSelected
	.export		_Bank_Render
	.import		_Buffer_NewMessage
	.import		_General_GetString
	.import		_General_StrlcpyWithAlloc
	.import		_General_Strlcpy
	.import		_General_Strnlen
	.import		_snprintf
	.import		_Text_FillBox
	.import		_Text_Invert
	.import		_Text_SetXY
	.import		_Text_DrawStringAtXY
	.import		_Text_DisplayTextEntryDialog
	.import		_memset
	.import		_global_dlg
	.import		_global_dlg_title
	.import		_global_dlg_body_msg
	.import		_temp_screen_buffer_char
	.import		_temp_screen_buffer_attr
	.import		_global_string_buff1
	.import		_global_string_buff2

.segment	"DATA"

_bank_non_kup_name:
	.addr	L001B
_bank_non_kup_description:
	.addr	L001D
_bank_kup_component_description:
	.addr	L001F

.segment	"RODATA"

L001F:
	.byte	$54,$68,$69,$73,$20,$62,$61,$6E,$6B,$20,$63,$6F,$6E,$74,$61,$69
	.byte	$6E,$73,$20,$70,$61,$72,$74,$20,$6F,$66,$20,$61,$20,$4B,$55,$50
	.byte	$20,$70,$72,$6F,$67,$72,$61,$6D,$00
L001D:
	.byte	$54,$68,$69,$73,$20,$62,$61,$6E,$6B,$20,$69,$73,$20,$6E,$6F,$74
	.byte	$20,$61,$20,$4B,$55,$50,$20,$28,$6E,$61,$6D,$65,$64,$29,$20,$62
	.byte	$61,$6E,$6B,$00
L0149:
	.byte	$25,$30,$36,$6C,$58,$00
L0167:
	.byte	$25,$30,$32,$58,$00
L001B:
	.byte	$7E,$00

; ---------------------------------------------------------------
; void __near__ Bank_Init (__near__ struct FMBankObject *, __near__ const unsigned char *, __near__ const unsigned char *, int, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_Init: near

.segment	"RODATA"

L003A:
	.word	$0000
L0043:
	.word	$0000
L0052:
	.word	$0000

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pusha
;
; if (the_bank_type == BANK_KUP_PRIMARY)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0191
;
; if ( (the_bank->name_ = General_StrlcpyWithAlloc(the_name, FILE_MAX_FILENAME_SIZE)) == NULL)
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0B
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_StrlcpyWithAlloc
	ldy     #$0A
	jsr     staxspidx
	cpx     #$00
	bne     L0192
	cmp     #$00
;
; goto error;
;
	jeq     L0039
;
; if ( (the_bank->description_ = General_StrlcpyWithAlloc(the_description, FILE_MAX_FILENAME_SIZE)) == NULL)
;
L0192:	iny
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_StrlcpyWithAlloc
	ldy     #$0C
	jsr     staxspidx
	cpx     #$00
	bne     L0193
	cmp     #$00
;
; goto error;
;
	jeq     L0039
;
; the_bank->is_kup_ = true;
;
L0193:	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
;
; else if (the_bank_type == BANK_KUP_SECONDARY)
;
	bra     L0195
L0191:	lda     (sp),y
	bne     L0047
	dey
	lda     (sp),y
	cmp     #$01
	bne     L0047
;
; if ( (the_bank->name_ = General_StrlcpyWithAlloc(the_name, FILE_MAX_FILENAME_SIZE)) == NULL)
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0B
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_StrlcpyWithAlloc
	ldy     #$0A
	jsr     staxspidx
	cpx     #$00
	bne     L0194
	cmp     #$00
;
; goto error;
;
	beq     L0039
;
; the_bank->description_ = bank_kup_component_description;
;
L0194:	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     _bank_kup_component_description
	ldy     #$0C
	sta     (ptr1),y
	iny
	lda     _bank_kup_component_description+1
;
; else
;
	bra     L01A1
;
; the_bank->name_ = bank_non_kup_name;
;
L0047:	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     _bank_non_kup_name
	ldy     #$0A
	sta     (ptr1),y
	iny
	lda     _bank_non_kup_name+1
	sta     (ptr1),y
;
; the_bank->description_ = bank_non_kup_description;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     _bank_non_kup_description
	ldy     #$0C
	sta     (ptr1),y
	iny
	lda     _bank_non_kup_description+1
L01A1:	sta     (ptr1),y
;
; the_bank->is_kup_ = false;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
L0195:	sta     (ptr1)
;
; the_bank->selected_ = false;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
;
; return;
;
	bra     L01BB
;
; if (the_bank) {
;
L0039:	ldy     #$09
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L002D
;
; Bank_Reset(the_bank);
;
	iny
	jsr     ldaxysp
	jsr     _Bank_Reset
;
; the_bank->name_ = bank_non_kup_name;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     _bank_non_kup_name
	ldy     #$0A
	sta     (ptr1),y
	iny
	lda     _bank_non_kup_name+1
	sta     (ptr1),y
;
; the_bank->description_ = bank_non_kup_description;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     _bank_non_kup_description
	ldy     #$0C
	sta     (ptr1),y
	iny
	lda     _bank_non_kup_description+1
	sta     (ptr1),y
;
; the_bank->is_kup_ = false;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
L01BB:	sta     (ptr1),y
;
; the_bank->row_ = the_row;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$05
	sta     (ptr1),y
;
; the_bank->bank_num_ = the_bank_num;
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	ldy     #$01
	jsr     staspidx
;
; the_bank->addr_ = (uint32_t)the_bank_num * 8192;
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     shleax4
	jsr     shleax1
	ldy     #$06
	jsr     steaxspidx
;
; }
;
L002D:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Bank_Reset (__near__ struct FMBankObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_Reset: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pushax
;
; if (the_bank == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L01BF
;
; App_Exit(ERROR_BANK_TO_DESTROY_WAS_NULL); // crash early, crash often
;
	lda     #$81
	jsr     _App_Exit
;
; if ( (the_bank)->name_ != NULL && (the_bank)->name_ != bank_non_kup_name)
;
L01BF:	jsr     ldax0sp
	ldy     #$0B
	jsr     ldaxidx
	cpx     #$00
	bne     L01C0
	cmp     #$00
	beq     L007D
L01C0:	jsr     ldax0sp
	ldy     #$0B
	jsr     ldaxidx
	cpx     _bank_non_kup_name+1
	bne     L007E
	cmp     _bank_non_kup_name
	beq     L007D
;
; free((the_bank)->name_);
;
L007E:	jsr     ldax0sp
	ldy     #$0B
	jsr     ldaxidx
	jsr     _free
;
; (the_bank)->name_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if ((the_bank)->description_ != NULL && (the_bank)->description_ != bank_kup_component_description && (the_bank)->description_ != bank_non_kup_description)
;
L007D:	jsr     ldax0sp
	ldy     #$0D
	jsr     ldaxidx
	cpx     #$00
	bne     L01C1
	cmp     #$00
	beq     L008A
L01C1:	jsr     ldax0sp
	ldy     #$0D
	jsr     ldaxidx
	cpx     _bank_kup_component_description+1
	bne     L01C2
	cmp     _bank_kup_component_description
	beq     L008A
L01C2:	jsr     ldax0sp
	ldy     #$0D
	jsr     ldaxidx
	cpx     _bank_non_kup_description+1
	bne     L008B
	cmp     _bank_non_kup_description
	jeq     incsp2
;
; free((the_bank)->description_);
;
L008B:	jsr     ldax0sp
	ldy     #$0D
	jsr     ldaxidx
	jsr     _free
;
; (the_bank)->description_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0C
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; }
;
L008A:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Bank_UpdatePos (__near__ struct FMBankObject *, unsigned char, signed char, unsigned int)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_UpdatePos: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pushax
;
; if (the_bank == NULL)
;
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
;
; return;
;
	beq     L0098
;
; the_bank->x_ = x;
;
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	sta     (ptr1),y
;
; the_bank->display_row_ = display_row;
;
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$04
	sta     (ptr1),y
;
; the_bank->row_ = row;
;
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$05
	sta     (ptr1),y
;
; }
;
L0098:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Bank_IsSelected (__near__ struct FMBankObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_IsSelected: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pushax
;
; if (the_bank == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L01C3
;
; return false;
;
	tax
	jmp     incsp2
;
; return the_bank->selected_;
;
L01C3:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	ldx     #$00
	lda     (ptr1),y
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Bank_Clear (__near__ struct FMBankObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_Clear: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pushax
;
; Bank_Fill(the_bank, 0);
;
	jsr     pushw0sp
	lda     #$00
	jsr     _Bank_Fill
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Bank_Fill (__near__ struct FMBankObject *, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_Fill: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pusha
;
; char*  the_buffer = (char*)STORAGE_FILE_BUFFER_1;
;
	jsr     decsp1
	ldx     #$05
	lda     #$00
	jsr     pushax
;
; memset(the_buffer, the_fill_value, STORAGE_FILE_BUFFER_1_LEN);
;
	jsr     pushw0sp
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldx     #$01
	lda     #$00
	jsr     _memset
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
	lda     #$00
	ldy     #$02
L01C6:	sta     (sp),y
	cmp     #$20
	bcs     L00B4
;
; App_EMDataCopy((uint8_t*)the_buffer, the_bank->bank_num_, i, PARAM_COPY_TO_EM);
;
	jsr     pushw0sp
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _App_EMDataCopy
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
	ldy     #$02
	lda     (sp),y
	ina
	bra     L01C6
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_BANK_FILLED_WITH), the_bank->bank_num_, the_fill_value, the_fill_value);
;
L00B4:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$13
	jsr     _General_GetString
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	jsr     pusha0
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	ldy     #$0C
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ Bank_AskForFillValue (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_AskForFillValue: near

.segment	"OVERLAY_MEMSYS"

;
; uint16_t   the_fill_value = 0;
;
	jsr     decsp2
	jsr     push0
;
; bool    take_char_value = false;
;
	jsr     decsp1
	jsr     pusha
;
; General_Strlcpy((char*)&global_dlg_title, General_GetString(ID_STR_DLG_FILL_BANK_TITLE), sizeof(global_dlg_title));
;
	lda     #<(_global_dlg_title)
	ldx     #>(_global_dlg_title)
	jsr     pushax
	lda     #$11
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$24
	jsr     _General_Strlcpy
;
; General_Strlcpy((char*)&global_dlg_body_msg, General_GetString(ID_STR_DLG_FILL_BANK_BODY), APP_DIALOG_WIDTH);
;
	lda     #<(_global_dlg_body_msg)
	ldx     #>(_global_dlg_body_msg)
	jsr     pushax
	lda     #$12
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$2A
	jsr     _General_Strlcpy
;
; global_string_buff2[0] = 0; // clear whatever string had been in this buffer before
;
	lda     _global_string_buff2+1
	sta     ptr1+1
	lda     _global_string_buff2
	sta     ptr1
	lda     #$00
	sta     (ptr1)
;
; success = Text_DisplayTextEntryDialog(&global_dlg, (char*)&temp_screen_buffer_char, (char*)&temp_screen_buffer_attr, global_string_buff2, 3, APP_ACCENT_COLOR, APP_FOREGROUND_COLOR, APP_BACKGROUND_COLOR); //len("255")=3
;
	lda     #<(_global_dlg)
	ldx     #>(_global_dlg)
	jsr     pushax
	lda     #<(_temp_screen_buffer_char)
	ldx     #>(_temp_screen_buffer_char)
	jsr     pushax
	lda     #<(_temp_screen_buffer_attr)
	ldx     #>(_temp_screen_buffer_attr)
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$03
	jsr     pusha
	dea
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     _Text_DisplayTextEntryDialog
	ldy     #$01
	sta     (sp),y
;
; if (success == false)
;
	lda     (sp),y
	bne     L00E5
;
; return -1;
;
	ldx     #$FF
	txa
	jmp     incsp6
;
; the_len = General_Strnlen(global_string_buff2, 3);
;
L00E5:	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     _General_Strnlen
	ldy     #$04
	sta     (sp),y
;
; for (i = 0; i < the_len; i++)
;
	lda     #$00
	iny
L01CD:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	bpl     L00F3
	dex
L00F3:	dey
	cmp     (sp),y
	txa
	sbc     #$00
	bcs     L00ED
;
; if (global_string_buff2[i] > 47 && global_string_buff2[i] < 58)
;
	ldx     #$00
	iny
	lda     (sp),y
	bpl     L00F9
	dex
L00F9:	clc
	adc     _global_string_buff2
	sta     ptr1
	txa
	adc     _global_string_buff2+1
	sta     ptr1+1
	lda     (ptr1)
	cmp     #$30
	bcc     L01CC
	ldx     #$00
	ldy     #$05
	lda     (sp),y
	bpl     L00FC
	dex
L00FC:	clc
	adc     _global_string_buff2
	sta     ptr1
	txa
	adc     _global_string_buff2+1
	sta     ptr1+1
	lda     (ptr1)
	cmp     #$3A
	bcs     L01CC
;
; the_fill_value = the_fill_value * 10 + (global_string_buff2[i] - 48);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     mulax10
	sta     sreg
	stx     sreg+1
	ldx     #$00
	ldy     #$05
	lda     (sp),y
	bpl     L0102
	dex
L0102:	clc
	adc     _global_string_buff2
	sta     ptr1
	txa
	adc     _global_string_buff2+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$30
	jsr     decaxy
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; else
;
	bra     L00EE
;
; take_char_value = true;
;
L01CC:	lda     #$01
	sta     (sp)
;
; for (i = 0; i < the_len; i++)
;
L00EE:	ldy     #$05
	lda     (sp),y
	ina
	jmp     L01CD
;
; if (take_char_value)
;
L00ED:	lda     (sp)
	beq     L0106
;
; the_fill_value = (uint16_t)global_string_buff2[0];
;
	lda     _global_string_buff2+1
	sta     ptr1+1
	lda     _global_string_buff2
	sta     ptr1
	lda     (ptr1)
	ldx     #$00
;
; else if (the_fill_value > 255)
;
	bra     L01CE
L0106:	dey
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bcc     L010C
;
; the_fill_value = 255;
;
	ldx     #$00
	lda     #$FF
L01CE:	ldy     #$02
	jsr     staxysp
;
; return (int16_t)the_fill_value;
;
L010C:	ldy     #$03
	jsr     ldaxysp
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Bank_MarkSelected (__near__ struct FMBankObject *, signed char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_MarkSelected: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pusha
;
; if (the_bank == NULL)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L01CF
;
; return false;
;
	tax
	jmp     incsp4
;
; if (the_bank->selected_ == false)
;
L01CF:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	ldx     #$00
	lda     (ptr1),y
	bne     L01D0
;
; the_bank->selected_ = true;
;
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$02
	sta     (ptr1),y
;
; Bank_Render(the_bank, the_bank->selected_, y_offset, as_active); // if we're here, panel must be active?
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _Bank_Render
;
; return true;
;
	ldx     #$00
L01D0:	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Bank_MarkUnSelected (__near__ struct FMBankObject *, signed char)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_MarkUnSelected: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pusha
;
; if (the_bank == NULL)
;
	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L01D1
;
; return false;
;
	tax
	jmp     incsp3
;
; if (the_bank->selected_ == true)
;
L01D1:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	ldx     #$00
	lda     (ptr1),y
	cmp     #$01
	bne     L01D2
;
; the_bank->selected_ = false;
;
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
;
; Bank_Render(the_bank, the_bank->selected_, y_offset, PARAM_MARK_SELECTION_AS_ACTIVE); // if we're here, panel must be active?
;
	ldy     #$04
	jsr     pushwysp
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _Bank_Render
;
; return true;
;
	ldx     #$00
L01D2:	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ Bank_Render (__near__ struct FMBankObject *, unsigned char, signed char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_MEMSYS"

.proc	_Bank_Render: near

.segment	"OVERLAY_MEMSYS"

;
; {
;
	jsr     pusha
;
; if (the_bank == NULL)
;
	jsr     decsp6
	ldy     #$09
	lda     (sp),y
	iny
	ora     (sp),y
;
; return;
;
	jeq     L0144
;
; if (as_active)
;
	ldy     #$06
	lda     (sp),y
	beq     L0133
;
; the_color = LIST_ACTIVE_COLOR;
;
	lda     #$0B
;
; else
;
	bra     L01D4
;
; the_color = LIST_INACTIVE_COLOR;
;
L0133:	lda     #$03
L01D4:	ldy     #$01
	sta     (sp),y
;
; x1 = the_bank->x_;
;
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	ldy     #$05
	sta     (sp),y
;
; x2 = the_bank->x_ + (UI_PANEL_INNER_WIDTH - 1);
;
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	ldx     #$00
	lda     (ptr1),y
	ldy     #$20
	jsr     incaxy
	ldy     #$04
	sta     (sp),y
;
; typex = x1 + UI_PANEL_BANK_NUM_OFFSET + 1;
;
	iny
	ldx     #$00
	lda     (sp),y
	ldy     #$15
	jsr     incaxy
	ina
	ldy     #$02
	sta     (sp),y
;
; sizex = typex + UI_PANEL_BANK_ADDR_OFFSET + 0; // "bytes" is 5 in len, but we are using 6 digit size, so start one before bytes.
;
	clc
	adc     #$05
	iny
	sta     (sp),y
;
; if (the_bank->display_row_ != -1)
;
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$04
	jsr     ldaidx
	cmp     #$FF
	jeq     L0144
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "%06lX", the_bank->addr_);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L0149)
	ldx     #>(L0149)
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	ldy     #$09
	jsr     ldeaxidx
	jsr     pusheax
	ldy     #$0A
	jsr     _snprintf
;
; y = the_bank->display_row_ + y_offset;
;
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$04
	jsr     ldaidx
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$07
	lda     (sp),y
	bpl     L014E
	dex
L014E:	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	pla
	cmp     #$80
	sta     (sp)
;
; Text_FillBox(x1, y, x2, y, CH_SPACE, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_FillBox
;
; Text_DrawStringAtXY( x1, y, the_bank->name_, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0B
	jsr     pushwidx
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; Text_DrawStringAtXY( sizex, y, global_string_buff1, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "%02X", the_bank->bank_num_);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L0167)
	ldx     #>(L0167)
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$08
	jsr     _snprintf
;
; Text_DrawStringAtXY( typex, y, global_string_buff1, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; if (as_selected == true)
;
	ldy     #$08
	lda     (sp),y
	cmp     #$01
	bne     L0144
;
; Text_SetXY(x1, y);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_Invert(UI_PANEL_INNER_WIDTH);
;
	ldx     #$00
	lda     #$21
	jsr     _Text_Invert
;
; Text_FillBox( 0, UI_FULL_PATH_LINE_Y, 79, UI_FULL_PATH_LINE_Y, CH_SPACE, APP_BACKGROUND_COLOR, APP_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	lda     #$32
	jsr     pusha
	lda     #$4F
	jsr     pusha
	lda     #$32
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _Text_FillBox
;
; Text_DrawStringAtXY( 0, UI_FULL_PATH_LINE_Y, the_bank->description_, COLOR_GREEN, APP_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	lda     #$32
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0D
	jsr     pushwidx
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; }
;
L0144:	ldy     #$0B
	jmp     addysp

.endproc
