; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_Buffer_DrawCommunicationArea
	.export		_Buffer_Initialize
	.export		_Buffer_Clear
	.export		_Buffer_RefreshDisplay
	.export		_Buffer_NewMessage
	.import		_Text_FillBox
	.import		_Text_DrawBoxCoordsFancy
	.import		_Text_DrawStringAtXY
	.import		_strlen
	.import		_memcpy
	.import		_memset
	.export		_Buffer_ScrollUp

.segment	"DATA"

_comm_curr_buff_row:
	.byte	$00

.segment	"BSS"

_comm_buff:
	.res	553,$00
_comm_row:
	.res	14,$00
_comm_row_ptr:
	.res	14,$00

; ---------------------------------------------------------------
; void __near__ Buffer_DrawCommunicationArea (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_DrawCommunicationArea: near

.segment	"CODE"

;
; COMM_BUFFER_BOX_FIRST_COL, COMM_BUFFER_BOX_FIRST_ROW,
;
	lda     #$00
	jsr     pusha
	lda     #$33
	jsr     pusha
;
; COMM_BUFFER_BOX_LAST_COL, COMM_BUFFER_BOX_LAST_ROW,
;
	lda     #$4F
	jsr     pusha
	lda     #$3B
	jsr     pusha
;
; BUFFER_ACCENT_COLOR,
;
	lda     #$0A
	jsr     pusha
;
; );
;
	lda     #$00
	jmp     _Text_DrawBoxCoordsFancy

.endproc

; ---------------------------------------------------------------
; void __near__ Buffer_Initialize (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_Initialize: near

.segment	"CODE"

;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	jsr     decsp1
	lda     #$00
L00E9:	sta     (sp)
	cmp     #$07
	bcs     L00E8
;
; comm_row[i] = &comm_buff[i * (COMM_BUFFER_NUM_COLS + 1)];
;
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L00E3
	inx
	clc
L00E3:	adc     #<(_comm_row)
	tay
	txa
	adc     #>(_comm_row)
	tax
	tya
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$4F
	jsr     tosumula0
	clc
	adc     #<(_comm_buff)
	tay
	txa
	adc     #>(_comm_buff)
	tax
	tya
	ldy     #$00
	jsr     staxspidx
;
; comm_row_ptr[i] = &comm_row[i];
;
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L00E4
	inx
	clc
L00E4:	adc     #<(_comm_row_ptr)
	sta     ptr1
	txa
	adc     #>(_comm_row_ptr)
	sta     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L00E5
	inx
	clc
L00E5:	adc     #<(_comm_row)
	tay
	txa
	adc     #>(_comm_row)
	tax
	tya
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	lda     (sp)
	ina
	bra     L00E9
;
; comm_curr_buff_row = 0;
;
L00E8:	stz     _comm_curr_buff_row
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Buffer_Clear (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_Clear: near

.segment	"CODE"

;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	jsr     decsp1
	lda     #$00
L00EE:	sta     (sp)
	cmp     #$07
	bcs     L0060
;
; *(comm_row[i]) = 0;
;
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L00EB
	inx
	clc
L00EB:	adc     #<(_comm_row)
	tay
	txa
	adc     #>(_comm_row)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	lda     (sp)
	ina
	bra     L00EE
;
; COMM_BUFFER_FIRST_COL, COMM_BUFFER_FIRST_ROW,
;
L0060:	lda     #$01
	jsr     pusha
	lda     #$34
	jsr     pusha
;
; COMM_BUFFER_LAST_COL, COMM_BUFFER_LAST_ROW,
;
	lda     #$4E
	jsr     pusha
	lda     #$3A
	jsr     pusha
;
; CH_SPACE,
;
	lda     #$20
	jsr     pusha
;
; BUFFER_FOREGROUND_COLOR,
;
	lda     #$07
	jsr     pusha
;
; );
;
	lda     #$00
	jsr     _Text_FillBox
;
; comm_curr_buff_row = 0;
;
	stz     _comm_curr_buff_row
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Buffer_RefreshDisplay (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_RefreshDisplay: near

.segment	"CODE"

;
; Text_FillBox(
;
	jsr     decsp1
;
; COMM_BUFFER_FIRST_COL, COMM_BUFFER_FIRST_ROW,
;
	lda     #$01
	jsr     pusha
	lda     #$34
	jsr     pusha
;
; COMM_BUFFER_LAST_COL, COMM_BUFFER_LAST_ROW,
;
	lda     #$4E
	jsr     pusha
	lda     #$3A
	jsr     pusha
;
; CH_SPACE,
;
	lda     #$20
	jsr     pusha
;
; BUFFER_FOREGROUND_COLOR,
;
	lda     #$07
	jsr     pusha
;
; );
;
	lda     #$00
	jsr     _Text_FillBox
;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	lda     #$00
L00F7:	sta     (sp)
	cmp     #$07
	bcc     L00F8
;
; }
;
	jmp     incsp1
;
; int8_t  this_len = strlen(*comm_row_ptr[i]);
;
L00F8:	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L00F2
	inx
	clc
L00F2:	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	jsr     ldaxi
	jsr     _strlen
	cmp     #$80
	jsr     pusha
;
; if ( this_len > COMM_BUFFER_NUM_COLS)
;
	lda     (sp)
	sec
	sbc     #$4F
	bvs     L0092
	eor     #$80
L0092:	bpl     L008E
;
; (*comm_row_ptr[i])[COMM_BUFFER_NUM_COLS] = 0;
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L00F3
	inx
	clc
L00F3:	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$4E
	sta     (ptr1),y
;
; COMM_BUFFER_FIRST_COL, COMM_BUFFER_FIRST_ROW + i,
;
L008E:	lda     #$01
	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$34
	jsr     incaxy
	jsr     pusha
;
; *comm_row_ptr[i],
;
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L00F4
	inx
	clc
L00F4:	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	jsr     pushw
;
; BUFFER_FOREGROUND_COLOR,
;
	lda     #$07
	jsr     pusha
;
; );
;
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; }
;
	jsr     incsp1
;
; for (i = 0; i < COMM_BUFFER_NUM_ROWS; i++)
;
	lda     (sp)
	ina
	jmp     L00F7

.endproc

; ---------------------------------------------------------------
; void __near__ Buffer_NewMessage (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_NewMessage: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_message == NULL) return;
;
	jsr     decsp5
	ldy     #$05
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L00FE
;
; }
;
	jmp     incsp7
;
; remaining = strlen(the_message);
;
L00FE:	jsr     ldaxysp
	jsr     _strlen
	ldy     #$03
	jsr     staxysp
;
; while (remaining) {
;
	jmp     L00A9
;
; count = remaining > COMM_BUFFER_NUM_COLS ? COMM_BUFFER_NUM_COLS : remaining;
;
L00A7:	iny
	jsr     ldaxysp
	cmp     #$4F
	txa
	sbc     #$00
	bcc     L00AE
	lda     #$4E
	bra     L00FA
L00AE:	ldy     #$03
	lda     (sp),y
L00FA:	ldy     #$02
	sta     (sp),y
;
; next = the_message + count;
;
	clc
	ldy     #$05
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	jsr     stax0sp
;
; if (remaining > count) {
;
	ldy     #$04
	jsr     ldaxysp
	sec
	ldy     #$02
	sbc     (sp),y
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	bcc     L00B5
	beq     L00B5
;
; while (count && the_message[count] != ' ') --count;
;
	bra     L00FB
L00B7:	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
L00FB:	lda     (sp),y
	beq     L00FD
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	tay
	lda     (ptr1),y
	cmp     #$20
	bne     L00B7
;
; if (!count) count = COMM_BUFFER_NUM_COLS;
;
	ldy     #$02
L00FD:	lda     (sp),y
	bne     L00BF
	lda     #$4E
	sta     (sp),y
;
; next = the_message + count;
;
L00BF:	lda     (sp),y
	clc
	ldy     #$05
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	jsr     stax0sp
;
; if (*next == ' ') ++next;
;
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	bne     L00B5
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
;
; memset(*comm_row_ptr[0], ' ', COMM_BUFFER_NUM_COLS);
;
L00B5:	lda     _comm_row_ptr
	ldx     _comm_row_ptr+1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$4D
	lda     #$20
L00CF:	sta     (ptr1),y
	dey
	bpl     L00CF
;
; memcpy(*comm_row_ptr[0], the_message, count);
;
	lda     _comm_row_ptr
	ldx     _comm_row_ptr+1
	jsr     pushw
	ldy     #$0A
	jsr     pushwysp
	ldy     #$06
	lda     (sp),y
	ldx     #$00
	jsr     _memcpy
;
; (*comm_row_ptr[0])[COMM_BUFFER_NUM_COLS] = 0;
;
	lda     _comm_row_ptr
	ldx     _comm_row_ptr+1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$4E
	sta     (ptr1),y
;
; remaining -= next - the_message;
;
	jsr     ldax0sp
	sec
	ldy     #$05
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$03
	jsr     subeqysp
;
; the_message = (char*)next;
;
	jsr     ldax0sp
	ldy     #$05
	jsr     staxysp
;
; Buffer_ScrollUp();
;
	jsr     _Buffer_ScrollUp
;
; while (remaining) {
;
L00A9:	ldy     #$04
	lda     (sp),y
	dey
	ora     (sp),y
	jne     L00A7
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ Buffer_ScrollUp (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Buffer_ScrollUp: near

.segment	"CODE"

;
; last = COMM_BUFFER_NUM_ROWS - 1;
;
	jsr     decsp5
	lda     #$06
	ldy     #$01
	sta     (sp),y
;
; next_to_last = last - 1;
;
	sec
	sbc     #$01
	cmp     #$80
	sta     (sp)
;
; temp = *comm_row_ptr[last];
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	bpl     L0022
	dex
L0022:	jsr     aslax1
	clc
	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	jsr     ldaxi
	ldy     #$03
	jsr     staxysp
;
; *comm_row_ptr[last] = *comm_row_ptr[0];
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	bpl     L0025
	dex
L0025:	jsr     aslax1
	clc
	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	sta     sreg
	stx     sreg+1
	lda     _comm_row_ptr
	ldx     _comm_row_ptr+1
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
;
; for (i = 0; i < next_to_last; i++)
;
	lda     #$00
	iny
L0103:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	bpl     L002F
	ldx     #$FF
L002F:	jsr     tosicmp
	bcs     L0029
;
; *comm_row_ptr[i] = *comm_row_ptr[i + 1];
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0100
	inx
	clc
L0100:	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	sta     sreg
	stx     sreg+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	ina
	bne     L0035
	inx
L0035:	jsr     aslax1
	clc
	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
;
; for (i = 0; i < next_to_last; i++)
;
	iny
	lda     (sp),y
	ina
	bra     L0103
;
; *comm_row_ptr[next_to_last] = temp;
;
L0029:	ldx     #$00
	lda     (sp)
	bpl     L0038
	dex
L0038:	jsr     aslax1
	clc
	adc     #<(_comm_row_ptr)
	tay
	txa
	adc     #>(_comm_row_ptr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; Buffer_RefreshDisplay();
;
	jsr     _Buffer_RefreshDisplay
;
; }
;
	jmp     incsp5

.endproc
