; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_global_file_bytes_loaded
	.export		_global_file_load_limit

	.export		_File_UpdatePos
	.export		_File_UpdateFileName
	.export		_File_IsSelected
	.export		_File_ReadFontData
	.export		_File_LoadFileToEM
	.export		_File_CheckForFile
	.export		_File_Delete
	.export		_File_Rename
	.export		_File_MarkSelected
	.export		_File_MarkUnSelected
	.export		_File_Render
	.export		_File_CompareSize
	.export		_File_CompareName
	.export		_File_CompareFileTypeID
	.import		_calloc
	.import		_free
	.import		_App_EMDataCopy
	.import		_App_Exit
	.import		_App_GetFilenameFromEM
	.import		_App_SetFilenameInEM
	.import		_Buffer_NewMessage
	.import		_General_GetString
	.import		_General_Strncasecmp
	.import		_General_ExtractFileExtensionFromFilename
	.import		_Kernel_DeleteFile
	.import		_Kernel_DeleteFolder
	.import		_fclose
	.import		_ferror
	.import		_fopen
	.import		_fread
	.import		_rename
	.import		_snprintf
	.import		_Text_FillBox
	.import		_Text_Invert
	.import		_Text_SetXY
	.import		_Text_DrawStringAtXY
	.import		_Sys_SwapIOPage
	.import		_Sys_RestoreIOPage
	.import		_memcpy
	.import		_memset
	.import		_global_string_buff1
	.import		_global_retrieved_em_filename
	.export		_File_GetFileTypeFromExtension
	.export		_File_GetFileTypeString

.segment	"DATA"

.segment	"OVERLAY_DISKSYS"
_file_compare_filename_buffer:
	.byte	$00
	.res	31,$00
_file_compare_filename:
	.addr	_file_compare_filename_buffer
_temp_file_extension_buffer:
	.byte	$00
	.res	7,$00
.segment	"DATA"
_global_file_load_limit:
	.word	$FF00

.segment	"RODATA"

L0264:
	.byte	$25,$35,$6C,$75,$4B,$00
L026B:
	.byte	$25,$35,$6C,$75,$4D,$00
L025B:
	.byte	$25,$36,$6C,$75,$00
L00B0:
	.byte	$32,$35,$36,$00
L00C2:
	.byte	$75,$72,$6C,$00
L002C:
	.byte	$70,$67,$5A,$00
L0031:
	.byte	$70,$67,$58,$00
L003B:
	.byte	$62,$61,$73,$00
L0044:
	.byte	$74,$78,$74,$00
L004D:
	.byte	$6D,$6F,$64,$00
L0056:
	.byte	$6D,$69,$64,$00
L005F:
	.byte	$76,$67,$6D,$00
L0068:
	.byte	$72,$73,$64,$00
L0071:
	.byte	$6D,$70,$33,$00
L007A:
	.byte	$6F,$67,$67,$00
L0083:
	.byte	$77,$61,$76,$00
L008C:
	.byte	$70,$67,$78,$00
L0095:
	.byte	$66,$6E,$74,$00
L009E:
	.byte	$6B,$75,$70,$00
L00A7:
	.byte	$6C,$62,$6D,$00
L00B9:
	.byte	$73,$72,$63,$00
L01A8:
	.byte	$72,$62,$00
L0177	:=	L01A8+0
L01E2:
	.byte	$72,$00

.segment	"BSS"

_global_file_bytes_loaded:
	.res	2,$00

; ---------------------------------------------------------------
; __near__ struct WB2KFileObject * __near__ File_New (unsigned char, __near__ const unsigned char *, unsigned char, unsigned long, unsigned char, unsigned char, __near__ struct DateTime *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"



; ---------------------------------------------------------------
; void __near__ File_Destroy (__near__ __near__ struct WB2KFileObject * *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"



; ---------------------------------------------------------------
; void __near__ File_UpdatePos (__near__ struct WB2KFileObject *, unsigned char, signed char, unsigned int)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_UpdatePos: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_file == NULL)
;
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
;
; return;
;
	beq     L0152
;
; the_file->x_ = x;
;
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	ldy     #$0F
	sta     (ptr1),y
;
; the_file->display_row_ = display_row;
;
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$11
	sta     (ptr1),y
;
; the_file->row_ = row;
;
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$10
	sta     (ptr1),y
;
; }
;
L0152:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_UpdateFileName (__near__ struct WB2KFileObject *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_UpdateFileName: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_file == NULL)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L02D4
;
; return false;
;
	tax
	jmp     incsp4
;
; App_SetFilenameInEM(the_file, new_file_name);
;
L02D4:	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     _App_SetFilenameInEM
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_IsSelected (__near__ struct WB2KFileObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_IsSelected: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_file == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L02D5
;
; return false;
;
	tax
	jmp     incsp2
;
; return the_file->selected_;
;
L02D5:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	ldx     #$00
	lda     (ptr1),y
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_ReadFontData (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_ReadFontData: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; uint16_t remaining = TEXT_FONT_BYTE_SIZE;
;
	jsr     decsp2
	ldx     #$08
	lda     #$00
	jsr     pushax
;
; uint8_t* font = (uint8_t*)FONT_MEMORY_BANK0;
;
	jsr     decsp2
	ldx     #$C0
	lda     #$00
	jsr     pushax
;
; uint8_t* buffer = (uint8_t*)STORAGE_FILE_BUFFER_1;
;
	ldx     #$05
	jsr     pushax
;
; if (!the_file_path) return false;
;
	ldy     #$0B
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0171
	tax
	jmp     L016C
;
; handle = fopen(the_file_path, "rb");
;
L0171:	ldy     #$0D
	jsr     pushwysp
	lda     #<(L0177)
	ldx     #>(L0177)
	jsr     _fopen
	ldy     #$08
	jsr     staxysp
;
; if (!handle) return false;
;
	ldy     #$09
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L017E
	tax
	jmp     L016C
;
; count = remaining < 256 ? remaining : 256;
;
L017C:	ldy     #$07
	jsr     ldaxysp
	cpx     #$01
	bcs     L0182
	ldy     #$07
	jsr     ldaxysp
	bra     L0184
L0182:	ldx     #$01
	lda     #$00
L0184:	ldy     #$04
	jsr     staxysp
;
; if (fread(buffer, 1, count, handle) != count) { fclose(handle); return false; }
;
	jsr     pushw0sp
	lda     #$01
	jsr     pusha0
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0F
	jsr     ldaxysp
	jsr     _fread
	ldy     #$04
	cmp     (sp),y
	bne     L02D7
	txa
	iny
	cmp     (sp),y
	beq     L0186
L02D7:	ldy     #$09
	jsr     ldaxysp
	jsr     _fclose
	ldx     #$00
	txa
	bra     L016C
;
; Sys_SwapIOPage(VICKY_IO_PAGE_FONT_AND_LUTS);
;
L0186:	lda     #$01
	jsr     _Sys_SwapIOPage
;
; memcpy(font, buffer, count);
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	jsr     _memcpy
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; font += count;
;
	ldy     #$05
	jsr     ldaxysp
	ldy     #$02
	jsr     addeqysp
;
; remaining -= count;
;
	ldy     #$05
	jsr     ldaxysp
	ldy     #$06
	jsr     subeqysp
;
; while (remaining) {
;
L017E:	ldy     #$07
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L017C
;
; return fclose(handle) == 0;
;
	ldy     #$09
	jsr     ldaxysp
	jsr     _fclose
	cpx     #$00
	bne     L019C
	cmp     #$00
L019C:	jsr     booleq
;
; }
;
L016C:	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_LoadFileToEM (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_LoadFileToEM: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; uint16_t page = 0;
;
	jsr     decsp2
	jsr     push0
;
; uint8_t* buffer = (uint8_t*)STORAGE_FILE_BUFFER_1;
;
	jsr     decsp4
	ldx     #$05
	lda     #$00
	jsr     pushax
;
; global_file_bytes_loaded = 0;
;
	tax
	stz     _global_file_bytes_loaded
	stz     _global_file_bytes_loaded+1
;
; if (!the_file_path) return false;
;
	ldy     #$0C
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L019D
;
; handle = fopen(the_file_path, "rb");
;
	ldy     #$0E
	jsr     pushwysp
	lda     #<(L01A8)
	ldx     #>(L01A8)
	jsr     _fopen
	ldy     #$08
	jsr     staxysp
;
; if (!handle) return false;
;
	ldy     #$09
	lda     (sp),y
	dey
	ora     (sp),y
	jne     L01AF
	tax
	jmp     L019D
;
; bank = em_bank_num + page / PAGES_PER_BANK;
;
L01AD:	ldy     #$0A
	lda     (sp),y
	jsr     pusha0
	ldy     #$09
	jsr     ldaxysp
	jsr     shrax4
	jsr     shrax1
	jsr     tosaddax
	ldy     #$04
	jsr     staxysp
;
; if ((uint32_t)global_file_bytes_loaded + count > global_file_load_limit || page >= 255 || bank <= OVERLAY_MEMSYSTEM || bank >= MEMORY_BANK_COUNT ||
;
	lda     _global_file_bytes_loaded
	ldx     _global_file_bytes_loaded+1
	jsr     axulong
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     axulong
	jsr     tosaddeax
	jsr     pusheax
	lda     _global_file_load_limit
	ldx     _global_file_load_limit+1
	jsr     axulong
	jsr     tosugteax
	bne     L02D8
	ldy     #$07
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bcs     L02D8
	ldy     #$05
	lda     (sp),y
	cmp     #$00
	bne     L01BC
	dey
	lda     (sp),y
	cmp     #$0D
L01BC:	bcc     L02D8
	ldy     #$05
	jsr     ldaxysp
	cmp     #$40
	txa
	sbc     #$00
	bcs     L02D8
;
; bank == STRING_STORAGE_EM_SLOT || bank == FILENAME_STORAGE_EM_SLOT || bank == FILENAME_STORAGE_EM_SLOT + 1 || bank == DIRECTORY_RECORD_BANK || bank == DIRECTORY_RECORD_BANK + 1) {
;
	ldy     #$05
	lda     (sp),y
	bne     L02DE
	dey
	lda     (sp),y
	cmp     #$12
	beq     L02D8
	iny
L02DE:	lda     (sp),y
	bne     L02DF
	dey
	lda     (sp),y
	cmp     #$1B
	beq     L02D8
	iny
L02DF:	lda     (sp),y
	bne     L02E0
	dey
	lda     (sp),y
	cmp     #$1C
	beq     L02D8
	iny
L02E0:	lda     (sp),y
	bne     L02E1
	dey
	lda     (sp),y
	cmp     #$1D
	beq     L02D8
	iny
L02E1:	lda     (sp),y
	bne     L01BA
	dey
	lda     (sp),y
	cmp     #$1E
	bne     L01BA
;
; fclose(handle);
;
L02D8:	ldy     #$09
	jsr     ldaxysp
	jsr     _fclose
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_TO_OVERWRITE_FM_RAM));
;
	lda     #$79
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     L019D
;
; memset(buffer + count, 0, 256 - count);
;
L01BA:	ldy     #$03
	jsr     ldaxysp
	clc
	adc     (sp)
	pha
	txa
	ldy     #$01
	adc     (sp),y
	tax
	pla
	jsr     pushax
	lda     #$00
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	lda     #$01
	iny
	sbc     (sp),y
	tax
	pla
	jsr     __bzero
;
; App_EMDataCopy(buffer, em_bank_num, page++, PARAM_COPY_TO_EM);
;
	jsr     pushw0sp
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	jsr     ldaxysp
	sta     regsave
	ina
	bne     L01D1
	inx
L01D1:	ldy     #$09
	jsr     staxysp
	lda     regsave
	jsr     pusha
	lda     #$01
	jsr     _App_EMDataCopy
;
; global_file_bytes_loaded += count;
;
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     _global_file_bytes_loaded
	sta     _global_file_bytes_loaded
	txa
	adc     _global_file_bytes_loaded+1
	sta     _global_file_bytes_loaded+1
;
; while ((count = fread(buffer, 1, 256, handle)) != 0) {
;
L01AF:	jsr     pushw0sp
	lda     #$01
	jsr     pusha0
	tax
	dea
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     _fread
	ldy     #$02
	jsr     staxysp
	cpx     #$00
	jne     L01AD
	cmp     #$00
	jne     L01AD
;
; if (ferror(handle)) { fclose(handle); return false; }
;
	ldy     #$09
	jsr     ldaxysp
	jsr     _ferror
	stx     tmp1
	ora     tmp1
	beq     L01D5
	ldy     #$09
	jsr     ldaxysp
	jsr     _fclose
	ldx     #$00
	txa
	bra     L019D
;
; return fclose(handle) == 0;
;
L01D5:	ldy     #$09
	jsr     ldaxysp
	jsr     _fclose
	cpx     #$00
	bne     L01DD
	cmp     #$00
L01DD:	jsr     booleq
;
; }
;
L019D:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_CheckForFile (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_CheckForFile: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; the_file_handler = fopen(the_file_path, "r");
;
	jsr     decsp2
	ldy     #$06
	jsr     pushwysp
	lda     #<(L01E2)
	ldx     #>(L01E2)
	jsr     _fopen
	jsr     stax0sp
;
; if (the_file_handler == NULL)
;
	cpx     #$00
	bne     L01E4
	cmp     #$00
	bne     L01E4
;
; Buffer_NewMessage(General_GetString(feedback_string_id));
;
	ldy     #$02
	lda     (sp),y
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp5
;
; fclose(the_file_handler);
;
L01E4:	jsr     ldax0sp
	jsr     _fclose
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_Delete (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_Delete: near

.segment	"RODATA"

L0200:
	.word	$0000

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; if (is_directory)
;
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	beq     L01EF
;
; success = Kernel_DeleteFolder(the_file_path);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _Kernel_DeleteFolder
	sta     (sp)
;
; if (!success)
;
	lda     (sp)
	bne     L02E3
;
; success = Kernel_DeleteFile(the_file_path);
;
L01EF:	ldy     #$03
	jsr     ldaxysp
	jsr     _Kernel_DeleteFile
	sta     (sp)
;
; if (success == false)
;
L02E3:	ldx     #$00
	lda     (sp)
;
; goto error;
;
	beq     L01EE
;
; return true;
;
	lda     #$01
	jmp     incsp4
;
; }
;
L01EE:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_Rename (__near__ struct WB2KFileObject *, __near__ const unsigned char *, __near__ const unsigned char *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_Rename: near

.segment	"RODATA"

L0212:
	.word	$0000
L0218:
	.word	$0000

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_file == NULL)
;
	jsr     decsp1
	ldy     #$07
	lda     (sp),y
	iny
	ora     (sp),y
;
; return false;
;
	beq     L0211
;
; if ( (result_code = rename( old_file_path, new_file_path )) < 0)
;
	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	jsr     ldaxysp
	jsr     _rename
	cmp     #$80
	sta     (sp)
	asl     a
	lda     #$00
	tax
;
; goto error;
;
	bcs     L0205
;
; if (File_UpdateFileName(the_file, new_file_name) == false)
;
	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	jsr     ldaxysp
	jsr     _File_UpdateFileName
	cmp     #$00
;
; goto error;
;
	beq     L0211
;
; if (!the_file->is_directory_)
;
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	bne     L0219
;
; the_file->file_type_ = File_GetFileTypeFromExtension(_CBM_T_REG, new_file_name);
;
	jsr     pushwysp
	lda     #$10
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	jsr     _File_GetFileTypeFromExtension
	ldy     #$0E
	jsr     staspidx
;
; return true;
;
L0219:	ldx     #$00
	lda     #$01
	bra     L0205
;
; return false;
;
L0211:	tax
;
; }
;
L0205:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_MarkSelected (__near__ struct WB2KFileObject *, signed char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_MarkSelected: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; if (the_file == NULL)
;
	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L02E9
;
; return false;
;
	tax
	jmp     incsp3
;
; if (the_file->selected_ == false)
;
L02E9:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	ldx     #$00
	lda     (ptr1),y
	bne     L02EA
;
; the_file->selected_ = true;
;
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$0B
	sta     (ptr1),y
;
; File_Render(the_file, the_file->selected_, y_offset, true); // if we're here, panel must be active?
;
	ldy     #$04
	jsr     pushwysp
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _File_Render
;
; return true;
;
	ldx     #$00
L02EA:	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_MarkUnSelected (__near__ struct WB2KFileObject *, signed char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_MarkUnSelected: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; if (the_file == NULL)
;
	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L02EB
;
; return false;
;
	tax
	jmp     incsp3
;
; if (the_file->selected_ == true)
;
L02EB:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	ldx     #$00
	lda     (ptr1),y
	cmp     #$01
	bne     L02EC
;
; the_file->selected_ = false;
;
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0B
	sta     (ptr1),y
;
; File_Render(the_file, the_file->selected_, y_offset, true); // if we're here, panel must be active?
;
	ldy     #$04
	jsr     pushwysp
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _File_Render
;
; return true;
;
	ldx     #$00
L02EC:	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ File_Render (__near__ struct WB2KFileObject *, unsigned char, signed char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_Render: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; if (the_file == NULL)
;
	jsr     decsp6
	ldy     #$09
	lda     (sp),y
	iny
	ora     (sp),y
;
; return;
;
	jeq     L0254
;
; if (as_active)
;
	ldy     #$06
	lda     (sp),y
	beq     L0244
;
; the_color = LIST_ACTIVE_COLOR;
;
	lda     #$0B
;
; else
;
	bra     L02EF
;
; the_color = LIST_INACTIVE_COLOR;
;
L0244:	lda     #$03
L02EF:	ldy     #$01
	sta     (sp),y
;
; x1 = the_file->x_;
;
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0F
	lda     (ptr1),y
	ldy     #$05
	sta     (sp),y
;
; x2 = the_file->x_ + (UI_PANEL_INNER_WIDTH - 1);
;
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0F
	ldx     #$00
	lda     (ptr1),y
	ldy     #$20
	jsr     incaxy
	ldy     #$04
	sta     (sp),y
;
; typex = x1 + UI_PANEL_FILETYPE_OFFSET;
;
	iny
	ldx     #$00
	lda     (sp),y
	ldy     #$17
	jsr     incaxy
	ldy     #$02
	sta     (sp),y
;
; sizex = typex + UI_PANEL_FILESIZE_OFFSET - 1; // "bytes" is 5 in len, but we are using 6 digit size, so start one before bytes.
;
	clc
	adc     #$05
	sec
	sbc     #$01
	iny
	sta     (sp),y
;
; if (the_file->display_row_ != -1)
;
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$11
	jsr     ldaidx
	cmp     #$FF
	jeq     L0254
;
; if (the_file->size_ <= 999999UL)
;
	ldy     #$0A
	jsr     ldaxysp
	jsr     ldeaxi
	cmp     #$40
	txa
	sbc     #$42
	lda     sreg
	sbc     #$0F
	lda     sreg+1
	sbc     #$00
	bcs     L0256
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "%6lu", the_file->size_);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L025B)
	ldx     #>(L025B)
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	jsr     ldeaxi
;
; else if (the_file->size_ / 1024UL <= 99999UL)
;
	bra     L02F1
L0256:	ldy     #$0A
	jsr     ldaxysp
	jsr     ldeaxi
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	stz     sreg+1
	jsr     shreax2
	cmp     #$A0
	txa
	sbc     #$86
	lda     sreg
	sbc     #$01
	lda     sreg+1
	sbc     #$00
	bcs     L025F
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "%5luK", the_file->size_ / 1024UL);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L0264)
	ldx     #>(L0264)
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	jsr     ldeaxi
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	stz     sreg+1
	jsr     shreax2
;
; else
;
	bra     L02F1
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, "%5luM", the_file->size_ / 1048576UL);
;
L025F:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L026B)
	ldx     #>(L026B)
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	jsr     ldeaxi
	ldx     sreg+1
	lda     sreg
	stz     sreg+1
	stz     sreg
	jsr     shreax4
L02F1:	jsr     pusheax
	ldy     #$0A
	jsr     _snprintf
;
; y = the_file->display_row_ + y_offset;
;
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$11
	jsr     ldaidx
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$07
	lda     (sp),y
	bpl     L0270
	dex
L0270:	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	pla
	cmp     #$80
	sta     (sp)
;
; Text_FillBox(x1, y, x2, y, CH_SPACE, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_FillBox
;
; Text_DrawStringAtXY( x1, y, App_GetFilenameFromEM(the_file), the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; Text_DrawStringAtXY( sizex, y, global_string_buff1, the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; Text_DrawStringAtXY( typex, y, File_GetFileTypeString(the_file->file_type_), the_color, APP_BACKGROUND_COLOR);
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jsr     _File_GetFileTypeString
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; if (as_selected == true)
;
	ldy     #$08
	lda     (sp),y
	cmp     #$01
	bne     L0254
;
; Text_SetXY(x1,y);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_Invert(UI_PANEL_INNER_WIDTH);
;
	ldx     #$00
	lda     #$21
	jsr     _Text_Invert
;
; Text_FillBox( 0, UI_FULL_PATH_LINE_Y, 79, UI_FULL_PATH_LINE_Y, CH_SPACE, APP_BACKGROUND_COLOR, APP_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	lda     #$32
	jsr     pusha
	lda     #$4F
	jsr     pusha
	lda     #$32
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _Text_FillBox
;
; Text_DrawStringAtXY( 0, UI_FULL_PATH_LINE_Y, App_GetFilenameFromEM(the_file), COLOR_GREEN, APP_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	lda     #$32
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; }
;
L0254:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_CompareSize (__near__ void *, __near__ void *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_CompareSize: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; WB2KFileObject*  file_1 = (WB2KFileObject*)first_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; WB2KFileObject*  file_2 = (WB2KFileObject*)second_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; if (file_1->size_ > file_2->size_)
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     tosugteax
	beq     L02B1
;
; return true;
;
	ldx     #$00
	lda     #$01
	jmp     incsp8
;
; return false;
;
L02B1:	ldx     #$00
	txa
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_CompareName (__near__ void *, __near__ void *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_CompareName: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; WB2KFileObject*  file_1 = (WB2KFileObject*)first_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; WB2KFileObject*  file_2 = (WB2KFileObject*)second_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; App_GetFilenameFromEM(file_2); // puts file2 filename into global_retrieved_em_filename
;
	jsr     ldax0sp
	jsr     _App_GetFilenameFromEM
;
; memcpy(file_compare_filename, global_retrieved_em_filename, FILE_MAX_FILENAME_SIZE); // copy from 1 to 2 so we can overwrite global_retrieved_em_filename
;
	lda     _file_compare_filename
	ldx     _file_compare_filename+1
	jsr     pushax
	lda     _global_retrieved_em_filename
	ldx     _global_retrieved_em_filename+1
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _memcpy
;
; App_GetFilenameFromEM(file_1); // puts file1 filename into global_retrieved_em_filename
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
;
; if (General_Strncasecmp(global_retrieved_em_filename, file_compare_filename, FILE_MAX_FILENAME_SIZE) > 0)
;
	lda     _global_retrieved_em_filename
	ldx     _global_retrieved_em_filename+1
	jsr     pushax
	lda     _file_compare_filename
	ldx     _file_compare_filename+1
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _General_Strncasecmp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L02D0
	eor     #$80
L02D0:	asl     a
	lda     #$00
	tax
	bcc     L02D2
;
; return true;
;
	ina
	jmp     incsp8
;
; }
;
L02D2:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_CompareFileTypeID (__near__ void *, __near__ void *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_CompareFileTypeID: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; WB2KFileObject*  file_1 = (WB2KFileObject*)first_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; WB2KFileObject*  file_2 = (WB2KFileObject*)second_payload;
;
	ldy     #$05
	jsr     pushwysp
;
; if (file_1->file_type_ > file_2->file_type_)
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jsr     tosicmp0
	bcc     L02B9
	beq     L02B9
;
; return true;
;
	ldx     #$00
	lda     #$01
	jmp     incsp8
;
; return false;
;
L02B9:	ldx     #$00
	txa
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ File_GetFileTypeFromExtension (unsigned char, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_GetFileTypeFromExtension: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; General_ExtractFileExtensionFromFilename(the_file_name, (char*)&temp_file_extension_buffer);
;
	jsr     pushw0sp
	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     _General_ExtractFileExtensionFromFilename
;
; if (General_Strncasecmp((char*)&temp_file_extension_buffer, "pgZ", FILE_MAX_EXTENSION_SIZE) == 0 ||
;
	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L002C)
	ldx     #>(L002C)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L02F3
	cmp     #$00
	beq     L02F5
;
; General_Strncasecmp((char*)&temp_file_extension_buffer, "pgX", FILE_MAX_EXTENSION_SIZE) == 0)
;
L02F3:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0031)
	ldx     #>(L0031)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0029
	cmp     #$00
	bne     L0029
;
; return FNX_FILETYPE_EXE;
;
L02F5:	lda     #$C9
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "bas", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0029:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L003B)
	ldx     #>(L003B)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0038
	cmp     #$00
	bne     L0038
;
; return FNX_FILETYPE_BASIC;
;
	lda     #$CA
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "txt", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0038:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0044)
	ldx     #>(L0044)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0041
	cmp     #$00
	bne     L0041
;
; return FNX_FILETYPE_TEXT;
;
	lda     #$CD
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "mod", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0041:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L004D)
	ldx     #>(L004D)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L004A
	cmp     #$00
	bne     L004A
;
; return FNX_FILETYPE_MUSIC;
;
	lda     #$CB
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "mid", FILE_MAX_EXTENSION_SIZE) == 0)
;
L004A:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0056)
	ldx     #>(L0056)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0053
	cmp     #$00
	bne     L0053
;
; return FNX_FILETYPE_MIDI;
;
	lda     #$CE
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "vgm", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0053:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L005F)
	ldx     #>(L005F)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L005C
	cmp     #$00
	bne     L005C
;
; return FNX_FILETYPE_VGM;
;
	lda     #$D2
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "rsd", FILE_MAX_EXTENSION_SIZE) == 0)
;
L005C:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0068)
	ldx     #>(L0068)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0065
	cmp     #$00
	bne     L0065
;
; return FNX_FILETYPE_RSD;
;
	lda     #$D3
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "mp3", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0065:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0071)
	ldx     #>(L0071)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L006E
	cmp     #$00
	bne     L006E
;
; return FNX_FILETYPE_MP3;
;
	lda     #$CF
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "ogg", FILE_MAX_EXTENSION_SIZE) == 0)
;
L006E:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L007A)
	ldx     #>(L007A)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0077
	cmp     #$00
	bne     L0077
;
; return FNX_FILETYPE_OGG;
;
	lda     #$D0
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "wav", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0077:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0083)
	ldx     #>(L0083)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0080
	cmp     #$00
	bne     L0080
;
; return FNX_FILETYPE_WAV;
;
	lda     #$D1
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "pgx", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0080:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L008C)
	ldx     #>(L008C)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0089
	cmp     #$00
	bne     L0089
;
; return FNX_FILETYPE_EXE;
;
	lda     #$C9
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "fnt", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0089:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L0095)
	ldx     #>(L0095)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0092
	cmp     #$00
	bne     L0092
;
; return FNX_FILETYPE_FONT;
;
	lda     #$C8
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "kup", FILE_MAX_EXTENSION_SIZE) == 0)
;
L0092:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L009E)
	ldx     #>(L009E)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L009B
	cmp     #$00
	bne     L009B
;
; return FNX_FILETYPE_EXE;
;
	lda     #$C9
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "lbm", FILE_MAX_EXTENSION_SIZE) == 0)
;
L009B:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L00A7)
	ldx     #>(L00A7)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L00A4
	cmp     #$00
	bne     L00A4
;
; return FNX_FILETYPE_IMAGE;
;
	lda     #$CC
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "256", FILE_MAX_EXTENSION_SIZE) == 0)
;
L00A4:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L00B0)
	ldx     #>(L00B0)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L00AD
	cmp     #$00
	bne     L00AD
;
; return FNX_FILETYPE_IMAGE;
;
	lda     #$CC
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "src", FILE_MAX_EXTENSION_SIZE) == 0)
;
L00AD:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L00B9)
	ldx     #>(L00B9)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L00B6
	cmp     #$00
	bne     L00B6
;
; return FNX_FILETYPE_TEXT;
;
	lda     #$CD
	jmp     incsp3
;
; else if (General_Strncasecmp((char*)&temp_file_extension_buffer, "url", FILE_MAX_EXTENSION_SIZE) == 0)
;
L00B6:	lda     #<(_temp_file_extension_buffer)
	ldx     #>(_temp_file_extension_buffer)
	jsr     pushax
	lda     #<(L00C2)
	ldx     #>(L00C2)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L00BF
	cmp     #$00
	bne     L00BF
;
; return _CBM_T_DIR;
;
	lda     #$02
	jmp     incsp3
;
; return default_file_type;
;
L00BF:	ldy     #$02
	ldx     #$00
	lda     (sp),y
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ File_GetFileTypeString (unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_File_GetFileTypeString: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; switch (cbm_filetype_id)
;
	lda     (sp)
;
; }
;
	cmp     #$01
	beq     L00CD
	cmp     #$02
	beq     L00D1
	cmp     #$03
	beq     L00D5
	cmp     #$05
	beq     L00D9
	cmp     #$C8
	beq     L00E1
	cmp     #$C9
	beq     L00E5
	cmp     #$CA
	beq     L00DD
	cmp     #$CB
	beq     L00ED
	cmp     #$CC
	beq     L00E9
	cmp     #$CD
	beq     L00FD
	cmp     #$CE
	beq     L0101
	cmp     #$CF
	beq     L00F1
	cmp     #$D0
	beq     L00F5
	cmp     #$D1
	beq     L00F9
	cmp     #$D2
	beq     L0105
	cmp     #$D3
	beq     L0109
	bra     L010C
;
; return General_GetString(ID_STR_FILETYPE_SUBDIR);
;
L00CD:	lda     #$5F
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_DIR);
;
L00D1:	lda     #$5D
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_LINK);
;
L00D5:	lda     #$5E
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_HEADER);
;
L00D9:	lda     #$5C
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_BASIC);
;
L00DD:	lda     #$61
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_FONT);
;
L00E1:	lda     #$63
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_EXE);
;
L00E5:	lda     #$62
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_IMAGE);
;
L00E9:	lda     #$65
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_MUSIC);
;
L00ED:	lda     #$64
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_MP3);
;
L00F1:	lda     #$68
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_OGG);
;
L00F5:	lda     #$69
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_WAV);
;
L00F9:	lda     #$6A
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_TEXT);
;
L00FD:	lda     #$66
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_MIDI);
;
L0101:	lda     #$67
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_VGM);
;
L0105:	lda     #$6B
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_RSD);
;
L0109:	lda     #$6C
	bra     L02F6
;
; return General_GetString(ID_STR_FILETYPE_OTHER);
;
L010C:	lda     #$60
L02F6:	jsr     _General_GetString
;
; }
;
	jmp     incsp1

.endproc
