; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_Directory_Select
	.import		_Directory_SelectFolder
	.import		_File_New
	.import		_File_Destroy
	.import		_File_MarkSelected
	.import		_File_MarkUnSelected
	.import		_calloc
	.import		_free
	.import		_App_ShowProgressBar
	.import		_App_HideProgressBar
	.import		_App_UpdateProgressBar
	.import		_App_Exit
	.import		_App_GetFilenameFromEM
	.import		_Buffer_NewMessage
	.import		_General_GetString
	.import		_General_StrlcpyWithAlloc
	.import		_General_Strlcpy
	.import		_General_Strncasecmp
	.import		_General_CreateFilePathFromFolderAndFile
	.import		_List_NewItem
	.import		_List_Destroy
	.import		_List_AddItem
	.import		_fclose
	.import		_ferror
	.import		_fopen
	.import		_fread
	.import		_fwrite
	.import		_snprintf
	.import		_sprintf
	.export		_Folder_NewOrReset
	.export		_Folder_Destroy

	.export		_Folder_SetCurrentRow
	.export		_Folder_GetCountFiles
	.export		_Folder_GetCurrentRow
	.export		_Folder_GetCurrentFile
	.export		_Folder_GetCurrentFileType
	.export		_Folder_FindFileByRow
	.export		_Folder_AddNewFile
	.export		_Folder_CopyFile
	.export		_Folder_CopyCurrentFile
	.export		_Folder_PopulateFiles
	.export		_Folder_SetFileSelectionByRow
	.export		_Folder_GetTargetHandleForWriting
	.import		_strcmp
	.import		_strlen
	.import		_Kernel_OpenDir
	.import		_Kernel_ReadDir
	.import		_Kernel_CloseDir
	.import		_global_temp_path_1
	.import		_global_temp_path_2
	.import		_global_string_buff1
	.export		_Folder_CopyFileBytes

.segment	"DATA"

.segment	"OVERLAY_DISKSYS"
_folder_temp_filename_buffer:
	.byte	$00
	.res	31,$00
_folder_temp_filename:
	.addr	_folder_temp_filename_buffer
.segment	"DATA"

.segment	"RODATA"

L0312:
	.byte	$53,$6B,$69,$70,$70,$65,$64,$20,$6E,$61,$6D,$65,$73,$20,$6C,$6F
	.byte	$6E,$67,$65,$72,$20,$74,$68,$61,$6E,$20,$33,$31,$20,$63,$68,$61
	.byte	$72,$61,$63,$74,$65,$72,$73,$2E,$00
L0268:
	.byte	$49,$6E,$74,$65,$72,$6E,$61,$6C,$20,$6D,$69,$63,$72,$6F,$20,$53
	.byte	$44,$00
L0265:
	.byte	$45,$78,$74,$65,$72,$6E,$61,$6C,$20,$53,$44,$00
L01D8:
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$00
L01CC:
	.byte	$5B,$50,$41,$54,$48,$5D,$00
L01B6:
	.byte	$5B,$55,$52,$4C,$5D,$00
L0368:
	.byte	$7E,$25,$30,$32,$75,$00
L0031:
	.byte	$72,$62,$00
L0374	:=	L0031+0
L03C6:
	.byte	$77,$62,$00
L01F9:
	.byte	$2E,$2E,$00
L02F2:
	.byte	$5E,$00

; ---------------------------------------------------------------
; __near__ struct WB2KFolderObject * __near__ Folder_NewOrReset (__near__ struct WB2KFolderObject *, unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_NewOrReset: near

.segment	"RODATA"

L0092:
	.word	$0000
L00AD:
	.word	$0000
L00BE:
	.word	$0000

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_existing_folder == NULL)
;
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L03C8
;
; if ( (the_folder = (WB2KFolderObject*)calloc(1, sizeof(WB2KFolderObject)) ) == NULL)
;
	ina
	jsr     pusha0
	lda     #$0D
	jsr     _calloc
	jsr     stax0sp
	cpx     #$00
	bne     L0093
	cmp     #$00
	bne     L0093
;
; goto error;
;
	jmp     L0091
;
; the_folder = the_existing_folder;
;
L03C8:	jsr     ldaxysp
	jsr     stax0sp
;
; Folder_DestroyAllFiles(the_folder);
;
	jsr     _Folder_DestroyAllFiles
;
; free((the_folder)->list_);
;
	jsr     ldax0sp
	jsr     ldaxi
	jsr     _free
;
; (the_folder)->list_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; free(the_folder->file_name_);
;
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
;
; the_folder->file_name_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; free(the_folder->file_path_);
;
	jsr     ldax0sp
	ldy     #$05
	jsr     ldaxidx
	jsr     _free
;
; the_folder->file_path_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if ( (the_folder->list_ = (WB2KList**)calloc(1, sizeof(WB2KList*)) ) == NULL)
;
L0093:	jsr     pushw0sp
	lda     #$01
	jsr     pusha0
	ina
	jsr     _calloc
	ldy     #$00
	jsr     staxspidx
	cpx     #$00
	bne     L03C9
	cmp     #$00
;
; goto error;
;
	beq     L0091
;
; the_folder->cur_row_ = 0;
;
L03C9:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$08
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_folder->file_count_ = 0;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$06
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_folder->device_number_ = the_device_number;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (sp),y
	ldy     #$0B
	sta     (ptr1),y
;
; the_folder->is_meatloaf_ = false;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
;
; if ( (the_folder->file_path_ = General_StrlcpyWithAlloc(new_path, FILE_MAX_PATHNAME_SIZE)) == NULL)
;
	jsr     pushw0sp
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_StrlcpyWithAlloc
	ldy     #$04
	jsr     staxspidx
	cpx     #$00
	bne     L03CA
	cmp     #$00
;
; goto error;
;
	beq     L0091
;
; return the_folder;
;
L03CA:	jsr     ldax0sp
	jmp     incsp7
;
; if (the_folder) Folder_Destroy(&the_folder);
;
L0091:	ldy     #$01
	lda     (sp),y
	ora     (sp)
	beq     L03CC
	lda     sp
	ldx     sp+1
	jsr     _Folder_Destroy
;
; return NULL;
;
	ldx     #$00
	txa
;
; }
;
L03CC:	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ Folder_Destroy (__near__ __near__ struct WB2KFolderObject * *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_Destroy: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (*the_folder == NULL)
;
	jsr     ldax0sp
	jsr     ldaxi
	cpx     #$00
	bne     L00C7
	cmp     #$00
	bne     L00C7
;
; App_Exit(ERROR_FOLDER_TO_DESTROY_WAS_NULL); // crash early, crash often
;
	lda     #$72
	jsr     _App_Exit
;
; if ((*the_folder)->file_path_ != NULL)
;
L00C7:	jsr     ldax0sp
	jsr     ldaxi
	ldy     #$05
	jsr     ldaxidx
	cpx     #$00
	bne     L03CD
	cmp     #$00
	beq     L00CC
;
; free((*the_folder)->file_path_);
;
L03CD:	jsr     ldax0sp
	jsr     ldaxi
	ldy     #$05
	jsr     ldaxidx
	jsr     _free
;
; (*the_folder)->file_path_ = NULL;
;
	jsr     ldax0sp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if ((*the_folder)->file_name_ != NULL)
;
L00CC:	jsr     ldax0sp
	jsr     ldaxi
	ldy     #$03
	jsr     ldaxidx
	cpx     #$00
	bne     L03CE
	cmp     #$00
	beq     L00D6
;
; free((*the_folder)->file_name_);
;
L03CE:	jsr     ldax0sp
	jsr     ldaxi
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
;
; (*the_folder)->file_name_ = NULL;
;
	jsr     ldax0sp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; Folder_DestroyAllFiles(*the_folder);
;
L00D6:	jsr     ldax0sp
	jsr     ldaxi
	jsr     _Folder_DestroyAllFiles
;
; free((*the_folder)->list_);
;
	jsr     ldax0sp
	jsr     ldaxi
	jsr     ldaxi
	jsr     _free
;
; (*the_folder)->list_ = NULL;
;
	jsr     ldax0sp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; free(*the_folder);
;
	jsr     ldax0sp
	jsr     ldaxi
	jsr     _free
;
; *the_folder = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Folder_DestroyAllFiles (__near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"



; ---------------------------------------------------------------
; void __near__ Folder_SetCurrentRow (__near__ struct WB2KFolderObject *, int)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_SetCurrentRow: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_folder == NULL)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L03D3
;
; App_Exit(ERROR_SET_CURR_ROW_FOLDER_WAS_NULL); // crash early, crash often
;
	lda     #$73
	jsr     _App_Exit
;
; if (the_folder->file_count_ < (the_row_number+1))
;
	ldy     #$03
L03D3:	jsr     ldaxysp
	ldy     #$07
	jsr     pushwidx
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0117
	inx
L0117:	jsr     tosicmp
	bcs     L0114
;
; the_folder->cur_row_ = -1;
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$08
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; else
;
	jmp     incsp4
;
; the_folder->cur_row_ = the_row_number;
;
L0114:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$08
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ Folder_GetCountFiles (__near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_GetCountFiles: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_folder == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L03D4
;
; App_Exit(ERROR_DEFINE_ME); // crash early, crash often
;
	dea
	jsr     _App_Exit
;
; Directory_SelectFolder(the_folder);
;
L03D4:	jsr     ldax0sp
	jsr     _Directory_SelectFolder
;
; return the_folder->file_count_;
;
	jsr     ldax0sp
	ldy     #$07
	jsr     ldaxidx
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ Folder_GetCurrentRow (__near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_GetCurrentRow: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_folder == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L03D5
;
; App_Exit(ERROR_GET_CURR_ROW_FOLDER_WAS_NULL); // crash early, crash often
;
	lda     #$74
	jsr     _App_Exit
;
; return the_folder->cur_row_;
;
L03D5:	jsr     ldax0sp
	ldy     #$09
	jsr     ldaxidx
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; __near__ struct WB2KFileObject * __near__ Folder_GetCurrentFile (__near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_GetCurrentFile: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_folder->cur_row_ < 0)
;
	jsr     ldax0sp
	ldy     #$09
	jsr     ldaxidx
	cpx     #$80
	bcc     L012E
;
; return NULL;
;
	ldx     #$00
	txa
	jmp     incsp2
;
; return Folder_FindFileByRow(the_folder, the_folder->cur_row_);
;
L012E:	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     _Folder_FindFileByRow
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Folder_GetCurrentFileType (__near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_GetCurrentFileType: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; the_file =  Folder_GetCurrentFile(the_folder);
;
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     _Folder_GetCurrentFile
	jsr     stax0sp
;
; if (the_file == NULL)
;
	cpx     #$00
	bne     L0138
	cmp     #$00
;
; return 0;
;
	jeq     incsp4
;
; return the_file->file_type_;
;
L0138:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	ldx     #$00
	lda     (ptr1),y
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; __near__ struct WB2KFileObject * __near__ Folder_FindFileByRow (__near__ struct WB2KFolderObject *, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_FindFileByRow: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; if (the_folder == NULL)
;
	jsr     decsp2
	ldy     #$03
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L03D8
;
; return NULL;
;
	tax
	jmp     incsp5
;
; Directory_SelectFolder(the_folder);
;
L03D8:	jsr     ldaxysp
	jsr     _Directory_SelectFolder
;
; the_item = *(the_folder->list_);
;
	ldy     #$04
	jsr     ldaxysp
	jsr     ldaxi
	jsr     ldaxi
	jsr     stax0sp
;
; while (the_item != NULL)
;
	bra     L0149
;
; WB2KFileObject*  this_file = (WB2KFileObject*)(the_item->payload_);
;
L03D9:	jsr     ldaxysp
	ldy     #$05
	jsr     pushwidx
;
; if ( this_file->row_ == the_row)
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$10
	lda     (ptr1),y
	ldy     #$04
	cmp     (sp),y
	bne     L014E
;
; return this_file;
;
	jsr     ldax0sp
	jsr     incsp2
	jmp     incsp5
;
; the_item = the_item->next_item_;
;
L014E:	dey
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$02
	jsr     staxysp
;
; }
;
	jsr     incsp2
;
; while (the_item != NULL)
;
L0149:	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L03D9
;
; return NULL;
;
	tax
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Folder_AddNewFile (__near__ struct WB2KFolderObject *, __near__ struct WB2KFileObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_AddNewFile: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (the_folder == NULL)
;
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0382
;
; App_Exit(ERROR_DEFINE_ME); // crash early, crash often
;
	dea
	jsr     _App_Exit
;
; the_new_item = List_NewItem((void *)the_file);
;
L0382:	ldy     #$03
	jsr     ldaxysp
	jsr     _List_NewItem
	jsr     stax0sp
;
; if (the_new_item == NULL) return false;
;
	cpx     #$00
	bne     L038A
	cmp     #$00
	jeq     incsp6
;
; List_AddItem(the_folder->list_, the_new_item);
;
L038A:	ldy     #$05
	jsr     ldaxysp
	jsr     pushw
	ldy     #$03
	jsr     ldaxysp
	jsr     _List_AddItem
;
; the_folder->file_count_++;
;
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxidx
	ina
	bne     L0392
	inx
L0392:	ldy     #$06
	jsr     staxspidx
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Folder_CopyFile (__near__ struct WB2KFolderObject *, __near__ struct WB2KFileObject *, __near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_CopyFile: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; if (!the_folder || !the_file || !the_target_folder || the_file->is_directory_) return false;
;
	jsr     decsp3
	ldy     #$08
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L03DB
	dey
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L03DB
	dey
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L03DB
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0345
L03DB:	ldx     #$00
	txa
	jmp     L0344
;
; General_Strlcpy(folder_temp_filename, App_GetFilenameFromEM(the_file), FILE_MAX_FILENAME_SIZE);
;
L0345:	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_Strlcpy
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_folder->file_path_, folder_temp_filename)) return false;
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$05
	jsr     pushwidx
	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     L0344
;
; for (tries = 0; tries < 100; ++tries) {
;
	lda     #$00
	ldy     #$02
L03DA:	sta     (sp),y
	cmp     #$64
	jcs     L03DD
;
; if (tries) {
;
	lda     (sp),y
	beq     L035D
;
; General_Strlcpy(folder_temp_filename, App_GetFilenameFromEM(the_file), FILE_MAX_FILENAME_SIZE - 3);
;
	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$1D
	jsr     _General_Strlcpy
;
; sprintf(folder_temp_filename + strlen(folder_temp_filename), "~%02u", tries);
;
	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     pushax
	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     _strlen
	jsr     tosaddax
	jsr     pushax
	lda     #<(L0368)
	ldx     #>(L0368)
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_2, the_target_folder->file_path_, folder_temp_filename)) return false;
;
L035D:	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	ldy     #$06
	jsr     ldaxysp
	ldy     #$05
	jsr     pushwidx
	lda     _folder_temp_filename
	ldx     _folder_temp_filename+1
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	beq     L0344
;
; existing = fopen(global_temp_path_2, "rb");
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #<(L0374)
	ldx     #>(L0374)
	jsr     _fopen
	jsr     stax0sp
;
; if (!existing) break;
;
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	beq     L0356
;
; fclose(existing);
;
	jsr     ldax0sp
	jsr     _fclose
;
; for (tries = 0; tries < 100; ++tries) {
;
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L03DA
;
; if (tries == 100) return false;
;
L0356:	iny
L03DD:	lda     (sp),y
	cmp     #$64
	bne     L037A
	ldx     #$00
	txa
	bra     L0344
;
; return Folder_CopyFileBytes(global_temp_path_1, global_temp_path_2, the_file->size_) >= 0;
;
L037A:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     _Folder_CopyFileBytes
	lda     sreg+1
	jsr     boolge
;
; }
;
L0344:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Folder_CopyCurrentFile (__near__ struct WB2KFolderObject *, __near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_CopyCurrentFile: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; the_file = Folder_GetCurrentFile(the_folder);
;
	jsr     decsp2
	ldy     #$05
	jsr     ldaxysp
	jsr     _Folder_GetCurrentFile
	jsr     stax0sp
;
; if (the_file == NULL)
;
	cpx     #$00
	bne     L033C
	cmp     #$00
;
; return false;
;
	jeq     incsp6
;
; return Folder_CopyFile(the_folder, the_file, the_target_folder);
;
L033C:	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	jsr     pushwysp
	ldy     #$07
	jsr     ldaxysp
	jsr     _Folder_CopyFile
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Folder_PopulateFiles (unsigned char, __near__ struct WB2KFolderObject *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_PopulateFiles: near

.segment	"RODATA"

L015B:
	.byte	$00
	.res	5,$00
L0204:
	.word	$0000
L020E:
	.word	$0000
L024B:
	.word	$0000
L02BF:
	.word	$0000
L02DB:
	.word	$0000
L02FC:
	.word	$0000
L0305:
	.word	$0000

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; bool    stop_processing = false;
;
	jsr     decsp2
	lda     #$00
	jsr     pusha
;
; bool skipped_long_name = false;
;
	jsr     pusha
;
; uint8_t    meatloaf_info_file_cnt = 0; // if in meatloaf mode, treat first 4 files as info-only files. convert last one to '..'
;
	jsr     pusha
;
; uint8_t    meatloaf_slash_cnt = 0;   // used to parse the INFO file row and tell if we're on root or not.
;
	jsr     pusha
;
; uint8_t    the_error_code = ERROR_NO_ERROR;
;
	ldy     #$0C
	jsr     subysp
	lda     #$00
	jsr     pusha
;
; uint16_t   file_cnt = 0;
;
	jsr     push0
;
; DateTime   this_datetime = {0};
;
	ldy     #$0A
	jsr     subysp
	ldy     #$05
L015D:	lda     L015B,y
	sta     (sp),y
	dey
	bpl     L015D
;
; the_folder->panel_id_ = the_panel_id;
;
	jsr     decsp2
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$23
	lda     (sp),y
	ldy     #$0C
	sta     (ptr1),y
;
; Directory_Select(the_panel_id);
;
	ldy     #$23
	lda     (sp),y
	jsr     _Directory_Select
;
; max_file_cnt = 255;
;
	ldx     #$00
	lda     #$FF
	ldy     #$0A
	jsr     staxysp
;
; if (max_file_cnt > 255) max_file_cnt = 255;
;
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0164
	lda     #$FF
	ldy     #$0A
	jsr     staxysp
;
; if (the_folder == NULL)
;
L0164:	ldy     #$21
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L03E3
;
; App_Exit(ERROR_POPULATE_FILES_FOLDER_WAS_NULL); // crash early, crash often
;
	lda     #$7B
	jsr     _App_Exit
;
; if (the_folder->file_path_ == NULL)
;
	ldy     #$22
L03E3:	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	cpx     #$00
	bne     L016D
	cmp     #$00
	bne     L016D
;
; App_Exit(ERROR_FOLDER_WAS_NULL); // crash early, crash often
;
	lda     #$69
	jsr     _App_Exit
;
; General_Strlcpy(global_temp_path_1, the_folder->file_path_, FILE_MAX_PATHNAME_SIZE);
;
L016D:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$24
	jsr     ldaxysp
	ldy     #$05
	jsr     pushwidx
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; the_folder->file_count_ = 0;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$06
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if (the_folder->device_number_ <= DEVICE_INTERNAL_SD)
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	ldx     #$00
	lda     (ptr1),y
	cmp     #$02
	bcs     L03E4
;
; the_block_size = FILE_BYTES_PER_BLOCK;
;
	inx
	lda     #$00
;
; else
;
	bra     L0411
;
; the_block_size = FILE_BYTES_PER_BLOCK_IEC;
;
L03E4:	lda     #$FE
L0411:	jsr     stax0sp
;
; free(the_folder->file_name_);
;
	ldy     #$22
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
;
; the_folder->file_name_ = NULL;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_folder->is_meatloaf_ = false;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
;
; dir = Kernel_OpenDir(the_folder->file_path_);
;
	ldy     #$22
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	jsr     _Kernel_OpenDir
	ldy     #$11
	jsr     staxysp
;
; if (! dir) {
;
	ldy     #$12
	lda     (sp),y
	dey
	ora     (sp),y
	jne     L02E2
;
; return ERROR_COULD_NOT_OPEN_DIR;
;
	tax
	lda     #$6B
	jmp     L0154
;
; skip_this_file = false;
;
L03E5:	ldy     #$20
	sta     (sp),y
;
; if (strlen(dirent->d_name) >= FILE_MAX_FILENAME_SIZE && !_DE_ISLBL(dirent->d_type) && !the_folder->is_meatloaf_) {
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	jsr     _strlen
	cmp     #$20
	txa
	sbc     #$00
	lda     #$00
	bcc     L03E9
	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L019E
	cmp     #$02
L019E:	jsr     booleq
	tax
	bne     L019C
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0199
L019C:	lda     #$00
	bra     L03E9
;
; skipped_long_name = true;
;
L0199:	ina
	ldy     #$1D
	sta     (sp),y
;
; continue;
;
	jmp     L02E2
;
; meatloaf_slash_cnt = 0;
;
L03E9:	ldy     #$1B
	sta     (sp),y
;
; if (the_folder->is_meatloaf_ == true && meatloaf_info_file_cnt < 5)
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	cmp     #$01
	jne     L0215
	ldy     #$1C
	lda     (sp),y
	cmp     #$05
	jcs     L0215
;
; if (_DE_ISREG(dirent->d_type) == true || _DE_ISDIR(dirent->d_type)  == true) // remember, microkernel doesn't check, it just assumes dir if block size is 0.
;
	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L01AB
	cmp     #$00
L01AB:	jsr     booleq
	cmp     #$01
	beq     L03ED
	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L01AE
	cmp     #$01
L01AE:	jsr     booleq
	cmp     #$01
	jne     L0215
;
; if (meatloaf_info_file_cnt == 0)
;
L03ED:	ldy     #$1C
	lda     (sp),y
	bne     L03EF
;
; if (General_Strncasecmp((char*)dirent->d_name, "[URL]", 5) == 0)
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	jsr     pushax
	lda     #<(L01B6)
	ldx     #>(L01B6)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _General_Strncasecmp
	cpx     #$00
	jne     L0215
	cmp     #$00
	jne     L0215
;
; meatloaf_info_file_cnt = 1;
;
	ina
	ldy     #$1C
	sta     (sp),y
;
; else
;
	jmp     L0412
;
; else if (meatloaf_info_file_cnt == 1)
;
L03EF:	lda     (sp),y
	cmp     #$01
	bne     L03F1
;
; else if (meatloaf_info_file_cnt == 2)
;
	jmp     L0425
L03F1:	lda     (sp),y
	cmp     #$02
	bne     L03F3
;
; if (General_Strncasecmp((char*)dirent->d_name, "[PATH]", 6) == 0)
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	jsr     pushax
	lda     #<(L01CC)
	ldx     #>(L01CC)
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L01C9
	cmp     #$00
	bne     L01C9
;
; meatloaf_info_file_cnt = 3;
;
	lda     #$03
	ldy     #$1C
;
; else if (General_Strncasecmp((char*)dirent->d_name, "------", 6) == 0)
;
	jmp     L0418
L01C9:	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	jsr     pushax
	lda     #<(L01D8)
	ldx     #>(L01D8)
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     _General_Strncasecmp
	cpx     #$00
	jne     L0215
	cmp     #$00
	jne     L0215
;
; meatloaf_info_file_cnt = 5;
;
	lda     #$05
	ldy     #$1C
;
; else if (meatloaf_info_file_cnt == 3)
;
	jmp     L0418
L03F3:	lda     (sp),y
	cmp     #$03
	jne     L03F8
;
; this_file_name = dirent->d_name;
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$13
	jsr     staxysp
;
; filename_len = strlen(this_file_name);
;
	jsr     _strlen
	ldy     #$19
	sta     (sp),y
;
; for (i = 0; i < filename_len; i++)
;
	lda     #$00
	iny
L0419:	sta     (sp),y
	dey
	cmp     (sp),y
	bcs     L01E9
;
; if (this_file_name[i] == '/')
;
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$1A
	lda     (sp),y
	tay
	lda     (ptr1),y
	cmp     #$2F
	bne     L01EA
;
; meatloaf_slash_cnt++;
;
	ldy     #$1B
	lda     (sp),y
	ina
	sta     (sp),y
;
; for (i = 0; i < filename_len; i++)
;
L01EA:	ldy     #$1A
	lda     (sp),y
	ina
	bra     L0419
;
; if (meatloaf_slash_cnt > 1)
;
L01E9:	ldy     #$1B
	lda     (sp),y
	cmp     #$02
	bcc     L03F6
;
; this_file = File_New(the_panel_id, "..", PARAM_FILE_IS_FOLDER, 0, _CBM_T_DIR, file_cnt, &this_datetime);
;
	ldy     #$23
	lda     (sp),y
	jsr     pusha
	lda     #<(L01F9)
	ldx     #>(L01F9)
	jsr     pushax
	lda     #$01
	jsr     pusha
	jsr     pushl0
	lda     #$02
	jsr     pusha
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _File_New
	ldy     #$08
	jsr     staxysp
;
; if (this_file == NULL)
;
	cpx     #$00
	bne     L040E
	cmp     #$00
;
; goto error;
;
	jeq     L0415
;
; file_added = Folder_AddNewFile(the_folder, this_file);
;
L040E:	ldy     #$24
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Folder_AddNewFile
	ldy     #$1F
	sta     (sp),y
;
; if (!file_added) { File_Destroy(&this_file); goto error; }
;
	lda     (sp),y
	bne     L020A
	lda     #$08
	jsr     leaa0sp
	jsr     _File_Destroy
	jmp     L0203
;
; ++file_cnt;
;
L020A:	ldy     #$0C
	ldx     #$00
	lda     #$01
	jsr     addeqysp
;
; meatloaf_info_file_cnt = 4;
;
L03F6:	lda     #$04
	ldy     #$1C
;
; else if (meatloaf_info_file_cnt == 4)
;
	bra     L0418
L03F8:	lda     (sp),y
	cmp     #$04
	bne     L0215
;
; meatloaf_info_file_cnt = 5;
;
L0425:	ina
L0418:	sta     (sp),y
;
; skip_this_file = true;
;
	lda     #$01
L0412:	ldy     #$20
	sta     (sp),y
;
; if (!skip_this_file && !_DE_ISLBL(dirent->d_type) && strlen(dirent->d_name) >= FILE_MAX_FILENAME_SIZE) {
;
L0215:	ldy     #$20
	lda     (sp),y
	bne     L0414
	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L021F
	cmp     #$02
L021F:	jsr     booleq
	tax
	bne     L021B
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	jsr     _strlen
	cmp     #$20
	txa
	sbc     #$00
	bcc     L021B
;
; skipped_long_name = true;
;
	lda     #$01
	ldy     #$1D
	sta     (sp),y
;
; continue;
;
	jmp     L02E2
;
; if (skip_this_file == false)
;
L021B:	ldy     #$20
L0414:	lda     (sp),y
	jne     L02D1
;
; if (_DE_ISDIR(dirent->d_type))
;
	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	jne     L0227
	cmp     #$01
	jne     L0227
;
; this_file_name = dirent->d_name;
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$13
	jsr     staxysp
;
; if (this_file_name[0] == '.' && this_file_name[1] != '.')
;
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$2E
	bne     L022D
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$2E
	jne     L02D1
;
; this_file = File_New(the_panel_id, this_file_name, PARAM_FILE_IS_FOLDER, 0, _CBM_T_DIR, file_cnt, &this_datetime);
;
L022D:	ldy     #$23
	lda     (sp),y
	jsr     pusha
	ldy     #$17
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	jsr     pushl0
	lda     #$02
	jsr     pusha
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _File_New
	ldy     #$08
	jsr     staxysp
;
; if (this_file == NULL)
;
	cpx     #$00
	bne     L023D
	cmp     #$00
	bne     L023D
;
; stop_processing = true;
;
	ina
	ldy     #$1E
	sta     (sp),y
;
; else
;
	jmp     L02D1
;
; file_added = Folder_AddNewFile(the_folder, this_file);
;
L023D:	ldy     #$24
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Folder_AddNewFile
	ldy     #$1F
	sta     (sp),y
;
; if (!file_added) { File_Destroy(&this_file); goto error; }
;
	lda     (sp),y
	jne     L02D7
	lda     #$08
	jsr     leaa0sp
	jsr     _File_Destroy
	jmp     L0203
;
; else if (_DE_ISLBL(dirent->d_type))
;
L0227:	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	jne     L0253
	cmp     #$02
	jne     L0253
;
; this_file_name = dirent->d_name;
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$13
	jsr     staxysp
;
; free(the_folder->file_name_);
;
	ldy     #$22
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
;
; the_folder->file_name_ = NULL;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if (the_folder->device_number_ <= DEVICE_INTERNAL_SD && this_file_name[1] == ':')
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	cmp     #$02
	bcs     L025D
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$3A
	bne     L025D
;
; the_folder->file_name_ = General_StrlcpyWithAlloc(the_folder->device_number_ == DEVICE_EXTERNAL_SD ? "External SD" : "Internal micro SD", FILE_MAX_FILENAME_SIZE);
;
	ldy     #$24
	jsr     pushwysp
	ldy     #$24
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	bne     L0266
	lda     #<(L0265)
	ldx     #>(L0265)
	bra     L0269
L0266:	lda     #<(L0268)
	ldx     #>(L0268)
L0269:	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_StrlcpyWithAlloc
	ldy     #$02
	jsr     staxspidx
;
; else if (this_file_name[0] == NO_DISK_PRESENT_FILE_NAME || this_file_name[0] == NO_DISK_PRESENT_ANYMORE_FILE_NAME)
;
	jmp     L02D1
L025D:	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$1F
	beq     L03FE
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$1C
	bne     L026E
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_ERROR_NO_DISK), the_folder->device_number_);
;
L03FE:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$74
	jsr     _General_GetString
	jsr     pushax
	ldy     #$28
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; the_error_code = ERROR_COULD_NOT_OPEN_DIR;
;
	lda     #$6B
	ldy     #$0E
	sta     (sp),y
;
; break;
;
	jmp     L018D
;
; if ( this_file_name[0] == ' ' && this_file_name[1] == ' ')
;
L026E:	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	bne     L027E
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$20
	bne     L027E
;
; this_file_name += 2; // skip past the 2 spaces in "  MEATLOAF" sub dirs. annoying!
;
	ldy     #$13
	ldx     #$00
	lda     #$02
	jsr     addeqysp
;
; if (General_Strncasecmp(this_file_name, General_GetString(ID_STR_LBL_MEATLOAF_DIR_NAME), 8) == 0)
;
	ldy     #$16
	jsr     pushwysp
	lda     #$40
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0295
	cmp     #$00
	bne     L0295
;
; the_folder->is_meatloaf_ = true;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$0A
	sta     (ptr1),y
;
; General_Strlcpy(this_file_name + 8, General_GetString(ID_STR_LBL_MEATLOAF_LOCAL_MODIFIER), 9);
;
	ldy     #$14
	jsr     ldaxysp
	jsr     incax8
	jsr     pushax
	lda     #$41
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$09
	jsr     _General_Strlcpy
;
; else if (General_Strncasecmp(this_file_name, General_GetString(ID_STR_LBL_MEATLOAF_DIR_NAME), 8) == 0)
;
	bra     L0295
L027E:	ldy     #$16
	jsr     pushwysp
	lda     #$40
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _General_Strncasecmp
	cpx     #$00
	bne     L0295
	cmp     #$00
	bne     L0295
;
; the_folder->is_meatloaf_ = true;
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$0A
	sta     (ptr1),y
;
; the_folder->file_name_ = General_StrlcpyWithAlloc(this_file_name, FILE_MAX_FILENAME_SIZE);
;
L0295:	ldy     #$24
	jsr     pushwysp
	ldy     #$18
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_StrlcpyWithAlloc
	ldy     #$02
	jsr     staxspidx
;
; else if (_DE_ISREG(dirent->d_type))
;
	jmp     L02D1
L0253:	ldy     #$10
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	jne     L02D1
	cmp     #$00
	jne     L02D1
;
; this_file_name = dirent->d_name;
;
	ldy     #$10
	jsr     ldaxysp
	ldy     #$0C
	jsr     incaxy
	ldy     #$13
	jsr     staxysp
;
; if (this_file_name[0] == '.')
;
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$2E
;
; else
;
	jeq     L02D1
;
; if (the_folder->is_meatloaf_ == true && the_block_size < 2)
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	cmp     #$01
	bne     L02AE
	tay
	lda     (sp),y
	cmp     #$00
	bne     L02B1
	lda     (sp)
	cmp     #$02
L02B1:	bcs     L02AE
;
; this_file = File_New(the_panel_id, this_file_name, PARAM_FILE_IS_FOLDER, 0, _CBM_T_DIR, file_cnt, &this_datetime);
;
	ldy     #$23
	lda     (sp),y
	jsr     pusha
	ldy     #$17
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	jsr     pushl0
	lda     #$02
	jsr     pusha
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _File_New
	ldy     #$08
	jsr     staxysp
;
; if (this_file == NULL)
;
	cpx     #$00
	bne     L02CC
	cmp     #$00
	bne     L02CC
;
; goto error;
;
	jmp     L0415
;
; calc_file_size = (uint32_t)the_block_size * (uint32_t)dirent->d_blocks;
;
L02AE:	jsr     ldax0sp
	jsr     axulong
	jsr     pusheax
	ldy     #$14
	jsr     ldaxysp
	ldy     #$05
	jsr     ldeaxidx
	jsr     tosumuleax
	ldy     #$15
	jsr     steaxysp
;
; this_file = File_New(the_panel_id, this_file_name, PARAM_FILE_IS_NOT_FOLDER, calc_file_size, _CBM_T_REG, file_cnt, &this_datetime);
;
	ldy     #$23
	lda     (sp),y
	jsr     pusha
	ldy     #$17
	jsr     pushwysp
	lda     #$00
	jsr     pusha
	ldy     #$1C
	jsr     ldeaxysp
	jsr     pusheax
	lda     #$10
	jsr     pusha
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _File_New
	ldy     #$08
	jsr     staxysp
;
; if (this_file == NULL)
;
	cpx     #$00
	bne     L02CC
	cmp     #$00
	bne     L02CC
;
; stop_processing = true;
;
	ina
	ldy     #$1E
	sta     (sp),y
;
; if (stop_processing != true)
;
L02CC:	ldy     #$1E
	lda     (sp),y
	cmp     #$01
	beq     L02D1
;
; file_added = Folder_AddNewFile(the_folder, this_file);
;
	ldy     #$24
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Folder_AddNewFile
	ldy     #$1F
	sta     (sp),y
;
; if (!file_added) { File_Destroy(&this_file); goto error; }
;
	lda     (sp),y
	bne     L02D7
	lda     #$08
	jsr     leaa0sp
	jsr     _File_Destroy
	jmp     L0203
;
; if (file_cnt == 0)
;
L02D7:	ldy     #$0C
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L02DC
;
; this_file->selected_ = true;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$0B
	sta     (ptr1),y
;
; ++file_cnt;
;
L02DC:	ldy     #$0C
	ldx     #$00
	lda     #$01
	jsr     addeqysp
;
; if (the_folder->is_meatloaf_) max_file_cnt = 254; // reserve the home entry
;
L02D1:	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L02E2
	ldx     #$00
	lda     #$FE
	jsr     staxysp
;
; while ( (dirent = Kernel_ReadDir(dir)) != NULL && file_cnt < max_file_cnt && stop_processing == false )
;
L02E2:	ldy     #$12
	jsr     ldaxysp
	jsr     _Kernel_ReadDir
	ldy     #$0F
	jsr     staxysp
	cpx     #$00
	bne     L040F
	cmp     #$00
	beq     L018D
L040F:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0A
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L018D
	ldy     #$1E
	lda     (sp),y
	jeq     L03E5
;
; Kernel_CloseDir(dir);
;
L018D:	ldy     #$12
	jsr     ldaxysp
	jsr     _Kernel_CloseDir
;
; dir = NULL;
;
	ldx     #$00
	txa
	ldy     #$11
	jsr     staxysp
;
; if (the_folder->is_meatloaf_ == true && file_cnt < 255)
;
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	cmp     #$01
	bne     L02EA
	ldy     #$0D
	lda     (sp),y
	cmp     #$00
	bne     L02ED
	dey
	lda     (sp),y
	cmp     #$FF
L02ED:	bcs     L02EA
;
; this_file = File_New(the_panel_id, "^", PARAM_FILE_IS_FOLDER, 0, _CBM_T_DIR, file_cnt, &this_datetime);
;
	ldy     #$23
	lda     (sp),y
	jsr     pusha
	lda     #<(L02F2)
	ldx     #>(L02F2)
	jsr     pushax
	lda     #$01
	jsr     pusha
	jsr     pushl0
	lda     #$02
	jsr     pusha
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _File_New
	ldy     #$08
	jsr     staxysp
;
; if (this_file == NULL)
;
	cpx     #$00
	bne     L0410
	cmp     #$00
;
; goto error;
;
	jeq     L0415
;
; file_added = Folder_AddNewFile(the_folder, this_file);
;
L0410:	ldy     #$24
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Folder_AddNewFile
	ldy     #$1F
	sta     (sp),y
;
; if (!file_added) { File_Destroy(&this_file); goto error; }
;
	lda     (sp),y
	bne     L0301
	lda     #$08
	jsr     leaa0sp
	jsr     _File_Destroy
	jmp     L0203
;
; ++file_cnt;
;
L0301:	ldy     #$0C
	ldx     #$00
	lda     #$01
	jsr     addeqysp
;
; the_folder->cur_row_ = (file_cnt > 0 ? 0 : -1);
;
L02EA:	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0C
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L030B
	ldx     #$00
	bra     L0426
L030B:	ldx     #$FF
L0426:	txa
	ldy     #$08
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; if (skipped_long_name) Buffer_NewMessage("Skipped names longer than 31 characters.");
;
	ldy     #$1D
	lda     (sp),y
	beq     L030F
	lda     #<(L0312)
	ldx     #>(L0312)
	jsr     _Buffer_NewMessage
;
; if ((file_cnt >= max_file_cnt && dirent != NULL) || stop_processing)
;
L030F:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0A
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L03DE
	ldy     #$0F
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L040A
L03DE:	ldy     #$1E
	lda     (sp),y
	beq     L0314
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_TRUNCATED_DIR_WARNING), file_cnt);
;
L040A:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$4F
	jsr     _General_GetString
	jsr     pushax
	ldy     #$15
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_N_FILES_FOUND), file_cnt);
;
L0314:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$4D
	jsr     _General_GetString
	jsr     pushax
	ldy     #$15
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; return (the_error_code);
;
	ldy     #$0E
	ldx     #$00
	bra     L03E2
;
; the_error_code = ERROR_COULD_NOT_CREATE_NEW_FILE_OBJECT;
;
L0203:	ldx     #$00
L0415:	lda     #$6C
	ldy     #$0E
	sta     (sp),y
;
; if (dir) Kernel_CloseDir(dir);
;
	ldy     #$12
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L040D
	iny
	jsr     ldaxysp
	jsr     _Kernel_CloseDir
;
; dir = NULL;
;
	ldx     #$00
	txa
	ldy     #$11
L040D:	jsr     staxysp
;
; return (the_error_code);
;
	ldy     #$0E
L03E2:	lda     (sp),y
;
; }
;
L0154:	ldy     #$24
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; __near__ struct WB2KFileObject * __near__ Folder_SetFileSelectionByRow (__near__ struct WB2KFolderObject *, unsigned int, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_SetFileSelectionByRow: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusha
;
; the_file = Folder_FindFileByRow(the_folder, the_row);
;
	jsr     decsp4
	ldy     #$0B
	jsr     pushwysp
	ldy     #$08
	lda     (sp),y
	jsr     _Folder_FindFileByRow
	ldy     #$02
	jsr     staxysp
;
; if (the_file == NULL)
;
	cpx     #$00
	bne     L0399
	cmp     #$00
;
; return NULL;
;
	jeq     L0394
;
; if (do_selection)
;
L0399:	ldy     #$05
	lda     (sp),y
	beq     L039D
;
; if (the_folder->cur_row_ != the_row)
;
	ldy     #$09
	jsr     ldaxysp
	ldy     #$09
	jsr     ldaxidx
	ldy     #$06
	cmp     (sp),y
	bne     L042A
	txa
	iny
	cmp     (sp),y
	beq     L03A9
;
; the_prev_selected_file = Folder_FindFileByRow(the_folder, the_folder->cur_row_);
;
L042A:	ldy     #$0B
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     _Folder_FindFileByRow
	jsr     stax0sp
;
; if (the_prev_selected_file == NULL)
;
	cpx     #$00
	bne     L042B
	cmp     #$00
;
; else
;
	beq     L03A9
;
; if (File_MarkUnSelected(the_prev_selected_file, y_offset) == false)
;
L042B:	jsr     pushw0sp
	ldy     #$06
	lda     (sp),y
	jsr     _File_MarkUnSelected
	cmp     #$00
	bne     L03A9
;
; App_Exit(ERROR_FILE_MARK_UNSELECTED_FILE_WAS_NULL);
;
	lda     #$77
	jsr     _App_Exit
;
; the_folder->cur_row_ = the_row;
;
L03A9:	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$07
	jsr     ldaxysp
	ldy     #$08
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; if (File_MarkSelected(the_file, y_offset) == false)
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$06
	lda     (sp),y
	jsr     _File_MarkSelected
	cmp     #$00
	bne     L03BC
;
; App_Exit(ERROR_FILE_MARK_SELECTED_FILE_WAS_NULL);
;
	lda     #$76
;
; else
;
	bra     L0429
;
; if (the_folder->cur_row_ == the_row)
;
L039D:	ldy     #$09
	jsr     ldaxysp
	ldy     #$09
	jsr     ldaxidx
	ldy     #$06
	cmp     (sp),y
	bne     L03B8
	txa
	iny
	cmp     (sp),y
	bne     L03B8
;
; the_folder->cur_row_ = -1;
;
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$08
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if (File_MarkUnSelected(the_file, y_offset) == false)
;
L03B8:	ldy     #$05
	jsr     pushwysp
	ldy     #$06
	lda     (sp),y
	jsr     _File_MarkUnSelected
	cmp     #$00
	bne     L03BC
;
; App_Exit(ERROR_FILE_MARK_UNSELECTED_FILE_WAS_NULL);
;
	lda     #$77
L0429:	jsr     _App_Exit
;
; return the_file;
;
L03BC:	ldy     #$03
	jsr     ldaxysp
;
; }
;
L0394:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; __near__ struct _FILE * __near__ Folder_GetTargetHandleForWriting (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_GetTargetHandleForWriting: near

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pushax
;
; return fopen(the_target_file_path, "wb");
;
	jsr     pushw0sp
	lda     #<(L03C6)
	ldx     #>(L03C6)
	jsr     _fopen
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; long __near__ Folder_CopyFileBytes (__near__ const unsigned char *, __near__ const unsigned char *, long)
; ---------------------------------------------------------------

.segment	"OVERLAY_DISKSYS"

.proc	_Folder_CopyFileBytes: near

.segment	"RODATA"

L0036:
	.word	$0000
L003C:
	.word	$0000
L004E:
	.word	$0000
L0051:
	.word	$0000
L0065:
	.word	$0000
L006C:
	.word	$0000
L0075:
	.word	$0000

.segment	"OVERLAY_DISKSYS"

;
; {
;
	jsr     pusheax
;
; FILE* source = NULL;
;
	jsr     push0
;
; FILE* target = NULL;
;
	jsr     push0
;
; uint8_t* buffer = (uint8_t*)STORAGE_FILE_BUFFER_1;
;
	ldx     #$05
	jsr     pushax
;
; int32_t total = 0;
;
	jsr     decsp2
	jsr     pushl0
;
; if (strcmp(the_source_file_path, the_target_file_path) == 0) return -1;
;
	jsr     decsp4
	ldy     #$19
	jsr     pushwysp
	ldy     #$17
	jsr     ldaxysp
	jsr     _strcmp
	cpx     #$00
	bne     L0027
	cmp     #$00
	jeq     L0433
;
; App_ShowProgressBar();
;
L0027:	jsr     _App_ShowProgressBar
;
; source = fopen(the_source_file_path, "rb");
;
	ldy     #$19
	jsr     pushwysp
	lda     #<(L0031)
	ldx     #>(L0031)
	jsr     _fopen
	ldy     #$0E
	jsr     staxysp
;
; if (!source) goto error;
;
	ldy     #$0F
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L0035
;
; target = Folder_GetTargetHandleForWriting(the_target_file_path);
;
	ldy     #$15
	jsr     ldaxysp
	jsr     _Folder_GetTargetHandleForWriting
	ldy     #$0C
	jsr     staxysp
;
; if (!target) goto error;
;
	ldy     #$0D
	lda     (sp),y
	dey
	ora     (sp),y
	jne     L003F
	jmp     L0035
;
; if (fwrite(buffer, 1, count, target) != count) goto error;
;
L003D:	ldy     #$0D
	jsr     pushwysp
	lda     #$01
	jsr     pusha0
	ldy     #$0F
	jsr     pushwysp
	ldy     #$13
	jsr     ldaxysp
	jsr     _fwrite
	ldy     #$08
	cmp     (sp),y
	jne     L0035
	txa
	iny
	cmp     (sp),y
	jne     L0035
;
; if (total > 2147483647L - count) goto error;
;
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$FF
	stx     sreg
	lda     #$7F
	sta     sreg+1
	txa
	jsr     pusheax
	ldy     #$11
	jsr     ldaxysp
	jsr     axulong
	jsr     tossubeax
	jsr     tosugteax
	jne     L0035
;
; total += count;
;
	ldy     #$09
	jsr     ldaxysp
	jsr     axulong
	ldy     #$04
	jsr     laddeqysp
;
; percent = expected_bytes > 0 ? (uint32_t)total / (((uint32_t)expected_bytes / 100) + 1) : 0;
;
	ldy     #$13
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$01
	jsr     tosgeeax
	beq     L0056
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$17
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	lda     #$64
	jsr     tosudiv0ax
	ldy     #$01
	jsr     inceaxy
	jsr     tosudiveax
	bra     L005A
L0056:	ldx     #$00
	txa
	jsr     axlong
L005A:	jsr     steax0sp
;
; App_UpdateProgressBar(percent > 100 ? 100 : percent);
;
	jsr     ldeax0sp
	cmp     #$65
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcc     L005E
	ldx     #$00
	lda     #$64
	jsr     axlong
	bra     L0060
L005E:	jsr     ldeax0sp
L0060:	jsr     _App_UpdateProgressBar
;
; while ((count = fread(buffer, 1, STORAGE_FILE_BUFFER_1_LEN, source)) != 0) {
;
L003F:	ldy     #$0D
	jsr     pushwysp
	lda     #$01
	jsr     pusha0
	tax
	dea
	jsr     pushax
	ldy     #$15
	jsr     ldaxysp
	jsr     _fread
	ldy     #$08
	jsr     staxysp
	cpx     #$00
	jne     L003D
	cmp     #$00
	jne     L003D
;
; if (ferror(source)) goto error;
;
	ldy     #$0F
	jsr     ldaxysp
	jsr     _ferror
	stx     tmp1
	ora     tmp1
	bne     L0035
;
; if (fclose(source) != 0) { source = NULL; goto error; }
;
	ldy     #$0F
	jsr     ldaxysp
	jsr     _fclose
	cpx     #$00
	bne     L042E
	cmp     #$00
	beq     L0431
L042E:	ldx     #$00
	txa
	ldy     #$0E
	jsr     staxysp
	bra     L0035
;
; source = NULL;
;
L0431:	ldy     #$0E
	jsr     staxysp
;
; if (fclose(target) != 0) { target = NULL; goto error; }
;
	ldy     #$0D
	jsr     ldaxysp
	jsr     _fclose
	cpx     #$00
	bne     L042F
	cmp     #$00
	beq     L006F
L042F:	ldx     #$00
	txa
	ldy     #$0C
	jsr     staxysp
	bra     L0035
;
; App_HideProgressBar();
;
L006F:	jsr     _App_HideProgressBar
;
; return total;
;
	ldy     #$07
	jsr     ldeaxysp
	bra     L0022
;
; if (source) fclose(source);
;
L0035:	ldy     #$0F
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0079
	iny
	jsr     ldaxysp
	jsr     _fclose
;
; if (target) fclose(target);
;
L0079:	ldy     #$0D
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L007D
	iny
	jsr     ldaxysp
	jsr     _fclose
;
; App_HideProgressBar();
;
L007D:	jsr     _App_HideProgressBar
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_GENERIC_DISK));
;
	lda     #$73
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return -1;
;
L0433:	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
;
; }
;
L0022:	ldy     #$18
	jmp     addysp

.endproc
