; MicroKernel API: Copyright 2022 Jessie Oberreuter. See ../API-NOTICE.
; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strlen
	.export		_write
	.export		_read
	.export		_open
	.export		_close
	.export		_Kernel_OpenDir
	.export		_Kernel_ReadDir
	.export		_Kernel_CloseDir
	.import		_General_Strlcpy
	.import		_General_Strnlen
	.import		_Keyboard_DeferBackgroundEvent
	.export		_args
	.export		_event
	.export		_error
	.export		_kernel_init
	.export		_scroll
	.export		_GETIN
	.export		_Kernal_AnyKeyEvent
	.export		_Kernel_DeleteFile
	.export		_Kernel_DeleteFolder
	.export		_rename
	.export		_mkfs
	.export		_Kernal_MkDir
	.export		_Kernal_RunNamed
	.export		_Kernal_LoadApp

.segment	"DATA"

_row:
	.byte	$00
_col:
	.byte	$00
_line:
	.word	$C000

.segment	"BSS"

.segment	"KERNEL_ARGS"
_args:
	.res	16,$00
.segment	"ZEROPAGE"
_event:
	.res	9,$00
_error:
	.res	1,$00
.segment	"BSS"
_dir_stream:
	.res	4,$00

; ---------------------------------------------------------------
; int __near__ __fastcall__ write (int, __near__ const void *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; uint8_t  *data = buf;
;
	ldy     #$05
	jsr     pushwysp
;
; int      total = 0;
;
	jsr     push0
;
; if (fd == 1 || fd == 2) {
;
	jsr     decsp3
	ldy     #$0C
	lda     (sp),y
	bne     L04A5
	dey
	lda     (sp),y
	cmp     #$01
	beq     L04A0
	iny
L04A5:	lda     (sp),y
	jne     L01E0
	dey
	lda     (sp),y
	cmp     #$02
	jne     L01E0
;
; char *text = (char*) buf;
;
L04A0:	jsr     decsp2
	ldy     #$0E
	jsr     pushwysp
;
; for (i = 0; i < nbytes; i++) {
;
	ldx     #$00
	txa
L04A6:	ldy     #$02
	jsr     staxysp
	ldy     #$0B
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L01D2
;
; out(text[i]);
;
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     (sp)
	sta     ptr1
	txa
	ldy     #$01
	adc     (sp),y
	sta     ptr1+1
	lda     (ptr1)
	jsr     _out
;
; for (i = 0; i < nbytes; i++) {
;
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L04A6
	inx
	bra     L04A6
;
; return i;
;
L01D2:	ldy     #$03
	jsr     ldaxysp
	jsr     incsp4
	bra     L01C8
;
; if (nbytes > 254) {
;
L01DE:	iny
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bcc     L01E2
;
; writing = 254;
;
	lda     #$FE
;
; } else {
;
	bra     L04A4
;
; writing = nbytes;
;
L01E2:	ldy     #$07
	lda     (sp),y
L04A4:	ldy     #$02
	sta     (sp),y
;
; written = kernel_write(fd, data+total, writing);
;
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$06
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     _kernel_write
	jsr     stax0sp
;
; if (written <= 0) {
;
	cmp     #$01
	txa
	sbc     #$00
	bvc     L01F0
	eor     #$80
L01F0:	bpl     L01EE
;
; return -1;
;
	ldx     #$FF
	txa
	bra     L01C8
;
; total += written;
;
L01EE:	jsr     ldax0sp
	ldy     #$03
	jsr     addeqysp
;
; nbytes -= written;
;
	jsr     ldax0sp
	ldy     #$07
	jsr     subeqysp
;
; while (nbytes) {
;
L01E0:	ldy     #$08
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L01DE
;
; return total;
;
	ldy     #$04
	jsr     ldaxysp
;
; }
;
L01C8:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ read (int, __near__ void *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; char *data = buf;
;
	ldy     #$05
	jsr     pushwysp
;
; int  gathered = 0;
;
	jsr     push0
;
; while (gathered < nbytes) {
;
	bra     L018E
;
; int returned = Kernel_Read(fd, data + gathered, nbytes - gathered);
;
L018C:	ldy     #$0B
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	clc
	ldy     #$04
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	jsr     _Kernel_Read
	jsr     pushax
;
; if (returned < 0) return -1;
;
	jsr     ldax0sp
	cpx     #$80
	bcc     L0194
	ldx     #$FF
	txa
	jsr     incsp2
	bra     L0189
;
; if (returned == 0) {
;
L0194:	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L04A7
;
; break;
;
	jsr     incsp2
	bra     L018D
;
; gathered += returned;
;
L04A7:	jsr     ldax0sp
	ldy     #$02
	jsr     addeqysp
;
; }
;
	jsr     incsp2
;
; while (gathered < nbytes) {
;
L018E:	jsr     ldax0sp
	ldy     #$04
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L018C
;
; return gathered;
;
L018D:	jsr     ldax0sp
;
; }
;
L0189:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ open (__near__ const unsigned char *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_open: near

.segment	"CODE"

;
; {
;
	jsr     enter
;
; int ret = 0;
;
	jsr     push0
;
; fname = path_without_drive(fname, &drive);
;
	jsr     decsp1
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	jsr     incax2
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     leaa0sp
	jsr     incax4
	jsr     pushw
	lda     #$04
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$00
	jsr     staxspidx
;
; if (drive >= MAX_DRIVES || strlen(fname) > 255) return -1;
;
	lda     (sp)
	cmp     #$04
	jcs     L013A
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	jsr     incax2
	jsr     ldaxi
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	jcs     L013A
;
; args.common.buf = (uint8_t*) fname;
;
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	jsr     incax2
	jsr     ldaxi
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(fname);
;
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	jsr     incax2
	jsr     ldaxi
	jsr     _strlen
	sta     _args+13
;
; args.file.open.drive = drive;
;
	lda     (sp)
	sta     _args+3
;
; if ((mode & (O_RDONLY | O_WRONLY)) == O_RDONLY) {
;
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	jsr     ldaxi
	and     #$03
	cmp     #$01
	bne     L0108
;
; mode = 0;
;
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
;
; } else {
;
	bra     L04AD
;
; mode = 1;
;
L0108:	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	sta     (ptr1)
	tay
	dea
L04AD:	sta     (ptr1),y
;
; args.file.open.mode = mode;
;
	ldy     #$03
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1)
	sta     _args+5
;
; ret = CALL(File.Open);
;
	jsr     _KernelCall_FF5C
	stz     _error
	ror     _error
	ldx     #$00
	ldy     #$01
	jsr     staxysp
;
; if (error) {
;
	lda     _error
	beq     L04AB
;
; return -1;
;
	bra     L013A
;
; event.type = 0;
;
L04AA:	lda     #$00
L04AB:	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; switch (event.type) {
;
	ldx     #$00
	lda     _event
;
; }
;
	cmp     #$28
	beq     L013A
	cmp     #$2A
	beq     L0135
	cmp     #$38
	beq     L013A
	bra     L04AA
;
; return ret + 3;
;
L0135:	ldy     #$02
	jsr     ldaxysp
	jsr     incax3
	bra     L0124
;
; return -1;
;
L013A:	ldx     #$FF
	txa
;
; }
;
L0124:	ldy     #$03
	jmp     leavey

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ close (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_close: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (fd < 3) return 0;
;
	jsr     ldax0sp
	cmp     #$03
	txa
	sbc     #$00
	bvc     L01FA
	eor     #$80
L01FA:	bpl     L01F8
	ldx     #$00
	txa
	jmp     incsp2
;
; args.file.close.stream = fd - 3;
;
L01F8:	ldy     #$00
	lda     (sp)
	sec
	sbc     #$03
	ldx     #$00
	sta     _args+3
;
; CALL(File.Close);
;
	jsr     _KernelCall_FF68
	stz     _error
	ror     _error
;
; if (error) return -1;
;
	lda     _error
	beq     L020F
	ldx     #$FF
	txa
	jmp     incsp2
;
; event.type = 0;
;
L020F:	tax
L04AE:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; switch (event.type) {
;
	ldx     #$00
	lda     _event
;
; }
;
	cmp     #$32
	beq     L04AF
	cmp     #$38
	beq     L0223
	bra     L04AE
;
; return 0;
;
L04AF:	txa
	jmp     incsp2
;
; return -1;
;
L0223:	dex
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; __near__ struct DIR * __near__ __fastcall__ Kernel_OpenDir (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_OpenDir: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; name = path_without_drive(name, &drive);
;
	jsr     decsp2
	ldy     #$05
	jsr     pushwysp
	lda     #$03
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$02
	jsr     staxysp
;
; if (drive >= MAX_DRIVES || strlen(name) > 255) return NULL;
;
	ldy     #$01
	lda     (sp),y
	cmp     #$04
	bcs     L04B0
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L022D
L04B0:	ldx     #$00
	txa
	jmp     incsp4
;
; if (dir_stream[drive]) {
;
L022D:	ldy     #$01
	lda     (sp),y
	tay
	lda     _dir_stream,y
	beq     L0232
;
; return NULL;  // Only one at a time.
;
	ldx     #$00
	txa
	jmp     incsp4
;
; args.directory.open.drive = drive;
;
L0232:	ldy     #$01
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = name;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(name);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	ldx     #$00
	sta     _args+13
;
; stream = CALL(Directory.Open);
;
	jsr     _KernelCall_FF78
	stz     _error
	ror     _error
	ldy     #$00
	sta     (sp)
;
; if (error) {
;
	lda     _error
	beq     L0250
;
; return NULL;
;
	ldx     #$00
	txa
	jmp     incsp4
;
; event.type = 0;
;
L0250:	tax
L04B1:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(directory.OPENED)) {
;
	lda     _event
	cmp     #$3C
;
; break;
;
	beq     L024E
;
; if (event.type == EVENT(directory.ERROR)) {
;
	ldx     #$00
	lda     _event
	cmp     #$48
	bne     L04B1
;
; return NULL;
;
	txa
	jmp     incsp4
;
; dir_stream[drive] = stream;
;
L024E:	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	sta     _dir_stream,x
;
; return (DIR*) &dir_stream[drive];
;
	lda     #<(_dir_stream)
	ldx     #>(_dir_stream)
	ldy     #$01
	clc
	adc     (sp),y
	bcc     L0228
	inx
;
; }
;
L0228:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; __near__ struct dirent * __near__ __fastcall__ Kernel_ReadDir (__near__ struct DIR *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_ReadDir: near

.segment	"BSS"

L026A:
	.res	268,$00

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (!dir) {
;
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	bne     L026B
;
; return NULL;
;
	tax
	jmp     incsp2
;
; args.directory.read.stream = *(char*)dir;
;
L026B:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1)
	sta     _args+3
;
; CALL(Directory.Read);
;
	jsr     _KernelCall_FF7C
	stz     _error
	ror     _error
;
; if (error) {
;
	lda     _error
	beq     L0281
;
; return NULL;
;
	ldx     #$00
	txa
	jmp     incsp2
;
; event.type = 0;
;
L0281:	jsr     decsp2
	ldx     #$00
	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; switch (event.type) {
;
	ldx     #$00
	lda     _event
;
; }
;
	cmp     #$3E
	beq     L04B2
	cmp     #$40
	beq     L04B3
	cmp     #$42
	jeq     L02B9
	cmp     #$44
	jeq     L04B4
	cmp     #$48
	jeq     L04B4
	jmp     L02D2
;
; dirent.d_blocks = 0;
;
L04B2:	stz     sreg
	stz     sreg+1
	stz     L026A+2
	stz     L026A+2+1
	stz     L026A+2+2
	stz     L026A+2+3
;
; dirent.d_type = 2;
;
	lda     #$02
	sta     L026A
	stz     L026A+1
;
; break;
;
	jmp     L04B5
;
; dirent.d_blocks = 0;
;
L04B3:	stz     sreg
	stz     sreg+1
	stz     L026A+2
	stz     L026A+2+1
	ldy     #$00
	stz     L026A+2+2
	stz     L026A+2+3
;
; args.common.buf = &dirent.d_blocks;
;
	lda     #>(L026A+2)
	sta     _args+11+1
	lda     #<(L026A+2)
	sta     _args+11
;
; args.common.buflen = 3; // 6 to pick up the 6 bytes of date info
;
	lda     #$03
	sta     _args+13
;
; CALL(ReadExt);
;
	jsr     _KernelCall_FF08
	stz     _error
	ror     _error
;
; dirent.d_type = ((char*)dir - dir_stream <= DEVICE_INTERNAL_SD) ?
;
	ldy     #$03
	jsr     ldaxysp
	sec
	sbc     #<(_dir_stream)
	pha
	txa
	sbc     #>(_dir_stream)
	tax
	pla
	cmp     #$02
	txa
	sbc     #$00
	bvc     L02AD
	eor     #$80
;
; ((event.directory.file.flags & 0x10) != 0) : (dirent.d_blocks == 0);
;
L02AD:	bpl     L02AE
	lda     _event+6
	and     #$10
	jsr     boolne
	bra     L02B3
L02AE:	lda     L026A+2+3
	sta     sreg+1
	lda     L026A+2+2
	sta     sreg
	ldx     L026A+2+1
	lda     L026A+2
	jsr     pusheax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	txa
	jsr     toseqeax
L02B3:	sta     L026A
	stx     L026A+1
;
; break;
;
	bra     L04B5
;
; args.directory.read.stream = *(char*)dir;
;
L02B9:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1)
	sta     _args+3
;
; CALL(Directory.Read);
;
	jsr     _KernelCall_FF7C
	stz     _error
	ror     _error
;
; if (!error) {
;
	lda     _error
	bne     L02C7
;
; continue;
;
	jsr     incsp2
	jmp     L0281
;
; return NULL;
;
L02C7:	ldx     #$00
L04B4:	txa
	jsr     incsp2
	jmp     incsp2
;
; default: continue;
;
L02D2:	jsr     incsp2
	jmp     L0281
;
; len = event.directory.file.len;
;
L04B5:	lda     _event+5
	ldx     #$00
	jsr     stax0sp
;
; if (len >= sizeof(dirent.d_name)) {
;
	cmp     #$00
	txa
	sbc     #$01
	bcc     L02D5
;
; len = sizeof(dirent.d_name) - 1;
;
	lda     #$FF
	jsr     stax0sp
;
; if (len > 0) {
;
L02D5:	lda     (sp)
	ldy     #$01
	ora     (sp),y
	beq     L02DB
;
; args.common.buf = &dirent.d_name;
;
	lda     #>(L026A+12)
	sta     _args+11+1
	lda     #<(L026A+12)
	sta     _args+11
;
; args.common.buflen = len;
;
	dey
	lda     (sp)
	sta     _args+13
;
; CALL(ReadData);
;
	jsr     _KernelCall_FF04
	stz     _error
	ror     _error
;
; dirent.d_name[len] = '\0';
;
L02DB:	lda     #<(L026A+12)
	clc
	adc     (sp)
	sta     ptr1
	lda     #>(L026A+12)
	ldy     #$01
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; return &dirent;
;
	lda     #<(L026A)
	ldx     #>(L026A)
	jsr     incsp2
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ Kernel_CloseDir (__near__ struct DIR *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_CloseDir: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (!dir || !*(char*)dir) return -1;
;
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	beq     L02F3
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L02F2
L02F3:	ldx     #$FF
	txa
	jmp     incsp2
;
; args.directory.close.stream = *(char*)dir;
;
L02F2:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1)
	sta     _args+3
;
; CALL(Directory.Close);
;
	jsr     _KernelCall_FF80
	stz     _error
	ror     _error
;
; if (error) return -1;
;
	lda     _error
	beq     L0309
	ldx     #$FF
	txa
	jmp     incsp2
;
; event.type = 0;
;
L0309:	ldx     #$00
L04B6:	txa
	stz     _event
;
; CALL(NextEvent);
;
	jsr     _KernelCall_FF00
	stz     _error
	ror     _error
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (error) { asm("jsr %w", VECTOR(Yield)); continue; }
;
	lda     _error
	beq     L0318
	jsr     _KernelCall_FF0C
	bra     L0309
;
; if (event.type == EVENT(directory.CLOSED)) {
;
L0318:	tax
	lda     _event
	cmp     #$46
	bne     L04B7
;
; *(char*)dir = 0;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; return 0;
;
	tax
	jmp     incsp2
;
; if (event.type == EVENT(directory.ERROR)) return -1;
;
L04B7:	lda     _event
	cmp     #$48
	bne     L04B6
	dex
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ kernel_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_kernel_init: near

.segment	"CODE"

;
; args.events.event = &event;
;
	lda     #>(_event)
	sta     _args+1
	lda     #<(_event)
	sta     _args
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ cls (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cls: near

.segment	"CODE"

;
; char *vram = (char*)0xc000;
;
	jsr     decsp2
	ldx     #$C0
	lda     #$00
	jsr     pushax
;
; asm("lda #$02");
;
	lda     #$02
;
; asm("sta $01");
;
	sta     $01
;
; for (i = 0; i < 80*60; i++) {
;
	ldx     #$00
	txa
L04BB:	ldy     #$02
	jsr     staxysp
	cmp     #$C0
	txa
	sbc     #$12
	bvc     L0026
	eor     #$80
L0026:	asl     a
	bcc     L04B9
;
; *vram++ = 32;
;
	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	ina
	bne     L002A
	inx
L002A:	jsr     stax0sp
	lda     #$20
	sta     (regsave)
;
; for (i = 0; i < 80*60; i++) {
;
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L04BB
	inx
	bra     L04BB
;
; row = col = 0;
;
L04B9:	stz     _col
	stz     _row
;
; line = (char*)0xc000;
;
	ldx     #$C0
	stz     _line
	stx     _line+1
;
; asm("stz $1"); asm("lda #9"); asm("sta $d010");
;
	stz     $1
	lda     #9
	sta     $d010
;
; (__A__ = row, asm("sta $d016"), asm("stz $d017"));
;
	lda     _row
	sta     $d016
	stz     $d017
;
; (__A__ = col, asm("sta $d014"), asm("stz $d015"));
;
	lda     _col
	sta     $d014
	stz     $d015
;
; asm("lda #'_'"); asm("sta $d012");
;
	lda     #'_'
	sta     $d012
;
; asm("stz $d011");
;
	stz     $d011
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scroll: near

.segment	"CODE"

;
; char *vram = (char*)0xc000;
;
	jsr     decsp2
	ldx     #$C0
	lda     #$00
	jsr     pushax
;
; asm("lda #$02");
;
	lda     #$02
;
; asm("sta $01");
;
	sta     $01
;
; for (i = 0; i < 80*59; i++) {
;
	ldx     #$00
	txa
L04BE:	ldy     #$02
	jsr     staxysp
	cmp     #$70
	txa
	sbc     #$12
	bvc     L0058
	eor     #$80
L0058:	bpl     L0052
;
; vram[i] = vram[i+80];
;
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     (sp)
	sta     sreg
	txa
	ldy     #$01
	adc     (sp),y
	sta     sreg+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$50
	jsr     incaxy
	clc
	adc     (sp)
	sta     ptr1
	txa
	ldy     #$01
	adc     (sp),y
	sta     ptr1+1
	lda     (ptr1)
	sta     (sreg)
;
; for (i = 0; i < 80*59; i++) {
;
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L04BE
	inx
	bra     L04BE
;
; vram += i;
;
L0052:	ldy     #$03
	jsr     ldaxysp
	jsr     addeq0sp
;
; for (i = 0; i < 80; i++) {
;
	ldx     #$00
	txa
L04BF:	ldy     #$02
	jsr     staxysp
	cmp     #$50
	txa
	sbc     #$00
	bvc     L0068
	eor     #$80
L0068:	bpl     L0062
;
; *vram++ = 32;
;
	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	ina
	bne     L006C
	inx
L006C:	jsr     stax0sp
	lda     #$20
	sta     (regsave)
;
; for (i = 0; i < 80; i++) {
;
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L04BF
	inx
	bra     L04BF
;
; }
;
L0062:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ out (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_out: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; switch (c) {
;
	lda     (sp)
;
; }
;
	cmp     #$0A
	beq     L04C1
	cmp     #$0C
	beq     L0073
	cmp     #$0D
	beq     L04C1
	bra     L0075
;
; cls();
;
L0073:	jsr     _cls
;
; break;
;
	bra     L0071
;
; asm("lda #2");
;
L0075:	lda     #2
;
; asm("sta $01");
;
	sta     $01
;
; line[col] = c;
;
	lda     _line
	ldx     _line+1
	clc
	adc     _col
	bcc     L04C0
	inx
L04C0:	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
;
; col++;
;
	inc     _col
;
; if (col != MAX_COL) {
;
	lda     _col
	cmp     #$50
;
; break;
;
	bne     L0071
;
; col = 0;
;
L04C1:	stz     _col
;
; row++;
;
	inc     _row
;
; if (row == MAX_ROW) {
;
	lda     _row
	cmp     #$3C
	bne     L0087
;
; scroll();
;
	jsr     _scroll
;
; row--;
;
	dec     _row
;
; break;
;
	bra     L0071
;
; line += 80;
;
L0087:	lda     #$50
	clc
	adc     _line
	sta     _line
	bcc     L0071
	inc     _line+1
;
; asm("stz $01");
;
L0071:	stz     $01
;
; (__A__ = row, asm("sta $d016"));
;
	lda     _row
	sta     $d016
;
; (__A__ = col, asm("sta $d014"));
;
	lda     _col
	sta     $d014
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GETIN (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GETIN: near

.segment	"CODE"

;
; CALL(NextEvent);
;
L009B:	jsr     _KernelCall_FF00
	stz     _error
	ror     _error
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (error) {
;
	lda     _error
	beq     L00AB
;
; asm("jsr %w", VECTOR(Yield));
;
	jsr     _KernelCall_FF0C
;
; continue;
;
	bra     L009B
;
; if (event.type != EVENT(key.PRESSED)) {
;
L00AB:	tax
	lda     _event
	cmp     #$08
;
; continue;
;
	bne     L009B
;
; if (event.key.flags) {
;
	lda     _event+6
	beq     L04C5
;
; if (event.key.raw >= CH_F1 && event.key.raw <= CH_F8)
;
	lda     _event+4
	cmp     #$81
	txa
	bcc     L009B
	lda     _event+4
	cmp     #$89
	bcc     L04C4
	txa
	bra     L009B
;
; return event.key.raw;
;
L04C4:	lda     _event+4
	rts
;
; return event.key.ascii;
;
L04C5:	lda     _event+5
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Kernal_AnyKeyEvent (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernal_AnyKeyEvent: near

.segment	"CODE"

;
; CALL(NextEvent);
;
	jsr     _KernelCall_FF00
	stz     _error
	ror     _error
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (error) {
;
	lda     _error
	beq     L00CF
;
; asm("jsr %w", VECTOR(Yield));
;
	jsr     _KernelCall_FF0C
;
; return false;
;
	ldx     #$00
	txa
	rts
;
; if (event.type == EVENT(key.PRESSED)) {
;
L00CF:	tax
	lda     _event
	cmp     #$08
	bne     L04C6
;
; return true;
;
	lda     #$01
	rts
;
; return false;
;
L04C6:	txa
	rts

.endproc

; ---------------------------------------------------------------
; __near__ const unsigned char * __near__ path_without_drive (__near__ const unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_path_without_drive: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; *drive = 0;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; if (strlen(path) < 2) {
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	cpx     #$00
	bne     L00E3
	cmp     #$02
L00E3:	bcs     L00E0
;
; return path;
;
	ldy     #$03
	jsr     ldaxysp
	jmp     incsp4
;
; if (path[1] != ':') {
;
L00E0:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$3A
	beq     L00E5
;
; return path;
;
	ldy     #$03
	jsr     ldaxysp
	jmp     incsp4
;
; if ((*path >= '0') && (*path <= '3')) {
;
L00E5:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$30
	bcc     L00E9
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$34
	bcs     L00E9
;
; *drive = *path - '0';
;
	jsr     ldax0sp
	sta     sreg
	stx     sreg+1
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$30
	jsr     decaxy
	sta     (sreg)
;
; } else {
;
	bra     L00F1
;
; *drive = MAX_DRIVES;
;
L00E9:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$04
	sta     (ptr1)
;
; return (path + 2);
;
L00F1:	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ Kernel_Read (int, __near__ void *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_Read: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (fd == 0) {
;
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0142
;
; *(char*)buf = GETIN();
;
	jsr     pushwysp
	jsr     _GETIN
	ldy     #$00
	jsr     staspidx
;
; return 1;
;
	ldx     #$00
	lda     #$01
	jmp     incsp6
;
; if (nbytes > 255) {
;
L0142:	jsr     ldax0sp
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0148
;
; nbytes = 255;
;
	ldx     #$00
	lda     #$FF
	jsr     stax0sp
;
; args.file.read.stream = fd - 3;
;
L0148:	ldy     #$04
	lda     (sp),y
	sec
	sbc     #$03
	sta     _args+3
;
; args.file.read.buflen = nbytes;
;
	ldy     #$00
	ldx     #$00
	lda     (sp)
	sta     _args+4
;
; CALL(File.Read);
;
	jsr     _KernelCall_FF60
	stz     _error
	ror     _error
;
; if (error) {
;
	lda     _error
	beq     L0161
;
; return -1;
;
	ldx     #$FF
	txa
	jmp     incsp6
;
; event.type = 0;
;
L0161:	tax
L04CA:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; switch (event.type) {
;
	ldx     #$00
	lda     _event
;
; }
;
	cmp     #$2C
	beq     L0170
	cmp     #$30
	beq     L04CB
	cmp     #$38
	beq     L0186
	bra     L04CA
;
; args.common.buf = buf;
;
L0170:	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = event.file.data.delivered;
;
	ldx     #$00
	lda     _event+6
	sta     _args+13
;
; asm("jsr %w", VECTOR(ReadData));
;
	jsr     _KernelCall_FF04
;
; if (!event.file.data.delivered) {
;
	lda     _event+6
	bne     L017A
;
; return 256;
;
	ldx     #$01
	jmp     incsp6
;
; return event.file.data.delivered;
;
L017A:	lda     _event+6
	ldx     #$00
	jmp     incsp6
;
; return 0;
;
L04CB:	txa
	jmp     incsp6
;
; return -1;
;
L0186:	dex
	txa
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ kernel_write (unsigned char, __near__ void *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_kernel_write: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; args.file.read.stream = fd - 3;
;
	ldy     #$03
	lda     (sp),y
	sec
	sbc     #$03
	sta     _args+3
;
; args.common.buf = buf;
;
	dey
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = nbytes;
;
	ldy     #$00
	ldx     #$00
	lda     (sp)
	sta     _args+13
;
; CALL(File.Write);
;
	jsr     _KernelCall_FF64
	stz     _error
	ror     _error
;
; if (error) {
;
	lda     _error
	beq     L01B5
;
; return -1;
;
	ldx     #$FF
	txa
	jmp     incsp4
;
; event.type = 0;
;
L01B5:	tax
L04CC:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(file.WROTE)) {
;
	ldx     #$00
	lda     _event
	cmp     #$2E
	bne     L04CD
;
; return event.file.data.delivered;
;
	lda     _event+6
	jmp     incsp4
;
; if (event.type == EVENT(file.ERROR)) {
;
L04CD:	lda     _event
	cmp     #$38
	bne     L04CC
;
; return -1;
;
	dex
	txa
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ Kernel_DeleteFile (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_DeleteFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; name = path_without_drive(name, &drive);
;
	jsr     decsp2
	ldy     #$05
	jsr     pushwysp
	lda     #$03
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$02
	jsr     staxysp
;
; if (drive >= MAX_DRIVES || strlen(name) > 255) return false;
;
	ldy     #$01
	lda     (sp),y
	cmp     #$04
	bcs     L04CE
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0330
L04CE:	ldx     #$00
	txa
	jmp     incsp4
;
; args.file.delete.drive = drive;
;
L0330:	ldy     #$01
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = name;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(name);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	ldx     #$00
	sta     _args+13
;
; stream = CALL(File.Delete);
;
	jsr     _KernelCall_FF70
	stz     _error
	ror     _error
	ldy     #$00
	sta     (sp)
;
; if (error) {
;
	lda     _error
	beq     L034E
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp4
;
; event.type = 0;
;
L034E:	tax
L04CF:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(file.DELETED)) {
;
	ldx     #$00
	lda     _event
	cmp     #$36
;
; break;
;
	beq     L04D0
;
; if (event.type == EVENT(file.ERROR)) {
;
	cmp     #$38
	bne     L04CF
;
; return false;
;
	txa
	jmp     incsp4
;
; return true;
;
L04D0:	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ Kernel_DeleteFolder (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernel_DeleteFolder: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; name = path_without_drive(name, &drive);
;
	jsr     decsp2
	ldy     #$05
	jsr     pushwysp
	lda     #$03
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$02
	jsr     staxysp
;
; if (drive >= MAX_DRIVES || strlen(name) > 255) return false;
;
	ldy     #$01
	lda     (sp),y
	cmp     #$04
	bcs     L04D1
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0366
L04D1:	ldx     #$00
	txa
	jmp     incsp4
;
; args.file.delete.drive = drive;
;
L0366:	ldy     #$01
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = name;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(name);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	ldx     #$00
	sta     _args+13
;
; stream = CALL(Directory.RmDir);
;
	jsr     _KernelCall_FF88
	stz     _error
	ror     _error
	ldy     #$00
	sta     (sp)
;
; if (error) {
;
	lda     _error
	beq     L0384
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp4
;
; event.type = 0;
;
L0384:	tax
L04D2:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(directory.DELETED)) {
;
	ldx     #$00
	lda     _event
	cmp     #$4C
;
; break;
;
	beq     L04D3
;
; if (event.type == EVENT(directory.ERROR)) {
;
	cmp     #$48
	bne     L04D2
;
; return false;
;
	txa
	jmp     incsp4
;
; return true;
;
L04D3:	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ rename (__near__ const unsigned char *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rename: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; name = path_without_drive(name, &drive);
;
	jsr     decsp3
	ldy     #$08
	jsr     pushwysp
	lda     #$04
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$05
	jsr     staxysp
;
; if (drive >= MAX_DRIVES || strlen(name) > 255) return -1;
;
	ldy     #$02
	lda     (sp),y
	cmp     #$04
	bcs     L04D5
	ldy     #$06
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L039C
L04D5:	ldx     #$FF
	txa
	jmp     incsp7
;
; to = path_without_drive(to, &dest);
;
L039C:	ldy     #$06
	jsr     pushwysp
	lda     #$02
	jsr     leaa0sp
	jsr     _path_without_drive
	ldy     #$03
	jsr     staxysp
;
; if (dest >= MAX_DRIVES || dest != drive || strlen(to) > 255) {
;
	lda     (sp)
	cmp     #$04
	bcs     L04D6
	ldy     #$02
	cmp     (sp),y
	bne     L04D6
	ldy     #$04
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L03A5
;
; return -1;
;
L04D6:	ldx     #$FF
	txa
	jmp     incsp7
;
; args.file.delete.drive = drive;
;
L03A5:	ldy     #$02
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = name;
;
	ldy     #$06
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(name);
;
	ldy     #$06
	jsr     ldaxysp
	jsr     _strlen
	sta     _args+13
;
; args.common.ext = to;
;
	ldy     #$04
	jsr     ldaxysp
	sta     _args+8
	stx     _args+8+1
;
; args.common.extlen = strlen(to);
;
	ldy     #$04
	jsr     ldaxysp
	jsr     _strlen
	ldx     #$00
	sta     _args+10
;
; stream = CALL(File.Rename);
;
	jsr     _KernelCall_FF6C
	stz     _error
	ror     _error
	ldy     #$01
	sta     (sp),y
;
; if (error) {
;
	lda     _error
	beq     L03C8
;
; return -1;
;
	ldx     #$FF
	txa
	jmp     incsp7
;
; event.type = 0;
;
L03C8:	tax
L04D7:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(file.RENAMED)) {
;
	ldx     #$00
	lda     _event
	cmp     #$34
;
; break;
;
	beq     L04D8
;
; if (event.type == EVENT(file.ERROR)) {
;
	cmp     #$38
	bne     L04D7
;
; return -1;
;
	dex
	txa
	jmp     incsp7
;
; return 0;
;
L04D8:	txa
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ mkfs (__near__ const unsigned char *, const unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mkfs: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (drive >= MAX_DRIVES || strlen(name) > 255) return -1;
;
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	cmp     #$04
	bcs     L04D9
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$00
	txa
	sbc     #$01
	bcc     L03DC
L04D9:	ldx     #$FF
	txa
	jmp     incsp4
;
; args.file.delete.drive = drive;
;
L03DC:	ldy     #$01
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = name;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = strlen(name);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	ldx     #$00
	sta     _args+13
;
; stream = CALL(FileSystem.MkFS);
;
	jsr     _KernelCall_FF44
	stz     _error
	ror     _error
	ldy     #$00
	sta     (sp)
;
; if (error) {
;
	lda     _error
	beq     L03FA
;
; return -2;
;
	ldx     #$FF
	lda     #$FE
	jmp     incsp4
;
; event.type = 0;
;
L03FA:	tax
L04DA:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(fs.CREATED)) {
;
	ldx     #$00
	lda     _event
	cmp     #$1E
;
; break;
;
	beq     L04DB
;
; if (event.type == EVENT(fs.ERROR)) {
;
	cmp     #$26
	bne     L04DA
;
; return -3;
;
	dex
	lda     #$FD
	jmp     incsp4
;
; return 0;
;
L04DB:	txa
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Kernal_MkDir (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernal_MkDir: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; the_path += 2; // get past 0:, 1:, 2:, etc.
;
	jsr     decsp1
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
;
; args.directory.mkdir.drive = drive_num;
;
	ldy     #$01
	lda     (sp),y
	sta     _args+3
;
; args.common.buf = the_path;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = General_Strnlen(the_path, FILE_MAX_PATHNAME_SIZE);
;
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     #$FF
	jsr     _General_Strnlen
	ldx     #$00
	sta     _args+13
;
; stream = CALL(Directory.MkDir);
;
	jsr     _KernelCall_FF84
	stz     _error
	ror     _error
	ldy     #$00
	sta     (sp)
;
; if (error)
;
	lda     _error
	beq     L042B
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp4
;
; event.type = 0;
;
L042B:	tax
L04DC:	txa
	stz     _event
;
; asm("jsr %w", VECTOR(NextEvent));
;
	jsr     _KernelCall_FF00
;
; Keyboard_DeferBackgroundEvent();
;
	jsr     _Keyboard_DeferBackgroundEvent
;
; if (event.type == EVENT(directory.CREATED)) {
;
	ldx     #$00
	lda     _event
	cmp     #$4A
;
; break;
;
	beq     L04DD
;
; if (event.type == EVENT(directory.ERROR)) {
;
	cmp     #$48
	bne     L04DC
;
; return false;
;
	txa
	jmp     incsp4
;
; return true;
;
L04DD:	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ Kernal_RunNamed (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernal_RunNamed: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; args.common.buf = kup_name;
;
	jsr     decsp1
	ldy     #$03
	jsr     ldaxysp
	sta     _args+11
	stx     _args+11+1
;
; args.common.buflen = name_len;
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     _args+13
;
; stream = CALL(RunNamed);
;
	jsr     _KernelCall_FF18
	stz     _error
	ror     _error
	sta     (sp)
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Kernal_LoadApp (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Kernal_LoadApp: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (strlen(the_app_path) > MAX_PEXEC_APP_PATH_LEN ||
;
	jsr     decsp2
	ldy     #$05
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$3F
	txa
	sbc     #$00
	bcs     L04E4
;
; (the_file_path && strlen(the_file_path) > MAX_PEXEC_FILE_PATH_LEN)) return false;
;
	ldy     #$03
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0450
	iny
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$3F
	txa
	sbc     #$00
	ldx     #$00
	bcs     L04E6
	bra     L0450
L04E4:	ldx     #$00
L04E6:	txa
	jmp     incsp6
;
; args.common.buf = (char*)0x0200; // tell Kernel which buffer to work with
;
L0450:	ldx     #$02
	stz     _args+11
	stx     _args+11+1
;
; args.common.buflen = 2;
;
	stx     _args+13
;
; args.common.ext = (char*)0x0280; // tell Kernel where the arg pointers start and how many there are
;
	lda     #$80
	sta     _args+8
	stx     _args+8+1
;
; args.common.extlen = 6;    // if no file for called app to load. will change if necessary.
;
	lda     #$06
	sta     _args+10
;
; *(uint8_t*)0x0200 = '-';
;
	lda     #$2D
	sta     $0200
;
; *(uint8_t*)0x0201 = 0;
;
	stz     $0201
;
; *(uint8_t*)0x0280 = 0x00; // set pointer to arg0
;
	stz     $0280
;
; *(uint8_t*)0x0281 = 0x02; // first arg (pexec '-') is at $0200
;
	stx     $0281
;
; path_len = General_Strnlen(the_app_path, MAX_PEXEC_APP_PATH_LEN) + 1;
;
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	lda     #$3E
	jsr     _General_Strnlen
	ldy     #$01
	jsr     inceaxy
	sta     (sp)
;
; General_Strlcpy((char*)0x0202, the_app_path, path_len);
;
	ldx     #$02
	txa
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	jsr     _General_Strlcpy
;
; *(uint8_t*)0x0282 = 0x02; // set pointer to arg1
;
	lda     #$02
	sta     $0282
;
; *(uint8_t*)0x0283 = 0x02; // 2nd arg (the app path) is at $0202
;
	sta     $0283
;
; *(uint8_t*)0x0284 = 0x00;
;
	stz     $0284
;
; *(uint8_t*)0x0285 = 0x00; // terminator (will be overwritten if there is a file to load)
;
	ldx     #$00
	stz     $0285
;
; if (the_file_path != NULL)
;
	tay
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L0479
;
; path_len = General_Strnlen(the_file_path, MAX_PEXEC_FILE_PATH_LEN) + 1;
;
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     #$3E
	jsr     _General_Strnlen
	ldy     #$01
	jsr     inceaxy
	sta     (sp)
;
; General_Strlcpy((char*)0x0242, the_file_path, path_len);
;
	ldx     #$02
	lda     #$42
	jsr     pushax
	ldy     #$07
	jsr     pushwysp
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	jsr     _General_Strlcpy
;
; *(uint8_t*)0x0284 = 0x42; // set pointer to arg2
;
	lda     #$42
	sta     $0284
;
; *(uint8_t*)0x0285 = 0x02; // 3rd arg (the file path) is at $0242
;
	lda     #$02
	sta     $0285
;
; *(uint8_t*)0x0286 = 0x00;
;
	stz     $0286
;
; *(uint8_t*)0x0287 = 0x00; // terminator
;
	stz     $0287
;
; args.common.extlen = 8;  // let Kernel know we have 8 bytes / 4 pointers for it to look at.
;
	ldx     #$00
	lda     #$08
	sta     _args+10
;
; stream = CALL(RunNamed);
;
L0479:	jsr     _KernelCall_FF18
	stz     _error
	ror     _error
	ldy     #$01
	sta     (sp),y
;
; if (error)
;
	lda     _error
	beq     L049A
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp6
;
; return true; // just so cc65 is happy; but will not be hit in event of success as pexec will already be running.
;
L049A:	tax
	tya
;
; }
;
	jmp     incsp6

.endproc
