; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_Directory_SelectPanel
	.import		_global_file_bytes_loaded
	.import		_global_file_load_limit
	.import		_File_UpdatePos
	.import		_File_IsSelected
	.import		_File_ReadFontData
	.import		_File_LoadFileToEM
	.import		_File_CheckForFile
	.import		_File_Delete
	.import		_File_Rename
	.import		_File_Render
	.import		_File_CompareName
	.import		_App_ShowProgressBar
	.import		_App_HideProgressBar
	.import		_App_UpdateProgressBar
	.import		_App_EMDataCopy
	.import		_App_Exit
	.import		_App_LoadOverlay
	.import		_App_GetFilenameFromEM
	.import		_General_GetString
	.import		_General_Strlcpy
	.import		_General_Strnlen
	.import		_General_CreateFilePathFromFolderAndFile
	.import		_List_InitMergeSort
	.import		_fclose
	.import		_fwrite
	.import		_snprintf
	.import		_sprintf
	.import		_Folder_NewOrReset
	.import		_Folder_Destroy
	.import		_Folder_DestroyAllFiles
	.import		_Folder_SetCurrentRow
	.import		_Folder_GetCountFiles
	.import		_Folder_GetCurrentRow
	.import		_Folder_GetCurrentFile
	.import		_Folder_FindFileByRow
	.import		_Folder_CopyCurrentFile
	.import		_Folder_PopulateFiles
	.import		_Folder_SetFileSelectionByRow
	.import		_Folder_GetTargetHandleForWriting
	.import		_Bank_UpdatePos
	.import		_Bank_IsSelected
	.import		_Bank_Render
	.import		_MemSys_NewOrReset
	.import		_MemSys_Destroy
	.import		_MemSys_ResetAllBanks
	.import		_MemSys_GetCurrentRow
	.import		_MemSys_GetCurrentBankNum
	.import		_MemSys_PopulateBanks
	.import		_MemSys_SetBankSelectionByRow
	.import		_MemSys_ExecuteCurrentRow
	.import		_MemSys_BankIsWriteable
	.import		_MemSys_FillCurrentBank
	.import		_MemSys_ClearCurrentBank
	.export		_Panel_Initialize
	.export		_Panel_SwitchDevice
	.export		_Panel_SetCurrentDevice
	.export		_Panel_ToggleActiveState
	.export		_Panel_MakeDir
	.export		_Panel_FormatDrive
	.export		_Panel_Refresh
	.export		_Panel_RenameCurrentFile
	.export		_Panel_DeleteCurrentFile
	.export		_Panel_OpenCurrentFileOrFolder
	.export		_Panel_CopyCurrentFile
	.export		_Panel_ViewCurrentFile
	.export		_Panel_SelectPrevFile
	.export		_Panel_SelectNextFile
	.export		_Panel_SetFileSelectionByRow
	.export		_Panel_ReflowContent
	.export		_Panel_ClearDisplay
	.export		_Panel_RenderContents
	.export		_Panel_SortAndDisplay
	.export		_Panel_FillCurrentBank
	.export		_Panel_ClearCurrentBank
	.export		_Panel_SearchCurrentBank
	.export		_Panel_OpenMeatloafURL
	.import		_Buffer_NewMessage
	.import		_mkfs
	.import		_Kernal_MkDir
	.import		_Kernal_RunNamed
	.import		_Kernal_LoadApp
	.import		_Keyboard_GetChar
	.import		_Text_ScrollTextUp
	.import		_Text_ScrollTextDown
	.import		_Text_FillBox
	.import		_Text_SetXY
	.import		_Text_DrawStringAtXY
	.import		_Text_DisplayTextEntryDialog
	.import		_EM_DisplayAsText
	.import		_EM_DisplayAsHex
	.import		_EM_SearchMemory
	.import		_Screen_UpdateSortIcons
	.import		_Screen_UpdateMeatloafIcon
	.import		_Screen_DrawPanelHeader
	.import		_Screen_GetStringFromUser
	.import		_Screen_ShowUserTwoButtonDialog
	.import		_ScreenEvaluateUserStringForHexSeries
	.import		_strcmp
	.import		_strcpy
	.import		_memcpy
	.import		_global_named_app_basic
	.import		_global_string_buff1
	.import		_global_string_buff2
	.import		_global_temp_path_1
	.import		_global_temp_path_2
	.import		_global_find_next_enabled
	.import		_global_search_phrase
	.import		_global_search_phrase_human_readable
	.import		_global_search_phrase_len
	.import		_global_dlg
	.import		_global_dlg_title
	.import		_global_dlg_body_msg
	.import		_temp_screen_buffer_char
	.import		_temp_screen_buffer_attr
	.importzp	_zp_y_cnt
	.importzp	_zp_search_loc_byte
	.importzp	_zp_search_loc_page
	.importzp	_zp_search_loc_bank
	.export		_Panel_ReflowContentForDisk
	.export		_Panel_ReflowContentForMemory
	.export		_Panel_RenderTitleOnly

.segment	"RODATA"

L039F:
	.byte	$42,$61,$6E,$6B,$5F,$25,$30,$32,$58,$2E,$62,$69,$6E,$00
L0578:
	.byte	$46,$6C,$61,$73,$68,$00
L0628:
	.byte	$25,$75,$3A,$25,$73,$00
L023A	:=	L0628+0
L0570:
	.byte	$52,$41,$4D,$00
L00D6:
	.byte	$25,$64,$3A,$00
L02FE:
	.byte	$2E,$2E,$00
L01F1	:=	L02FE+0
L01C6	:=	L02FE+0
L01CB:
	.byte	$5E,$00
L01EE	:=	L02FE+1
L0303	:=	L01CB+0

; ---------------------------------------------------------------
; void __near__ Panel_Initialize (unsigned char, __near__ struct WB2KViewPanel *, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_Initialize: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (for_disk)
;
	ldy     #$04
	lda     (sp),y
	beq     L0091
;
; the_panel->memory_system_ = NULL;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_panel->sort_compare_function_ = (void*)&File_CompareName;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #<(_File_CompareName)
	ldy     #$0F
	sta     (ptr1),y
	iny
	lda     #>(_File_CompareName)
;
; else
;
	bra     L0636
;
; the_panel->root_folder_ = NULL;
;
L0091:	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; if (the_panel->memory_system_->is_flash_)
;
	ldy     #$06
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	beq     L009A
;
; the_panel->device_number_ = DEVICE_FLASH;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$09
;
; else
;
	bra     L063A
;
; the_panel->device_number_ = DEVICE_RAM;
;
L009A:	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$08
L063A:	ldy     #$0B
	sta     (ptr1),y
	iny
	lda     #$00
L0636:	sta     (ptr1),y
;
; the_panel->for_disk_ = for_disk;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (sp),y
	ldy     #$0E
	sta     (ptr1),y
;
; the_panel->id_ = the_panel_id;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$07
	lda     (sp),y
	ldy     #$04
	sta     (ptr1),y
;
; the_panel->x_ = x;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	ldy     #$05
	sta     (ptr1),y
;
; the_panel->y_ = y;
;
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$06
	sta     (ptr1),y
;
; the_panel->width_ = width;
;
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	ldy     #$07
	sta     (ptr1),y
;
; the_panel->height_ = height;
;
	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$08
	sta     (ptr1),y
;
; the_panel->content_top_ = 0;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
;
; the_panel->num_rows_ = 0;
;
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$09
	sta     (ptr1),y
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_SwitchDevice (__near__ struct WB2KViewPanel *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SwitchDevice: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; the_panel->device_number_ = the_device;
;
	jsr     decsp5
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	jsr     ldaxysp
	ldy     #$0B
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; was_disk = the_panel->for_disk_;
;
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	sta     (sp)
;
; if (the_device < DEVICE_MAX_DISK_DEVICE)
;
	ldy     #$06
	jsr     ldaxysp
	cmp     #$04
	txa
	sbc     #$00
	bvc     L00B9
	eor     #$80
L00B9:	bpl     L00B7
;
; the_panel->for_disk_ = true;
;
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
;
; else
;
	bra     L0643
;
; the_panel->for_disk_ = false;
;
L00B7:	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
L0643:	ldy     #$0E
	sta     (ptr1),y
;
; if ( was_disk == true && the_panel->for_disk_ == false)
;
	lda     (sp)
	cmp     #$01
	bne     L0645
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	bne     L0645
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; Folder_Destroy(&the_panel->root_folder_);
;
	ldy     #$08
	jsr     ldaxysp
	jsr     _Folder_Destroy
;
; else if ( was_disk == false && the_panel->for_disk_ == true)
;
	bra     L00C8
L0645:	lda     (sp)
	bne     L00C8
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L00C8
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; MemSys_Destroy(&the_panel->memory_system_);
;
	ldy     #$08
	jsr     ldaxysp
	jsr     incax2
	jsr     _MemSys_Destroy
;
; if (the_panel->for_disk_ == true)
;
L00C8:	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L00D0
;
; the_panel->sort_compare_function_ = (void*)&File_CompareName;
;
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #<(_File_CompareName)
	ldy     #$0F
	sta     (ptr1),y
	iny
	lda     #>(_File_CompareName)
	sta     (ptr1),y
;
; sprintf(path_buff, "%d:", the_device);
;
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L00D6)
	ldx     #>(L00D6)
	jsr     pushax
	ldy     #$0C
	jsr     pushwysp
	ldy     #$06
	jsr     _sprintf
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; if ( (the_panel->root_folder_ = Folder_NewOrReset(the_panel->root_folder_, the_device, path_buff)) == NULL)
;
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     ldaxysp
	jsr     pushw
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$07
	jsr     leaa0sp
	jsr     _Folder_NewOrReset
	ldy     #$00
	jsr     staxspidx
	cpx     #$00
	bne     L00F0
	cmp     #$00
	bne     L00F0
;
; App_Exit(ERROR_DEFINE_ME); // crash early, crash often
;
	dea
;
; else
;
	bra     L063C
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L00D0:	lda     #$0C
	jsr     _App_LoadOverlay
;
; if (the_device == DEVICE_RAM)
;
	ldy     #$06
	lda     (sp),y
	bne     L00E8
	dey
	lda     (sp),y
	cmp     #$08
	bne     L00E8
;
; for_flash = false;
;
	lda     #$00
;
; else
;
	bra     L0644
;
; for_flash = true;
;
L00E8:	lda     #$01
L0644:	ldy     #$01
	sta     (sp),y
;
; if ( (the_panel->memory_system_ = MemSys_NewOrReset(the_panel->memory_system_, for_flash)) == NULL)
;
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$03
	jsr     pushwidx
	ldy     #$05
	lda     (sp),y
	jsr     _MemSys_NewOrReset
	ldy     #$02
	jsr     staxspidx
	cpx     #$00
	bne     L00F0
	cmp     #$00
	bne     L00F0
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ALLOC_FAIL));
;
	lda     #$80
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; App_Exit(ERROR_COULD_NOT_CREATE_OR_RESET_MEMSYS_OBJ);
;
	lda     #$84
L063C:	jsr     _App_Exit
;
; Panel_Refresh(the_panel);
;
L00F0:	ldy     #$08
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_SetCurrentDevice (__near__ struct WB2KViewPanel *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SetCurrentDevice: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; the_panel->device_number_ = the_device_num;
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$0B
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_ToggleActiveState (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ToggleActiveState: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->active_ == true)
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	cmp     #$01
	bne     L0103
;
; the_panel->active_ = false;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
;
; else
;
	bra     L0647
;
; the_panel->active_ = true;
;
L0103:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
L0647:	ldy     #$0D
	sta     (ptr1),y
;
; Panel_RenderTitleOnly(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_RenderTitleOnly
;
; Panel_RenderContents(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_RenderContents
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_MakeDir (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_MakeDir: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; temp_dialog_width = global_dlg.width_ - 2;
;
	jsr     decsp4
	lda     _global_dlg+2
	sec
	sbc     #$02
	sta     (sp)
;
; current_path_len = General_Strnlen(the_panel->root_folder_->file_path_, FILE_MAX_PATHNAME_SIZE);
;
	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldx     #$00
	lda     #$FF
	jsr     _General_Strnlen
	ldy     #$02
	sta     (sp),y
;
; available_len = FILE_MAX_PATHNAME_SIZE - current_path_len - 1;
;
	lda     #$FF
	sec
	sbc     (sp),y
	sec
	sbc     #$01
	dey
	sta     (sp),y
;
; if (available_len > temp_dialog_width)
;
	sec
	sbc     (sp)
	bcc     L0119
	beq     L0119
;
; available_len = temp_dialog_width;
;
	lda     (sp)
	ldy     #$01
	sta     (sp),y
;
; General_Strlcpy((char*)&global_dlg_title, General_GetString(ID_STR_DLG_NEW_FOLDER_TITLE), 36);
;
L0119:	lda     #<(_global_dlg_title)
	ldx     #>(_global_dlg_title)
	jsr     pushax
	lda     #$16
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$24
	jsr     _General_Strlcpy
;
; General_Strlcpy((char*)&global_dlg_body_msg, General_GetString(ID_STR_DLG_ENTER_NEW_FOLDER_NAME), 70);
;
	lda     #<(_global_dlg_body_msg)
	ldx     #>(_global_dlg_body_msg)
	jsr     pushax
	lda     #$17
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$46
	jsr     _General_Strlcpy
;
; global_string_buff2[0] = 0; // clear whatever string had been in this buffer before
;
	lda     _global_string_buff2+1
	sta     ptr1+1
	lda     _global_string_buff2
	sta     ptr1
	lda     #$00
	sta     (ptr1)
;
; success = Text_DisplayTextEntryDialog(&global_dlg, (char*)&temp_screen_buffer_char, (char*)&temp_screen_buffer_attr, global_string_buff2, available_len, APP_ACCENT_COLOR, APP_FOREGROUND_COLOR, APP_BACKGROUND_COLOR);
;
	lda     #<(_global_dlg)
	ldx     #>(_global_dlg)
	jsr     pushax
	lda     #<(_temp_screen_buffer_char)
	ldx     #>(_temp_screen_buffer_char)
	jsr     pushax
	lda     #<(_temp_screen_buffer_attr)
	ldx     #>(_temp_screen_buffer_attr)
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     _Text_DisplayTextEntryDialog
	ldy     #$03
	sta     (sp),y
;
; if (success == false)
;
	lda     (sp),y
	bne     L0134
;
; return false;
;
	tax
	jmp     incsp6
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, global_string_buff2)) return false;
;
L0134:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     incsp6
;
; success = Kernal_MkDir(global_temp_path_1, the_panel->device_number_);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     _Kernal_MkDir
	ldy     #$03
	sta     (sp),y
;
; if (success == false)
;
	lda     (sp),y
	bne     L0141
;
; return false;
;
	tax
	jmp     incsp6
;
; Panel_Refresh(the_panel);
;
L0141:	ldy     #$05
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; return success;
;
	ldy     #$03
	ldx     #$00
	lda     (sp),y
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_FormatDrive (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_FormatDrive: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	jsr     decsp1
	lda     #$08
	jsr     _App_LoadOverlay
;
; General_GetString(ID_STR_DLG_FORMAT_TITLE),
;
	lda     #$06
	jsr     _General_GetString
	jsr     pushax
;
; ID_STR_DLG_ARE_YOU_SURE,
;
	lda     #$01
	jsr     pusha
;
; ID_STR_DLG_YES,
;
	lda     #$07
	jsr     pusha
;
; ) != 1)
;
	ina
	jsr     _Screen_ShowUserTwoButtonDialog
	cmp     #$01
	beq     L014A
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp3
;
; General_Strlcpy(global_string_buff1, General_GetString(ID_STR_DLG_ENTER_NEW_NAME), 70);
;
L014A:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$0B
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$46
	jsr     _General_Strlcpy
;
; *global_string_buff2 = 0;
;
	lda     _global_string_buff2+1
	sta     ptr1+1
	lda     _global_string_buff2
	sta     ptr1
	lda     #$00
	sta     (ptr1)
;
; if (Screen_GetStringFromUser(General_GetString(ID_STR_DLG_FORMAT_TITLE), global_string_buff1, global_string_buff2, FILE_MAX_FILENAME_SIZE - 1) == NULL) return false;
;
	lda     #$06
	jsr     _General_GetString
	jsr     pushax
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$1F
	jsr     _Screen_GetStringFromUser
	cpx     #$00
	bne     L0159
	cmp     #$00
	jeq     incsp3
;
; if (global_string_buff2 == NULL)
;
L0159:	lda     _global_string_buff2
	ora     _global_string_buff2+1
	bne     L0163
;
; return false;
;
	tax
	jmp     incsp3
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_FORMATTING));
;
L0163:	lda     #$45
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; if ( (result_code = mkfs(global_string_buff2, the_panel->device_number_)) < 0)
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     _mkfs
	cmp     #$80
	sta     (sp)
	asl     a
	bcc     L016A
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_GENERIC_DISK));
;
	lda     #$73
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp3
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_DONE));
;
L016A:	lda     #$4B
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_Refresh (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_Refresh: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel == NULL)
;
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0648
;
; App_Exit(ERROR_PANEL_WAS_NULL); // crash early, crash often
;
	lda     #$66
	jsr     _App_Exit
;
; the_panel->content_top_ = 0;
;
	ldy     #$02
L0648:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0181
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_READING_DIR));
;
	lda     #$48
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; Folder_DestroyAllFiles(the_panel->root_folder_);
;
	ldy     #$02
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_DestroyAllFiles
;
; if ( (the_error_code = Folder_PopulateFiles(the_panel->id_, the_panel->root_folder_)) > ERROR_NO_ERROR)
;
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_PopulateFiles
	sta     (sp)
	cmp     #$00
	beq     L0193
;
; Panel_SortAndDisplay(the_panel);
;
	ldy     #$02
	jsr     ldaxysp
	jsr     _Panel_SortAndDisplay
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp3
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0181:	lda     #$0C
	jsr     _App_LoadOverlay
;
; MemSys_ResetAllBanks(the_panel->memory_system_);
;
	ldy     #$02
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_ResetAllBanks
;
; MemSys_PopulateBanks(the_panel->memory_system_);
;
	ldy     #$02
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_PopulateBanks
;
; Panel_SortAndDisplay(the_panel);
;
L0193:	ldy     #$02
	jsr     ldaxysp
	jsr     _Panel_SortAndDisplay
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_RenameCurrentFile (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_RenameCurrentFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	jsr     decsp5
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_file = Folder_GetCurrentFile(the_panel->root_folder_);
;
	ldy     #$06
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentFile
	ldy     #$03
	jsr     staxysp
;
; if (the_file == NULL)
;
	cpx     #$00
	bne     L01BD
	cmp     #$00
;
; return false;
;
	jeq     incsp7
;
; if (the_file == NULL || strcmp(App_GetFilenameFromEM(the_file), "..") == 0 ||
;
L01BD:	ldy     #$03
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L01C2
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	lda     #<(L01C6)
	ldx     #>(L01C6)
	jsr     _strcmp
	cpx     #$00
	bne     L064E
	cmp     #$00
	beq     L0650
;
; strcmp(App_GetFilenameFromEM(the_file), "^") == 0) return false;
;
L064E:	ldy     #$04
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	lda     #<(L01CB)
	ldx     #>(L01CB)
	jsr     _strcmp
	cpx     #$00
	bne     L01C1
	cmp     #$00
	beq     L0650
	bra     L01C1
L01C2:	tax
L0650:	jmp     incsp7
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_DLG_RENAME_TITLE), App_GetFilenameFromEM(the_file));
;
L01C1:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$02
	jsr     _General_GetString
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldy     #$08
	jsr     _snprintf
;
; General_Strlcpy(global_string_buff2, App_GetFilenameFromEM(the_file), FILE_MAX_FILENAME_SIZE);
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	ldy     #$06
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_Strlcpy
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; new_file_name = Screen_GetStringFromUser(global_string_buff1, General_GetString(ID_STR_DLG_ENTER_NEW_NAME), global_string_buff2, FILE_MAX_FILENAME_SIZE - 1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$0B
	jsr     _General_GetString
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$1F
	jsr     _Screen_GetStringFromUser
	jsr     stax0sp
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; if (new_file_name && (!strcmp(new_file_name, ".") || !strcmp(new_file_name, ".."))) return false;
;
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	beq     L0652
	jsr     pushw0sp
	lda     #<(L01EE)
	ldx     #>(L01EE)
	jsr     _strcmp
	stx     tmp1
	ora     tmp1
	beq     L01EC
	jsr     pushw0sp
	lda     #<(L01F1)
	ldx     #>(L01F1)
	jsr     _strcmp
	stx     tmp1
	ora     tmp1
	bne     L0652
L01EC:	tax
	jmp     incsp7
;
; if (new_file_name == NULL)
;
L0652:	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L01F6
;
; return false;
;
	tax
	jmp     incsp7
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, App_GetFilenameFromEM(the_file))) return false;
;
L01F6:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$08
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     incsp7
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_2, the_panel->root_folder_->file_path_, global_string_buff2)) return false;
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     incsp7
;
; strcpy(global_string_buff1, global_string_buff2); // get a copy of the filename because it won't be available after rename
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     _strcpy
;
; success = File_Rename(the_file, global_string_buff2, global_temp_path_1, global_temp_path_2);
;
	ldy     #$06
	jsr     pushwysp
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     _File_Rename
	ldy     #$02
	sta     (sp),y
;
; if (success == false)
;
	lda     (sp),y
	bne     L0210
;
; return false;
;
	tax
	jmp     incsp7
;
; Panel_RenderContents(the_panel);
;
L0210:	ldy     #$06
	jsr     ldaxysp
	jsr     _Panel_RenderContents
;
; return success;
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_DeleteCurrentFile (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_DeleteCurrentFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; char*    delete_file_name = delete_file_name_buff;
;
	ldy     #$25
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_current_row = Folder_GetCurrentRow(the_panel->root_folder_);
;
	ldy     #$28
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentRow
	ldy     #$23
	jsr     staxysp
;
; if (the_current_row < 0)
;
	cpx     #$80
	bcc     L02F2
;
; return false;
;
	ldx     #$00
	txa
	jmp     L02E9
;
; the_file = Folder_FindFileByRow(the_panel->root_folder_, the_current_row);
;
L02F2:	ldy     #$28
	jsr     ldaxysp
	jsr     pushw
	ldy     #$25
	lda     (sp),y
	jsr     _Folder_FindFileByRow
	ldy     #$25
	jsr     staxysp
;
; if (the_file == NULL || strcmp(App_GetFilenameFromEM(the_file), "..") == 0 ||
;
	cpx     #$00
	bne     L0654
	cmp     #$00
	jeq     L02E9
L0654:	ldy     #$26
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	lda     #<(L02FE)
	ldx     #>(L02FE)
	jsr     _strcmp
	cpx     #$00
	bne     L0655
	cmp     #$00
	jeq     L02E9
;
; strcmp(App_GetFilenameFromEM(the_file), "^") == 0) return false;
;
L0655:	ldy     #$26
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	lda     #<(L0303)
	ldx     #>(L0303)
	jsr     _strcmp
	cpx     #$00
	bne     L02F9
	cmp     #$00
	jeq     L02E9
;
; strcpy(delete_file_name, App_GetFilenameFromEM(the_file));
;
L02F9:	jsr     pushw0sp
	ldy     #$28
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     _strcpy
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_DLG_DELETE_TITLE), delete_file_name);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$05
	jsr     _General_GetString
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; global_string_buff1,
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
;
; ID_STR_DLG_ARE_YOU_SURE,
;
	lda     #$01
	jsr     pusha
;
; ID_STR_DLG_YES,
;
	lda     #$07
	jsr     pusha
;
; ) != 1)
;
	ina
	jsr     _Screen_ShowUserTwoButtonDialog
	cmp     #$01
	beq     L0314
;
; return false;
;
	ldx     #$00
	txa
	jmp     L02E9
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
L0314:	lda     #$09
	jsr     _App_LoadOverlay
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, App_GetFilenameFromEM(the_file))) return false;
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$2A
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$2A
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     L02E9
;
; success = File_Delete(global_temp_path_1, the_file->is_directory_);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$28
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	jsr     _File_Delete
	ldy     #$22
	sta     (sp),y
;
; if (success == false)
;
	lda     (sp),y
	bne     L0328
;
; if (the_file->is_directory_)
;
	ldy     #$26
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L032A
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_DELETE_DIR_FAILURE));
;
	lda     #$6F
;
; else
;
	bra     L0657
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_DELETE_FILE_FAILURE));
;
L032A:	lda     #$6E
L0657:	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	bra     L02E9
;
; Panel_Refresh(the_panel);
;
L0328:	ldy     #$28
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; if (the_current_row >= the_panel->root_folder_->file_count_)
;
	ldy     #$26
	jsr     pushwysp
	ldy     #$2A
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$07
	jsr     ldaxidx
	jsr     tosicmp
	bcc     L0336
;
; the_current_row = the_panel->root_folder_->file_count_ - 1;
;
	ldy     #$28
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$07
	jsr     ldaxidx
	jsr     decax1
	ldy     #$23
	jsr     staxysp
;
; if (the_current_row >= 0) Panel_SetFileSelectionByRow(the_panel, the_current_row, true);
;
L0336:	ldy     #$24
	jsr     ldaxysp
	txa
	bmi     L033A
	ldy     #$2A
	jsr     pushwysp
	ldy     #$28
	jsr     pushwysp
	lda     #$01
	jsr     _Panel_SetFileSelectionByRow
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_DELETE_SUCCESS), delete_file_name);
;
L033A:	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$49
	jsr     _General_GetString
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; return success;
;
	ldy     #$22
	ldx     #$00
	lda     (sp),y
;
; }
;
L02E9:	ldy     #$29
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_OpenCurrentFileOrFolder (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_OpenCurrentFileOrFolder: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == true)
;
	jsr     decsp3
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	jne     L0217
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_file = Folder_GetCurrentFile(the_panel->root_folder_);
;
	ldy     #$04
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentFile
	ldy     #$01
	jsr     staxysp
;
; if (the_file == NULL)
;
	cpx     #$00
	bne     L021E
	cmp     #$00
;
; return false;
;
	jeq     incsp5
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, App_GetFilenameFromEM(the_file))) return false;
;
L021E:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$06
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$06
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     incsp5
;
; if (the_file->file_type_ == _CBM_T_DIR)
;
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$02
	jne     L0229
;
; if (the_panel->root_folder_->is_meatloaf_ == false)
;
	ldy     #$04
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	bne     L022B
;
; if ( (the_panel->root_folder_ = Folder_NewOrReset(the_panel->root_folder_, the_panel->device_number_, global_temp_path_1)) == NULL )
;
	ldy     #$06
	jsr     pushwysp
	ldy     #$06
	jsr     ldaxysp
	jsr     pushw
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Folder_NewOrReset
	ldy     #$00
	jsr     staxspidx
	cpx     #$00
	bne     L0237
	cmp     #$00
	bne     L0237
;
; App_Exit(ERROR_DEFINE_ME); // crash early, crash often
;
	dea
	jsr     _App_Exit
;
; else
;
	bra     L0237
;
; sprintf(global_temp_path_1, "%u:%s", the_panel->root_folder_->device_number_, App_GetFilenameFromEM(the_file));
;
L022B:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     #<(L023A)
	ldx     #>(L023A)
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$08
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
;
; success = File_LoadFileToEM(global_temp_path_1, EM_STORAGE_START_PHYS_BANK_NUM);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     #$14
	jsr     _File_LoadFileToEM
	sta     (sp)
;
; Panel_Refresh(the_panel);
;
L0237:	ldy     #$04
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; success = true;
;
	lda     #$01
;
; else if (the_file->file_type_ == FNX_FILETYPE_FONT)
;
	jmp     L065E
L0229:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$C8
	bne     L0248
;
; success = File_ReadFontData(global_temp_path_1);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _File_ReadFontData
;
; else if (the_file->file_type_ == FNX_FILETYPE_EXE || the_file->file_type_ == FNX_FILETYPE_IMAGE)
;
	jmp     L065E
L0248:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$C9
	beq     L065A
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$CC
	bne     L024E
;
; success = Kernal_LoadApp(global_temp_path_1, NULL);
;
L065A:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Kernal_LoadApp
;
; else if (the_file->file_type_ == FNX_FILETYPE_MUSIC)
;
	jmp     L065E
L024E:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$CB
	bne     L0256
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_MOD_PLAYER), FILE_MAX_PATHNAME_SIZE);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$58
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_MOD_PLAYER) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7C
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L025E
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	jmp     L065E
;
; success = false;
;
L025E:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_MIDI)
;
	jmp     L065E
L0256:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$CE
	bne     L026A
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_MIDI_PLAYER), FILE_MAX_PATHNAME_SIZE);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$57
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_MIDI_PLAYER) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7B
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L0272
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	jmp     L065E
;
; success = false;
;
L0272:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_VGM)
;
	jmp     L065E
L026A:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$D2
	bne     L027E
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_VGM_PLAYER), FILE_MAX_PATHNAME_SIZE);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$5A
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_VGM_PLAYER) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7E
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L0286
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	jmp     L065E
;
; success = false;
;
L0286:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_RSD)
;
	jmp     L065E
L027E:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$D3
	bne     L0292
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_RSD_PLAYER), FILE_MAX_PATHNAME_SIZE);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$5B
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_RSD_PLAYER) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7F
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L029A
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	jmp     L065E
;
; success = false;
;
L029A:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_MP3 || the_file->file_type_ == FNX_FILETYPE_OGG || the_file->file_type_ == FNX_FILETYPE_WAV)
;
	jmp     L065E
L0292:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$CF
	beq     L065B
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$D0
	beq     L065B
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$D1
	bne     L02A6
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_AUDIO_PLAYER), FILE_MAX_PATHNAME_SIZE);
;
L065B:	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$59
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_AUDIO_PLAYER) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7D
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L02AF
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	jmp     L065E
;
; success = false;
;
L02AF:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_TEXT)
;
	jmp     L065E
L02A6:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$CD
	bne     L02BB
;
; General_Strlcpy(global_temp_path_2, General_GetString(ID_STR_APP_PATH_TEXT_EDITOR), FILE_MAX_PATHNAME_SIZE);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$56
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$FF
	jsr     _General_Strlcpy
;
; if (File_CheckForFile(global_temp_path_2, ID_STR_ERROR_NO_TEXT_EDITOR) == true)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     #$7A
	jsr     _File_CheckForFile
	cmp     #$01
	bne     L02C3
;
; success = Kernal_LoadApp(global_temp_path_2, global_temp_path_1);
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     _Kernal_LoadApp
;
; else
;
	bra     L065E
;
; success = false;
;
L02C3:	lda     #$00
;
; else if (the_file->file_type_ == FNX_FILETYPE_BASIC)
;
	bra     L065E
L02BB:	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	ldx     #$00
	lda     (ptr1),y
	cmp     #$CA
	bne     L065C
;
; success = File_LoadFileToEM(global_temp_path_1, EM_STORAGE_START_PHYS_BANK_NUM);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     #$14
	jsr     _File_LoadFileToEM
	sta     (sp)
;
; if (success)
;
	lda     (sp)
	beq     L065D
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_BASIC_LOAD_INSTRUCTIONS));
;
	lda     #$53
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; Keyboard_GetChar();
;
	jsr     _Keyboard_GetChar
;
; Kernal_RunNamed(global_named_app_basic, 5); // this will only ever return in an error condition.
;
	lda     _global_named_app_basic
	ldx     _global_named_app_basic+1
	jsr     pushax
	lda     #$05
	jsr     _Kernal_RunNamed
;
; success = false;
;
	lda     #$00
;
; else
;
	bra     L065E
;
; return false;
;
L065C:	txa
	jmp     incsp5
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0217:	lda     #$0C
	jsr     _App_LoadOverlay
;
; success = MemSys_ExecuteCurrentRow(the_panel->memory_system_);
;
	ldy     #$04
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_ExecuteCurrentRow
L065E:	sta     (sp)
;
; return success;
;
L065D:	ldx     #$00
	lda     (sp)
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_CopyCurrentFile (__near__ struct WB2KViewPanel *, __near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_CopyCurrentFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; bool    success = false;
;
	jsr     decsp7
	lda     #$00
	jsr     pusha
;
; uint8_t*   the_buffer = (uint8_t*)STORAGE_FILE_BUFFER_1;
;
	jsr     decsp6
	ldx     #$05
	lda     #$00
	jsr     pushax
;
; if (the_panel->for_disk_ == false)
;
	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	bne     L034C
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; src_bank_num = MemSys_GetCurrentBankNum(the_panel->memory_system_);
;
	ldy     #$13
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentBankNum
	ldy     #$0E
	sta     (sp),y
;
; if (the_other_panel->for_disk_ == false)
;
L034C:	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	bne     L0353
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; if (!MemSys_BankIsWriteable(the_other_panel->memory_system_)) {
;
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_BankIsWriteable
	tax
	bne     L0357
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_TO_OVERWRITE_FM_RAM));
;
	lda     #$79
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     L0349
;
; dst_bank_num = MemSys_GetCurrentBankNum(the_other_panel->memory_system_);
;
L0357:	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentBankNum
	ldy     #$0D
	sta     (sp),y
;
; if (the_panel->for_disk_ == true && the_other_panel->for_disk_ == true)
;
L0353:	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0361
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0361
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; success = Folder_CopyCurrentFile(the_panel->root_folder_, the_other_panel->root_folder_);
;
	ldy     #$13
	jsr     ldaxysp
	jsr     pushw
	ldy     #$13
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_CopyCurrentFile
	ldy     #$08
	sta     (sp),y
;
; if (success)
;
	lda     (sp),y
	beq     L036B
;
; Buffer_NewMessage(General_GetString(ID_STR_MSG_DONE));
;
	lda     #$4B
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; else
;
	jmp     L03E7
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_GENERIC_DISK));
;
L036B:	lda     #$73
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; else if (the_panel->for_disk_ == true && the_other_panel->for_disk_ == false)
;
	jmp     L03E7
L0361:	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	jne     L0375
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jne     L0375
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_file = Folder_GetCurrentFile(the_panel->root_folder_);
;
	ldy     #$13
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentFile
	ldy     #$04
	jsr     staxysp
;
; if (the_file == NULL || the_file->is_directory_) return false;
;
	cpx     #$00
	bne     L0672
	cmp     #$00
	jeq     L0349
L0672:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L037E
	ldx     #$00
	txa
	jmp     L0349
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, App_GetFilenameFromEM(the_file))) return false;
;
L037E:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$15
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$09
	jsr     ldaxysp
	jsr     _App_GetFilenameFromEM
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     L0349
;
; global_file_load_limit = 8192;
;
	ldx     #$20
	stz     _global_file_load_limit
	stx     _global_file_load_limit+1
;
; success = File_LoadFileToEM(global_temp_path_1, dst_bank_num);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$0F
	lda     (sp),y
	jsr     _File_LoadFileToEM
	ldy     #$08
	sta     (sp),y
;
; global_file_load_limit = 255U * 256U;
;
	ldx     #$FF
	stz     _global_file_load_limit
	stx     _global_file_load_limit+1
;
; else if (the_panel->for_disk_ == false && the_other_panel->for_disk_ == true)
;
	jmp     L03E7
L0375:	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jne     L0393
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	jne     L0393
;
; General_Strlcpy(global_string_buff1, General_GetString(ID_STR_DLG_COPY_TO_FILE_TITLE), 70);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$03
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$46
	jsr     _General_Strlcpy
;
; snprintf(global_string_buff2, STORAGE_STRING_BUFFER_2_LEN, "Bank_%02X.bin", src_bank_num);
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #<(L039F)
	ldx     #>(L039F)
	jsr     pushax
	ldy     #$14
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	jsr     _snprintf
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; the_name = Screen_GetStringFromUser(global_string_buff1, General_GetString(ID_STR_DLG_ENTER_FILE_NAME), global_string_buff2, FILE_MAX_FILENAME_SIZE - 1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$04
	jsr     _General_GetString
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$1F
	jsr     _Screen_GetStringFromUser
	ldy     #$02
	jsr     staxysp
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; if (the_name == NULL)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L03AE
;
; return false;
;
	tax
	jmp     L0349
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_2, the_other_panel->root_folder_->file_path_, the_name)) return false;
;
L03AE:	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     pushax
	ldy     #$13
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$07
	jsr     ldaxysp
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     L0349
;
; if ( (the_target_handle = Folder_GetTargetHandleForWriting(global_temp_path_2)) == NULL)
;
	lda     _global_temp_path_2
	ldx     _global_temp_path_2+1
	jsr     _Folder_GetTargetHandleForWriting
	ldy     #$06
	jsr     staxysp
	cpx     #$00
	bne     L03B8
	cmp     #$00
;
; return false;
;
	jeq     L0349
;
; App_ShowProgressBar();
;
L03B8:	jsr     _App_ShowProgressBar
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
	lda     #$00
	ldy     #$0F
L0675:	sta     (sp),y
	cmp     #$20
	bcs     L03C1
;
; App_EMDataCopy(the_buffer, src_bank_num, i, PARAM_COPY_FROM_EM);
;
	jsr     pushw0sp
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$12
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; if (fwrite(the_buffer, 1, STORAGE_FILE_BUFFER_1_LEN, the_target_handle) != STORAGE_FILE_BUFFER_1_LEN) {
;
	jsr     pushw0sp
	lda     #$01
	jsr     pusha0
	tax
	dea
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     _fwrite
	cpx     #$01
	bne     L0673
	cmp     #$00
	beq     L03CD
;
; fclose(the_target_handle);
;
L0673:	ldy     #$07
	jsr     ldaxysp
	jsr     _fclose
;
; App_HideProgressBar();
;
	jsr     _App_HideProgressBar
;
; return false;
;
	ldx     #$00
	txa
	jmp     L0349
;
; percent_read = ((uint32_t)i * 100) / (uint32_t)PAGES_PER_BANK;
;
L03CD:	ldy     #$0F
	dex
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     #$64
	jsr     tosumul0ax
	jsr     shreax4
	jsr     shreax1
	ldy     #$09
	jsr     steaxysp
;
; App_UpdateProgressBar((uint8_t)percent_read);
;
	ldy     #$09
	lda     (sp),y
	jsr     _App_UpdateProgressBar
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
	ldy     #$0F
	lda     (sp),y
	ina
	bra     L0675
;
; if (fclose(the_target_handle) != 0) { App_HideProgressBar(); return false; }
;
L03C1:	ldy     #$07
	jsr     ldaxysp
	jsr     _fclose
	cpx     #$00
	bne     L0674
	cmp     #$00
	beq     L03DD
L0674:	jsr     _App_HideProgressBar
	ldx     #$00
	txa
	jmp     L0349
;
; App_HideProgressBar();
;
L03DD:	jsr     _App_HideProgressBar
;
; else if (the_panel->for_disk_ == false && the_other_panel->for_disk_ == false)
;
	jmp     L0671
L0393:	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jne     L03E7
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	bne     L03E7
;
; if (src_bank_num == dst_bank_num)
;
	lda     (sp),y
	dey
	cmp     (sp),y
	bne     L03EB
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_COPY_BANK_TO_ITSELF));
;
	lda     #$78
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     L0349
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L03EB:	lda     #$0C
	jsr     _App_LoadOverlay
;
; if (MemSys_BankIsWriteable(the_other_panel->memory_system_) == false)
;
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_BankIsWriteable
	cmp     #$00
	bne     L03F3
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_TO_OVERWRITE_FM_RAM));
;
	lda     #$79
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	bra     L0349
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
L03F3:	lda     #$00
	ldy     #$0F
L0677:	sta     (sp),y
	cmp     #$20
	bcs     L0671
;
; App_EMDataCopy(the_buffer, src_bank_num, i, PARAM_COPY_FROM_EM);
;
	jsr     pushw0sp
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$12
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; App_EMDataCopy(the_buffer, dst_bank_num, i, PARAM_COPY_TO_EM);
;
	jsr     pushw0sp
	ldy     #$0F
	lda     (sp),y
	jsr     pusha
	ldy     #$12
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _App_EMDataCopy
;
; for (i = 0; i < PAGES_PER_BANK; i++)
;
	ldy     #$0F
	lda     (sp),y
	ina
	bra     L0677
;
; success = true;
;
L0671:	lda     #$01
	ldy     #$08
	sta     (sp),y
;
; Panel_Refresh(the_other_panel);
;
L03E7:	ldy     #$11
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; if (the_other_panel == the_panel)
;
	ldy     #$11
	jsr     ldaxysp
	ldy     #$12
	cmp     (sp),y
	bne     L0410
	txa
	iny
	cmp     (sp),y
	bne     L0410
;
; Panel_Refresh(the_panel);
;
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; return success;
;
L0410:	ldy     #$08
	ldx     #$00
	lda     (sp),y
;
; }
;
L0349:	ldy     #$14
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_ViewCurrentFile (__near__ struct WB2KViewPanel *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ViewCurrentFile: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$09
	jsr     subysp
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0416
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_current_row = Folder_GetCurrentRow(the_panel->root_folder_);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentRow
;
; else
;
	bra     L067C
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0416:	lda     #$0C
	jsr     _App_LoadOverlay
;
; the_current_row = MemSys_GetCurrentRow(the_panel->memory_system_);
;
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentRow
L067C:	ldy     #$07
	jsr     staxysp
;
; if (the_current_row < 0)
;
	cpx     #$80
	bcc     L0423
;
; return false;
;
	ldx     #$00
	txa
	jmp     L0415
;
; if (the_panel->for_disk_ == true)
;
L0423:	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0426
;
; the_file = Folder_FindFileByRow(the_panel->root_folder_, the_current_row);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushw
	ldy     #$09
	lda     (sp),y
	jsr     _Folder_FindFileByRow
	ldy     #$03
	jsr     staxysp
;
; the_name = App_GetFilenameFromEM(the_file);
;
	jsr     _App_GetFilenameFromEM
	jsr     stax0sp
;
; if (!General_CreateFilePathFromFolderAndFile(global_temp_path_1, the_panel->root_folder_->file_path_, the_name)) return false;
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
	jsr     pushwidx
	ldy     #$05
	jsr     ldaxysp
	jsr     _General_CreateFilePathFromFolderAndFile
	tax
	jeq     L0415
;
; num_pages = 0;
;
	lda     #$00
	ldy     #$06
	sta     (sp),y
;
; bank_num = EM_STORAGE_START_PHYS_BANK_NUM;
;
	lda     #$14
	dey
	sta     (sp),y
;
; success = File_LoadFileToEM(global_temp_path_1, bank_num);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     _File_LoadFileToEM
	ldy     #$02
	sta     (sp),y
;
; num_pages = ((uint32_t)global_file_bytes_loaded + 255U) / 256;
;
	lda     _global_file_bytes_loaded
	ldx     _global_file_bytes_loaded+1
	jsr     axulong
	ldy     #$FF
	jsr     inceaxy
	txa
	ldy     #$06
;
; else
;
	bra     L067B
;
; the_name = the_panel->memory_system_->bank_[the_current_row].name_;
;
L0426:	ldy     #$0B
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	ina
	bne     L0443
	inx
L0443:	jsr     pushax
	ldy     #$0C
	jsr     pushwysp
	lda     #$0E
	jsr     tosmula0
	jsr     tosaddax
	ldy     #$0B
	jsr     ldaxidx
	jsr     stax0sp
;
; num_pages = PAGES_PER_BANK; // 32 pages per bank (8192/256=32)
;
	lda     #$20
	ldy     #$06
	sta     (sp),y
;
; bank_num = the_panel->memory_system_->bank_[the_current_row].bank_num_;
;
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	ina
	bne     L0449
	inx
L0449:	jsr     pushax
	ldy     #$0C
	jsr     pushwysp
	lda     #$0E
	jsr     tosmula0
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ldy     #$05
	sta     (sp),y
;
; success = true;
;
	lda     #$01
	ldy     #$02
L067B:	sta     (sp),y
;
; if (success)
;
	ldy     #$02
	lda     (sp),y
	beq     L044D
;
; App_LoadOverlay(OVERLAY_EM);
;
	lda     #$0A
	jsr     _App_LoadOverlay
;
; if (the_viewer_type == PARAM_VIEW_AS_HEX)
;
	ldy     #$09
	lda     (sp),y
	bne     L0451
;
; EM_DisplayAsHex(bank_num, num_pages, the_name);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     _EM_DisplayAsHex
;
; else
;
	bra     L045C
;
; EM_DisplayAsText(bank_num, num_pages, the_name);
;
L0451:	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     _EM_DisplayAsText
;
; else
;
	bra     L045C
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_FAIL_VIEW_FILE));
;
L044D:	lda     #$75
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return success;
;
L045C:	ldy     #$02
	ldx     #$00
	lda     (sp),y
;
; }
;
L0415:	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_SelectPrevFile (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SelectPrevFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == true)
;
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0462
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_current_row = Folder_GetCurrentRow(the_panel->root_folder_);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentRow
;
; else
;
	bra     L067E
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0462:	lda     #$0C
	jsr     _App_LoadOverlay
;
; the_current_row = MemSys_GetCurrentRow(the_panel->memory_system_);
;
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentRow
L067E:	jsr     stax0sp
;
; if (--the_current_row < 0)
;
	ldx     #$00
	lda     #$01
	jsr     subeq0sp
	cpx     #$80
	bcc     L046F
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp4
;
; return Panel_SetFileSelectionByRow(the_panel, the_current_row, true);
;
L046F:	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     pushwysp
	lda     #$01
	jsr     _Panel_SetFileSelectionByRow
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_SelectNextFile (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SelectNextFile: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == true)
;
	jsr     decsp4
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0477
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_current_row = Folder_GetCurrentRow(the_panel->root_folder_);
;
	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCurrentRow
	ldy     #$02
	jsr     staxysp
;
; the_item_count = Folder_GetCountFiles(the_panel->root_folder_);
;
	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCountFiles
;
; else
;
	bra     L0681
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0477:	lda     #$0C
	jsr     _App_LoadOverlay
;
; the_current_row = MemSys_GetCurrentRow(the_panel->memory_system_);
;
	ldy     #$05
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentRow
	ldy     #$02
	jsr     staxysp
;
; the_item_count = MEMORY_BANK_COUNT;
;
	ldx     #$00
	lda     #$40
L0681:	jsr     stax0sp
;
; if (++the_current_row == the_item_count)
;
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	cmp     (sp)
	bne     L0489
	txa
	ldy     #$01
	cmp     (sp),y
	bne     L0489
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp6
;
; return Panel_SetFileSelectionByRow(the_panel, the_current_row, true);
;
L0489:	ldy     #$07
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	lda     #$01
	jsr     _Panel_SetFileSelectionByRow
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_SetFileSelectionByRow (__near__ struct WB2KViewPanel *, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SetFileSelectionByRow: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; bool    scroll_needed = false;
;
	lda     #$00
	jsr     pusha
;
; uint8_t    content_top = the_panel->content_top_;
;
	jsr     decsp1
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	jsr     pusha
;
; if (the_panel == NULL)
;
	jsr     decsp4
	ldy     #$0A
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0684
;
; App_Exit(ERROR_SET_FILE_SEL_BY_ROW_PANEL_WAS_NULL); // crash early, crash often
;
	lda     #$75
	jsr     _App_Exit
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$0B
L0684:	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L0498
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_file = Folder_SetFileSelectionByRow(the_panel->root_folder_, the_row, do_selection, the_panel->y_);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushw
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     _Folder_SetFileSelectionByRow
	ldy     #$02
;
; else
;
	bra     L068C
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L0498:	lda     #$0C
	jsr     _App_LoadOverlay
;
; the_bank = MemSys_SetBankSelectionByRow(the_panel->memory_system_, the_row, do_selection, the_panel->y_, the_panel->active_);
;
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$03
	jsr     pushwidx
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _MemSys_SetBankSelectionByRow
	ldy     #$00
L068C:	jsr     staxysp
;
; success = (the_bank != NULL);
;
	cpx     #$00
	bne     L04B3
	cmp     #$00
L04B3:	jsr     boolne
	ldy     #$05
	sta     (sp),y
;
; if (success)
;
	lda     (sp),y
	jeq     L0686
;
; if (the_row > content_top + the_panel->height_ || the_row + 1 < content_top) {
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tosadda0
	jsr     tosicmp
	beq     L0683
	bcs     L04B7
L0683:	ldy     #$09
	jsr     ldaxysp
	ina
	bne     L04B8
	inx
L04B8:	ldy     #$04
	cmp     (sp),y
	txa
	sbc     #$00
	bcs     L04B6
;
; the_panel->content_top_ = the_row < content_top ? the_row : the_row - the_panel->height_ + 1;
;
L04B7:	ldy     #$0D
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$06
	cmp     (sp),y
	txa
	sbc     #$00
	bcs     L04BC
	ldy     #$0A
	lda     (sp),y
	bra     L0688
L04BC:	ldy     #$0D
	jsr     pushwysp
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tossuba0
	ina
	ldy     #$0A
L0688:	jsr     staspidx
;
; Panel_ReflowContent(the_panel);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Panel_ReflowContent
;
; Panel_RenderContents(the_panel);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Panel_RenderContents
;
; return true;
;
	ldx     #$00
	lda     #$01
	jmp     L0490
;
; if (the_row >= (content_top + the_panel->height_))
;
L04B6:	ldy     #$0B
	jsr     pushwysp
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tosadda0
	jsr     tosicmp
	bcc     L04C6
;
; scroll_needed = true;
;
	lda     #$01
	ldy     #$06
	sta     (sp),y
;
; ++the_panel->content_top_;
;
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     #$01
	clc
	adc     (ptr1),y
	sta     (ptr1),y
;
; Text_SetXY(the_panel->x_, UI_VIEW_PANEL_SCROLL_UP_START);
;
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	lda     #$09
	jsr     _Text_SetXY
;
; zp_y_cnt = UI_VIEW_PANEL_SCROLL_CNT;
;
	lda     #$28
	sta     _zp_y_cnt
;
; Text_ScrollTextUp(UI_PANEL_INNER_WIDTH);
;
	lda     #$21
	jsr     _Text_ScrollTextUp
;
; else if (the_row < content_top)
;
	bra     L04D6
L04C6:	ldy     #$09
	jsr     ldaxysp
	ldy     #$04
	cmp     (sp),y
	txa
	sbc     #$00
	bcs     L04D6
;
; scroll_needed = true;
;
	lda     #$01
	ldy     #$06
	sta     (sp),y
;
; --the_panel->content_top_;
;
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
;
; Text_SetXY(the_panel->x_, UI_VIEW_PANEL_SCROLL_DN_START);
;
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	lda     #$30
	jsr     _Text_SetXY
;
; zp_y_cnt = UI_VIEW_PANEL_SCROLL_CNT;
;
	lda     #$28
	sta     _zp_y_cnt
;
; Text_ScrollTextDown(UI_PANEL_INNER_WIDTH);
;
	lda     #$21
	jsr     _Text_ScrollTextDown
;
; if (scroll_needed == true)
;
L04D6:	ldy     #$06
	lda     (sp),y
	cmp     #$01
	bne     L04F0
;
; Panel_ReflowContent(the_panel);
;
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Panel_ReflowContent
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L04E8
;
; File_Render(the_file, File_IsSelected(the_file), the_panel->y_, the_panel->active_);
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     _File_IsSelected
	jsr     pusha
	ldy     #$0E
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaidx
	jsr     pusha
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _File_Render
;
; else
;
	bra     L04F0
;
; Bank_Render(the_bank, Bank_IsSelected(the_bank), the_panel->y_, the_panel->active_);
;
L04E8:	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	jsr     _Bank_IsSelected
	jsr     pusha
	ldy     #$0E
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaidx
	jsr     pusha
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _Bank_Render
;
; return success;
;
L04F0:	ldy     #$05
	ldx     #$00
L0686:	lda     (sp),y
;
; }
;
L0490:	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_ReflowContent (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ReflowContent: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == true)
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L04F9
;
; Panel_ReflowContentForDisk(the_panel);
;
	jsr     ldax0sp
	jsr     _Panel_ReflowContentForDisk
;
; else
;
	jmp     incsp2
;
; Panel_ReflowContentForMemory(the_panel);
;
L04F9:	jsr     ldax0sp
	jsr     _Panel_ReflowContentForMemory
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_ClearDisplay (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ClearDisplay: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; Text_FillBox(the_panel->x_ + 0, the_panel->y_ + 0, the_panel->x_ + the_panel->width_ - 1, the_panel->y_ + the_panel->height_ - 1, CH_SPACE, LIST_ACTIVE_COLOR, APP_BACKGROUND_COLOR);
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$07
	lda     (ptr1),y
	jsr     tosadda0
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tosadda0
	sec
	sbc     #$01
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$0B
	jsr     pusha
	lda     #$00
	jsr     _Text_FillBox
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_RenderContents (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_RenderContents: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; Directory_SelectPanel(the_panel);
;
	jsr     ldax0sp
	jsr     _Directory_SelectPanel
;
; the_panel->x_, the_panel->y_,
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha
;
; the_panel->x_ + (UI_PANEL_INNER_WIDTH - 1), the_panel->y_ + (UI_PANEL_INNER_HEIGHT - 2),
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	ldx     #$00
	lda     (ptr1),y
	ldy     #$20
	jsr     incaxy
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	ldx     #$00
	lda     (ptr1),y
	ldy     #$28
	jsr     incaxy
	jsr     pusha
;
; CH_SPACE, LIST_ACTIVE_COLOR, APP_BACKGROUND_COLOR
;
	lda     #$20
	jsr     pusha
	lda     #$0B
	jsr     pusha
;
; );
;
	lda     #$00
	jsr     _Text_FillBox
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_DrawPanelHeader(the_panel->x_, the_panel->for_disk_);
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	jsr     _Screen_DrawPanelHeader
;
; if (the_panel->for_disk_ == true)
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L051B
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	jsr     decsp2
	lda     #$09
	jsr     _App_LoadOverlay
;
; the_item = *(the_panel->root_folder_->list_);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     ldaxi
	jsr     ldaxi
	jsr     stax0sp
;
; while (the_item != NULL)
;
	bra     L0524
;
; WB2KFileObject*  this_file = (WB2KFileObject*)(the_item->payload_);
;
L068D:	jsr     ldax0sp
	ldy     #$05
	jsr     pushwidx
;
; File_Render(this_file, File_IsSelected(this_file), the_panel->y_, the_panel->active_);
;
	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	jsr     _File_IsSelected
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaidx
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _File_Render
;
; the_item = the_item->next_item_;
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$02
	jsr     staxysp
;
; }
;
	jsr     incsp2
;
; while (the_item != NULL)
;
L0524:	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L068D
;
; }
;
	jsr     incsp2
;
; else
;
	bra     L0531
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L051B:	jsr     decsp1
	lda     #$0C
	jsr     _App_LoadOverlay
;
; for (row = 0; row < MEMORY_BANK_COUNT; row++)
;
	lda     #$00
L0690:	sta     (sp)
	cmp     #$40
	bcs     L0535
;
; this_bank = &the_panel->memory_system_->bank_[row];
;
	jsr     decsp2
	ldy     #$04
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	ina
	bne     L053E
	inx
L053E:	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	jsr     tosaddax
	jsr     stax0sp
;
; Bank_Render(this_bank, Bank_IsSelected(this_bank), the_panel->y_, the_panel->active_);
;
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _Bank_IsSelected
	jsr     pusha
	ldy     #$07
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaidx
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _Bank_Render
;
; }
;
	jsr     incsp2
;
; for (row = 0; row < MEMORY_BANK_COUNT; row++)
;
	lda     (sp)
	ina
	bra     L0690
;
; }
;
L0535:	jsr     incsp1
;
; Panel_RenderTitleOnly(the_panel);
;
L0531:	jsr     ldax0sp
	jsr     _Panel_RenderTitleOnly
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_SortAndDisplay (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SortAndDisplay: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; Directory_SelectPanel(the_panel);
;
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     _Directory_SelectPanel
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	jne     L057F
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; WB2KList* item = *the_panel->root_folder_->list_;
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     ldaxi
	jsr     pushw
;
; while (item) { ((WB2KFileObject*)item->payload_)->selected_ = false; item = item->next_item_; }
;
	bra     L0586
L0584:	jsr     ldax0sp
	ldy     #$05
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0B
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     ldaxi
	jsr     stax0sp
L0586:	ldy     #$01
	lda     (sp),y
	ora     (sp)
	bne     L0584
;
; }
;
	jsr     incsp2
;
; the_panel->content_top_ = 0;
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$0A
	sta     (ptr1),y
;
; the_panel->root_folder_->cur_row_ = -1;
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$08
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; List_InitMergeSort(the_panel->root_folder_->list_, the_panel->sort_compare_function_);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     pushw
	ldy     #$05
	jsr     ldaxysp
	ldy     #$10
	jsr     ldaxidx
	jsr     _List_InitMergeSort
;
; Panel_ReflowContent(the_panel);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _Panel_ReflowContent
;
; Panel_RenderContents(the_panel);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _Panel_RenderContents
;
; if (the_panel->root_folder_->file_count_ > 0)
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$07
	jsr     ldaxidx
	cpx     #$00
	bne     L0691
	cmp     #$00
	beq     L0598
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
L0691:	lda     #$09
	jsr     _App_LoadOverlay
;
; the_file = Folder_SetFileSelectionByRow(the_panel->root_folder_, 0, true, the_panel->y_);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     pushw
	jsr     push0
	lda     #$01
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     _Folder_SetFileSelectionByRow
	jsr     stax0sp
;
; File_Render(the_file, File_IsSelected(the_file), the_panel->y_, the_panel->active_);
;
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _File_IsSelected
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaidx
	jsr     pusha
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _File_Render
;
; else
;
	bra     L05A9
;
; Folder_SetCurrentRow(the_panel->root_folder_, -1);
;
L0598:	ldy     #$03
	jsr     ldaxysp
	jsr     pushw
	ldx     #$FF
	txa
	jsr     _Folder_SetCurrentRow
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
L05A9:	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_UpdateSortIcons(the_panel->x_, the_panel->sort_compare_function_);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	ldy     #$10
	jsr     ldaxidx
	jsr     _Screen_UpdateSortIcons
;
; Screen_UpdateMeatloafIcon(the_panel->x_, the_panel->root_folder_->is_meatloaf_);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	jsr     _Screen_UpdateMeatloafIcon
;
; else
;
	jmp     incsp4
;
; Panel_ReflowContent(the_panel);
;
L057F:	ldy     #$03
	jsr     ldaxysp
	jsr     _Panel_ReflowContent
;
; Panel_RenderContents(the_panel);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _Panel_RenderContents
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; Screen_UpdateMeatloafIcon(the_panel->x_, false);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	lda     #$00
	jsr     _Screen_UpdateMeatloafIcon
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; MemSys_SetBankSelectionByRow(the_panel->memory_system_, 0, PARAM_MARK_SELECTED, the_panel->y_, the_panel->active_);
;
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     pushwidx
	jsr     push0
	lda     #$01
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	jsr     _MemSys_SetBankSelectionByRow
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_FillCurrentBank (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_FillCurrentBank: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; if (MemSys_BankIsWriteable(the_panel->memory_system_) == false)
;
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_BankIsWriteable
	cmp     #$00
	bne     L01A0
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_TO_OVERWRITE_FM_RAM));
;
	lda     #$79
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp2
;
; return (MemSys_FillCurrentBank(the_panel->memory_system_));
;
L01A0:	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_FillCurrentBank
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_ClearCurrentBank (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ClearCurrentBank: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; if (MemSys_BankIsWriteable(the_panel->memory_system_) == false)
;
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_BankIsWriteable
	cmp     #$00
	bne     L01AD
;
; Buffer_NewMessage(General_GetString(ID_STR_ERROR_ATTEMPT_TO_OVERWRITE_FM_RAM));
;
	lda     #$79
	jsr     _General_GetString
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp2
;
; return (MemSys_ClearCurrentBank(the_panel->memory_system_));
;
L01AD:	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_ClearCurrentBank
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_SearchCurrentBank (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_SearchCurrentBank: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == true)
;
	jsr     decsp3
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L05C8
;
; return false;
;
	ldx     #$00
	txa
	jmp     incsp5
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
L05C8:	lda     #$0C
	jsr     _App_LoadOverlay
;
; the_bank_num = MemSys_GetCurrentBankNum(the_panel->memory_system_);
;
	ldy     #$04
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _MemSys_GetCurrentBankNum
	ldy     #$02
	sta     (sp),y
;
; General_Strlcpy(global_string_buff1, General_GetString(ID_STR_DLG_SEARCH_BANK_TITLE), 70);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$14
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$46
	jsr     _General_Strlcpy
;
; General_Strlcpy(global_string_buff2, global_search_phrase_human_readable, MAX_SEARCH_PHRASE_LEN + 1);
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     _global_search_phrase_human_readable
	ldx     _global_search_phrase_human_readable+1
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$21
	jsr     _General_Strlcpy
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; search_phrase = Screen_GetStringFromUser(global_string_buff1, General_GetString(ID_STR_DLG_SEARCH_BANK_BODY), global_string_buff2, MAX_SEARCH_PHRASE_LEN);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$15
	jsr     _General_GetString
	jsr     pushax
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$20
	jsr     _Screen_GetStringFromUser
	jsr     stax0sp
;
; if (search_phrase == NULL)
;
	cpx     #$00
	bne     L05E2
	cmp     #$00
	bne     L05E2
;
; global_search_phrase_len = 0;
;
	stz     _global_search_phrase_len
;
; *global_search_phrase = 0;
;
	lda     _global_search_phrase+1
	sta     ptr1+1
	lda     _global_search_phrase
	sta     ptr1
	txa
	sta     (ptr1)
;
; return false;
;
	jmp     incsp5
;
; General_Strlcpy(global_search_phrase_human_readable, search_phrase, MAX_SEARCH_PHRASE_LEN + 1);
;
L05E2:	lda     _global_search_phrase_human_readable
	ldx     _global_search_phrase_human_readable+1
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$21
	jsr     _General_Strlcpy
;
; global_search_phrase_len = ScreenEvaluateUserStringForHexSeries(&search_phrase);
;
	lda     sp
	ldx     sp+1
	jsr     _ScreenEvaluateUserStringForHexSeries
	sta     _global_search_phrase_len
;
; memcpy(global_search_phrase, search_phrase, global_search_phrase_len);
;
	lda     _global_search_phrase
	ldx     _global_search_phrase+1
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	lda     _global_search_phrase_len
	ldx     #$00
	jsr     _memcpy
;
; zp_search_loc_byte = 0; // start at begining of page
;
	stz     _zp_search_loc_byte
;
; zp_search_loc_page = 0; // start at first page in bank
;
	stz     _zp_search_loc_page
;
; zp_search_loc_bank = the_bank_num; // start at the currently selected bank
;
	ldy     #$02
	lda     (sp),y
	sta     _zp_search_loc_bank
;
; App_LoadOverlay(OVERLAY_EM);
;
	lda     #$0A
	jsr     _App_LoadOverlay
;
; if ( (global_find_next_enabled = EM_SearchMemory(PARAM_START_FROM_THIS_BANK)) == false)
;
	lda     #$01
	jsr     _EM_SearchMemory
	sta     _global_find_next_enabled
	cmp     #$00
	bne     L05FD
;
; return false;
;
	tax
	jmp     incsp5
;
; return true;
;
L05FD:	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Panel_OpenMeatloafURL (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_OpenMeatloafURL: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->for_disk_ == false)
;
	jsr     decsp3
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	bne     L0605
;
; return false;
;
	tax
	jmp     incsp5
;
; if (the_panel->root_folder_->is_meatloaf_ == false)
;
L0605:	ldy     #$04
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	bne     L0608
;
; return false;
;
	tax
	jmp     incsp5
;
; General_Strlcpy((char*)global_string_buff2, General_GetString(ID_STR_DLG_MEATLOAF_DEFAULT_URL), FILE_MAX_FILENAME_SIZE); // pre-set the foenix app store
;
L0608:	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	lda     #$10
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$20
	jsr     _General_Strlcpy
;
; General_Strlcpy(global_string_buff1, General_GetString(ID_STR_DLG_MEATLOAF_URL_TITLE), APP_DIALOG_WIDTH);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$0E
	jsr     _General_GetString
	jsr     pushax
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$2A
	jsr     _General_Strlcpy
;
; App_LoadOverlay(OVERLAY_SCREEN);
;
	lda     #$08
	jsr     _App_LoadOverlay
;
; global_string_buff1,
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
;
; General_GetString(ID_STR_DLG_MEATLOAF_URL_BODY),
;
	lda     #$0F
	jsr     _General_GetString
	jsr     pushax
;
; global_string_buff2,
;
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
;
; FILE_MAX_FILENAME_SIZE);
;
	lda     #$20
	jsr     _Screen_GetStringFromUser
	jsr     stax0sp
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; if (the_name == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L0622
;
; return false;
;
	tax
	jmp     incsp5
;
; sprintf(global_temp_path_1, "%u:%s", the_panel->root_folder_->device_number_, global_string_buff2);
;
L0622:	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     #<(L0628)
	ldx     #>(L0628)
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	jsr     pusha0
	lda     _global_string_buff2
	ldx     _global_string_buff2+1
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; success = File_LoadFileToEM(global_temp_path_1, EM_STORAGE_START_PHYS_BANK_NUM);
;
	lda     _global_temp_path_1
	ldx     _global_temp_path_1+1
	jsr     pushax
	lda     #$14
	jsr     _File_LoadFileToEM
	ldy     #$02
	sta     (sp),y
;
; Panel_Refresh(the_panel);
;
	ldy     #$04
	jsr     ldaxysp
	jsr     _Panel_Refresh
;
; return success;
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_ReflowContentForDisk (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ReflowContentForDisk: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; uint16_t  num_files = 0;
;
	jsr     decsp6
	jsr     push0
;
; uint8_t  first_viz_row = the_panel->content_top_;
;
	jsr     decsp1
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	jsr     pusha
;
; uint16_t  last_viz_row = first_viz_row + the_panel->height_ - 1;
;
	lda     (sp)
	jsr     pusha0
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tosadda0
	jsr     decax1
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_DISKSYS);
;
	lda     #$09
	jsr     _App_LoadOverlay
;
; num_files = Folder_GetCountFiles(the_panel->root_folder_);
;
	ldy     #$0D
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _Folder_GetCountFiles
	ldy     #$04
	jsr     staxysp
;
; num_rows = num_files;
;
	ldy     #$08
	jsr     staxysp
;
; if (num_rows > PANEL_LIST_MAX_ROWS)
;
	cmp     #$00
	txa
	sbc     #$01
	lda     #$00
	rol     a
;
; if (num_files == 0)
;
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L003E
;
; the_panel->num_rows_ = 0;
;
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
;
; return;
;
	jmp     L0697
;
; the_item = *(the_panel->root_folder_->list_);
;
L003E:	ldy     #$0D
	jsr     ldaxysp
	jsr     ldaxi
	jsr     ldaxi
	jsr     ldaxi
	ldy     #$0A
	jsr     staxysp
;
; if ( the_item == NULL )
;
	cpx     #$00
	bne     L0046
	cmp     #$00
	bne     L069A
;
; App_Exit(ERROR_NO_FILES_IN_FILE_LIST); // crash early, crash often
;
	lda     #$65
	jsr     _App_Exit
;
; for (row = 0; row < num_rows && the_item; row++)
;
L0046:	ldx     #$00
L069A:	txa
L069B:	ldy     #$06
	jsr     staxysp
	ldy     #$08
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	jcs     L004C
	ldy     #$0B
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L004C
;
; if (row >= first_viz_row && row <= last_viz_row)
;
	jsr     decsp2
	dey
	jsr     ldaxysp
	ldy     #$04
	cmp     (sp),y
	txa
	sbc     #$00
	bcc     L0056
	ldy     #$09
	jsr     ldaxysp
	sec
	ldy     #$02
	sbc     (sp),y
	sta     tmp1
	txa
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L0057
	bne     L0056
;
; display_row = row - first_viz_row;
;
L0057:	ldy     #$09
	jsr     ldaxysp
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	pla
	cmp     #$80
;
; else
;
	bra     L0698
;
; display_row = -1;
;
L0056:	lda     #$FF
L0698:	ldy     #$05
	sta     (sp),y
;
; this_file = (WB2KFileObject*)(the_item->payload_);
;
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	jsr     stax0sp
;
; File_UpdatePos(this_file, the_panel->x_, display_row, row);
;
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$0D
	jsr     ldaxysp
	jsr     _File_UpdatePos
;
; the_item = the_item->next_item_;
;
	ldy     #$0D
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$0C
	jsr     staxysp
;
; }
;
	jsr     incsp2
;
; for (row = 0; row < num_rows && the_item; row++)
;
	ldy     #$07
	jsr     ldaxysp
	ina
	jne     L069B
	inx
	jmp     L069B
;
; the_panel->num_rows_ = num_rows;
;
L004C:	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (sp),y
L0697:	ldy     #$09
	sta     (ptr1),y
;
; }
;
	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_ReflowContentForMemory (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_ReflowContentForMemory: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; uint8_t  first_viz_row = the_panel->content_top_;
;
	jsr     decsp3
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	jsr     pusha
;
; uint16_t  last_viz_row = first_viz_row + the_panel->height_ - 1;
;
	lda     (sp)
	jsr     pusha0
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	jsr     tosadda0
	jsr     decax1
	jsr     pushax
;
; App_LoadOverlay(OVERLAY_MEMSYSTEM);
;
	lda     #$0C
	jsr     _App_LoadOverlay
;
; for (row = 0; row < MEMORY_BANK_COUNT; row++)
;
	ldx     #$00
	txa
L06A1:	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	cmp     #$00
	bne     L0078
	dey
	lda     (sp),y
	cmp     #$40
L0078:	jcs     L0072
;
; if (row >= first_viz_row && row <= last_viz_row)
;
	jsr     decsp2
	ldy     #$07
	jsr     ldaxysp
	ldy     #$04
	cmp     (sp),y
	txa
	sbc     #$00
	bcc     L007B
	ldy     #$07
	jsr     ldaxysp
	sec
	ldy     #$02
	sbc     (sp),y
	sta     tmp1
	txa
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L007C
	bne     L007B
;
; display_row = row - first_viz_row;
;
L007C:	ldy     #$07
	jsr     ldaxysp
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	pla
	cmp     #$80
;
; else
;
	bra     L069F
;
; display_row = -1;
;
L007B:	lda     #$FF
L069F:	ldy     #$05
	sta     (sp),y
;
; this_bank = &the_panel->memory_system_->bank_[row];
;
	ldy     #$09
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	ina
	bne     L0087
	inx
L0087:	jsr     pushax
	ldy     #$0B
	jsr     pushwysp
	lda     #$0E
	jsr     tosmula0
	jsr     tosaddax
	jsr     stax0sp
;
; Bank_UpdatePos(this_bank, the_panel->x_, display_row, row);
;
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$0B
	jsr     ldaxysp
	jsr     _Bank_UpdatePos
;
; }
;
	jsr     incsp2
;
; for (row = 0; row < MEMORY_BANK_COUNT; row++)
;
	ldy     #$05
	jsr     ldaxysp
	ina
	jne     L06A1
	inx
	jmp     L06A1
;
; the_panel->num_rows_ = MEMORY_BANK_COUNT;
;
L0072:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$40
	ldy     #$09
	sta     (ptr1),y
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ Panel_RenderTitleOnly (__near__ struct WB2KViewPanel *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Panel_RenderTitleOnly: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (the_panel->active_ == true)
;
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	cmp     #$01
	bne     L06A5
;
; fore_color = PANEL_BACKGROUND_COLOR;
;
	dea
	sta     (sp)
;
; back_color = LIST_ACTIVE_COLOR;
;
	lda     #$0B
;
; else
;
	bra     L06A6
;
; fore_color = LIST_INACTIVE_COLOR;
;
L06A5:	lda     #$03
	sta     (sp)
;
; back_color = PANEL_BACKGROUND_COLOR;
;
	lda     #$00
L06A6:	ldy     #$01
	sta     (sp),y
;
; Text_FillBox(the_panel->x_, the_panel->y_ - 3, the_panel->x_ + (UI_PANEL_TAB_WIDTH - 3), the_panel->y_ - 3, CH_SPACE, fore_color, back_color);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	sec
	sbc     #$03
	jsr     pusha
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	ldx     #$00
	lda     (ptr1),y
	ldy     #$19
	jsr     incaxy
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	sec
	sbc     #$03
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _Text_FillBox
;
; if (the_panel->for_disk_ == true)
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	cmp     #$01
	bne     L055D
;
; Text_DrawStringAtXY( the_panel->x_, the_panel->y_ - 3, the_panel->root_folder_->file_name_ ? the_panel->root_folder_->file_name_ : the_panel->root_folder_->file_path_, fore_color, back_color);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	sec
	sbc     #$03
	jsr     pusha
	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L0563
	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$03
	bra     L06A3
L0563:	ldy     #$05
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$05
L06A3:	jsr     ldaxidx
;
; else if (the_panel->device_number_ == DEVICE_RAM)
;
	bra     L06AC
L055D:	ldy     #$03
	jsr     ldaxysp
	ldy     #$0C
	jsr     ldaxidx
	cpx     #$00
	bne     L056A
	cmp     #$08
	bne     L056A
;
; Text_DrawStringAtXY( the_panel->x_, the_panel->y_ - 3, "RAM", fore_color, back_color);
;
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	sec
	sbc     #$03
	jsr     pusha
	lda     #<(L0570)
	ldx     #>(L0570)
;
; else
;
	bra     L06AC
;
; Text_DrawStringAtXY( the_panel->x_, the_panel->y_ - 3, "Flash", fore_color, back_color);
;
L056A:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	sec
	sbc     #$03
	jsr     pusha
	lda     #<(L0578)
	ldx     #>(L0578)
L06AC:	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_DrawStringAtXY
;
; }
;
	jmp     incsp4

.endproc
