; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_calloc
	.import		_free

	.export		_List_RemoveItem
	.export		_List_InitMergeSort
	.export		_List_MergeSortedList
	.export		_List_SplitList
	.export		_List_MergeSort
	.export		_List_RepairPrevLinks

; ---------------------------------------------------------------
; __near__ struct WB2KList * __near__ List_NewItem (__near__ void *)
; ---------------------------------------------------------------

.segment	"CODE"



; ---------------------------------------------------------------
; void __near__ List_Destroy (__near__ __near__ struct WB2KList * *)
; ---------------------------------------------------------------

.segment	"CODE"



; ---------------------------------------------------------------
; void __near__ List_AddItem (__near__ __near__ struct WB2KList * *, __near__ struct WB2KList *)
; ---------------------------------------------------------------

.segment	"CODE"



; ---------------------------------------------------------------
; void __near__ List_RemoveItem (__near__ __near__ struct WB2KList * *, __near__ struct WB2KList *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_RemoveItem: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (*list_head == the_item)
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	cmp     (sp)
	bne     L00CE
	txa
	ldy     #$01
	cmp     (sp),y
	bne     L00CE
;
; *list_head = (*the_item).next_item_;
;
	ldy     #$03
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
;
; if ((*the_item).prev_item_ != NULL)
;
L00CE:	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	cpx     #$00
	bne     L00CC
	cmp     #$00
	beq     L00B1
;
; the_item->prev_item_->next_item_ = (*the_item).next_item_;
;
L00CC:	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
;
; if ((*the_item).next_item_ != NULL)
;
L00B1:	jsr     ldax0sp
	jsr     ldaxi
	cpx     #$00
	bne     L00CD
	cmp     #$00
	beq     L00B8
;
; the_item->next_item_->prev_item_ = (*the_item).prev_item_;
;
L00CD:	jsr     ldax0sp
	jsr     ldaxi
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	ldy     #$03
	jsr     ldaxidx
	ldy     #$02
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
;
; the_item->prev_item_ = NULL;
;
L00B8:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_item->next_item_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ List_InitMergeSort (__near__ __near__ struct WB2KList * *, __near__ __near__ function returning unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_InitMergeSort: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; List_MergeSort(list_head, compare_function);
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     _List_MergeSort
;
; List_RepairPrevLinks(list_head);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     _List_RepairPrevLinks
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; __near__ struct WB2KList * __near__ List_MergeSortedList (__near__ struct WB2KList *, __near__ struct WB2KList *, __near__ __near__ function returning unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_MergeSortedList: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; WB2KList* result = NULL;
;
	jsr     push0
;
; WB2KList** tail = &result;
;
	lda     sp
	ldx     sp+1
	jsr     pushax
;
; while (list1 != NULL && list2 != NULL) {
;
	bra     L0013
;
; if ((*compare_function)(list2->payload_, list1->payload_)) {
;
L0011:	ldy     #$07
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	ldy     #$05
	jsr     pushwidx
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	pha
	ldy     #$02
	lda     (sp),y
	sta     jmpvec+1
	iny
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	tax
	beq     L0019
;
; *tail = list1;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$09
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; list1 = list1->next_item_;
;
	ldy     #$09
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$08
;
; } else {
;
	bra     L00D0
;
; *tail = list2;
;
L0019:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$07
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; list2 = list2->next_item_;
;
	ldy     #$07
	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$06
L00D0:	jsr     staxysp
;
; tail = &(*tail)->next_item_;
;
	jsr     ldax0sp
	jsr     ldaxi
	jsr     stax0sp
;
; while (list1 != NULL && list2 != NULL) {
;
L0013:	ldy     #$08
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L00CF
	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	jne     L0011
;
; if (list1 != NULL) {
;
L00CF:	ldy     #$08
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L002A
;
; *tail = list1;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$09
;
; } else {
;
	bra     L00D7
;
; *tail = list2;
;
L002A:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$07
L00D7:	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; return result;
;
	ldy     #$03
	jsr     ldaxysp
;
; }
;
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ List_SplitList (__near__ struct WB2KList *, __near__ __near__ struct WB2KList * *, __near__ __near__ struct WB2KList * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_SplitList: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; ptr2 = source;
;
	jsr     decsp4
	ldy     #$09
	jsr     ldaxysp
	jsr     stax0sp
;
; ptr1 = source->next_item_;
;
	ldy     #$09
;
; while (ptr1 != NULL)
;
	bra     L00DE
;
; ptr1 = ptr1->next_item_;
;
L00D9:	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$02
	jsr     staxysp
;
; if (ptr1 != NULL)
;
	cpx     #$00
	bne     L00DA
	cmp     #$00
	beq     L003F
;
; ptr2 = ptr2->next_item_;
;
L00DA:	jsr     ldax0sp
	jsr     ldaxi
	jsr     stax0sp
;
; ptr1 = ptr1->next_item_;
;
	ldy     #$03
L00DE:	jsr     ldaxysp
	jsr     ldaxi
	ldy     #$02
	jsr     staxysp
;
; while (ptr1 != NULL)
;
L003F:	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L00D9
;
; *front = source;
;
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$09
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; *back = ptr2->next_item_;
;
	ldy     #$05
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
;
; ptr2->next_item_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
;
; }
;
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ List_MergeSort (__near__ __near__ struct WB2KList * *, __near__ __near__ function returning unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_MergeSort: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; WB2KList* the_item = *list_head;
;
	ldy     #$03
	jsr     ldaxysp
	jsr     pushw
;
; if ((the_item == NULL) || (the_item->next_item_ == NULL))
;
	jsr     decsp4
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L004C
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L004E
	cmp     #$00
	beq     L004C
;
; List_SplitList(the_item, &ptr1, &ptr2);
;
L004E:	ldy     #$07
	jsr     pushwysp
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     _List_SplitList
;
; List_MergeSort(&ptr1, compare_function);
;
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     _List_MergeSort
;
; List_MergeSort(&ptr2, compare_function);
;
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     _List_MergeSort
;
; *list_head = List_MergeSortedList(ptr1, ptr2, compare_function);
;
	ldy     #$0B
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldy     #$0D
	jsr     ldaxysp
	jsr     _List_MergeSortedList
	ldy     #$00
	jsr     staxspidx
;
; }
;
L004C:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ List_RepairPrevLinks (__near__ __near__ struct WB2KList * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_List_RepairPrevLinks: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; WB2KList* prev_item = *list_head;
;
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     pushw
;
; if (prev_item == NULL)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
;
; return;
;
	beq     L0071
;
; prev_item->prev_item_ = NULL;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; if (prev_item->next_item_ == NULL)
;
	jsr     ldax0sp
	jsr     ldaxi
	cpx     #$00
	bne     L00E0
	cmp     #$00
;
; return;
;
	beq     L0071
;
; prev_item->prev_item_ = NULL; // first item might have a now-invalid previous item link, so clear that out
;
L00E0:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; the_item = prev_item->next_item_;
;
L0070:	jsr     ldax0sp
	jsr     ldaxi
	ldy     #$02
	jsr     staxysp
;
; the_item->prev_item_ = prev_item;
;
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$02
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; prev_item = the_item;
;
	jsr     ldaxysp
	jsr     stax0sp
;
; } while (the_item->next_item_ != NULL);
;
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	cpx     #$00
	bne     L0070
	cmp     #$00
	bne     L0070
;
; }
;
L0071:	jmp     incsp6

.endproc
