; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_Startup_LoadString
	.export		_Startup_InitializeRandomNumGen
	.export		_App_InitializeDialogBox
	.import		_Memory_SwapInNewBank
	.import		_Sys_SwapIOPage
	.import		_Sys_RestoreIOPage
	.import		_global_dlg
	.import		_global_dlg_title
	.import		_global_dlg_body_msg
	.import		_global_dlg_button
	.import		_global_string
	.importzp	_zp_bank_num

; ---------------------------------------------------------------
; void __near__ Startup_LoadString (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Startup_LoadString: near

.segment	"OVERLAY_STARTUP"

;
; uint8_t* cursor = (uint8_t*)0xC000;
;
	jsr     decsp5
	ldx     #$C0
	lda     #$00
	jsr     pushax
;
; asm("PHP");
;
	php
;
; asm("SEI");
;
	sei
;
; old_io = R8(MMU_IO_CTRL);
;
	lda     $0001
	ldy     #$02
	sta     (sp),y
;
; R8(MMU_IO_CTRL) = 4;
;
	lda     #$04
	sta     $0001
;
; zp_bank_num = STRING_STORAGE_EM_SLOT;
;
	lda     #$12
	sta     _zp_bank_num
;
; old_bank = Memory_SwapInNewBank(BANK_IO);
;
	lda     #$06
	jsr     _Memory_SwapInNewBank
	ldy     #$03
	sta     (sp),y
;
; for (count = 0; count < NUM_STRINGS; ++count) {
;
	lda     #$00
	iny
L0E20:	sta     (sp),y
	cmp     #$8B
	jcs     L0E24
;
; id = cursor[0];
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$06
	sta     (sp),y
;
; length = cursor[1];
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ldy     #$05
	sta     (sp),y
;
; if (id >= NUM_STRINGS || cursor + length + 2 >= (uint8_t*)0xE000) break;
;
	iny
	lda     (sp),y
	cmp     #$8B
	bcs     L0E24
	ldx     #$00
	dey
	lda     (sp),y
	clc
	adc     (sp)
	pha
	txa
	ldy     #$01
	adc     (sp),y
	tax
	pla
	jsr     incax2
	cmp     #$00
	txa
	sbc     #$E0
	bcs     L0E24
;
; cursor[0] = 0;
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; cursor += 2;
;
	tax
	lda     #$02
	jsr     addeq0sp
;
; global_string[id] = (char*)cursor;
;
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0E21
	inx
	clc
L0E21:	adc     #<(_global_string)
	sta     ptr1
	txa
	adc     #>(_global_string)
	sta     ptr1+1
	jsr     ldax0sp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
;
; cursor += length;
;
	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
;
; for (count = 0; count < NUM_STRINGS; ++count) {
;
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0E20
;
; *cursor = 0;
;
L0E24:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; zp_bank_num = old_bank;
;
	ldy     #$03
	lda     (sp),y
	sta     _zp_bank_num
;
; Memory_SwapInNewBank(BANK_IO);
;
	lda     #$06
	jsr     _Memory_SwapInNewBank
;
; R8(MMU_IO_CTRL) = old_io;
;
	ldy     #$02
	lda     (sp),y
	sta     $0001
;
; asm("PLP");
;
	plp
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ Startup_InitializeRandomNumGen (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Startup_InitializeRandomNumGen: near

.segment	"OVERLAY_STARTUP"

;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	jsr     decsp1
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; old_rtc_control = R8(RTC_CONTROL);
;
	lda     $D69E
	sta     (sp)
;
; R8(RTC_CONTROL) = old_rtc_control | 0x08; // stop it from updating external registers
;
	ora     #$08
	sta     $D69E
;
; R8(RANDOM_NUM_GEN_ENABLE) = 3; // enable and set seed mode
;
	lda     #$03
	sta     $D6A6
;
; R8(RANDOM_NUM_GEN_LOW) = R8(RTC_SECONDS);
;
	lda     $D690
	sta     $D6A4
;
; R8(RANDOM_NUM_GEN_HI) = R8(RTC_MINUTES);
;
	lda     $D692
	sta     $D6A5
;
; R8(RANDOM_NUM_GEN_ENABLE) = 1; // keep enabled, return to generate mode
;
	lda     #$01
	sta     $D6A6
;
; R8(RTC_CONTROL) = old_rtc_control;
;
	lda     (sp)
	sta     $D69E
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ App_InitializeDialogBox (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_App_InitializeDialogBox: near

.segment	"OVERLAY_STARTUP"

;
; global_dlg.x_ = (SCREEN_NUM_COLS - APP_DIALOG_WIDTH)/2;
;
	lda     #$13
	sta     _global_dlg
;
; global_dlg.y_ = 16;
;
	lda     #$10
	sta     _global_dlg+1
;
; global_dlg.width_ = APP_DIALOG_WIDTH;
;
	lda     #$2A
	sta     _global_dlg+2
;
; global_dlg.height_ = APP_DIALOG_HEIGHT;
;
	lda     #$07
	sta     _global_dlg+3
;
; global_dlg.num_buttons_ = APP_DIALOG_STARTING_NUM_BUTTONS;
;
	lda     #$02
	sta     _global_dlg+4
;
; global_dlg.title_text_ = global_dlg_title;
;
	lda     #>(_global_dlg_title)
	sta     _global_dlg+5+1
	lda     #<(_global_dlg_title)
	sta     _global_dlg+5
;
; global_dlg.body_text_ = global_dlg_body_msg;
;
	lda     #>(_global_dlg_body_msg)
	sta     _global_dlg+7+1
	lda     #<(_global_dlg_body_msg)
	sta     _global_dlg+7
;
; global_dlg.btn_label_[0] = global_dlg_button[0];
;
	lda     #>(_global_dlg_button)
	sta     _global_dlg+9+1
	lda     #<(_global_dlg_button)
	sta     _global_dlg+9
;
; global_dlg.btn_label_[1] = global_dlg_button[1];
;
	lda     #>(_global_dlg_button+10)
	sta     _global_dlg+11+1
	lda     #<(_global_dlg_button+10)
	sta     _global_dlg+11
;
; global_dlg.btn_label_[2] = global_dlg_button[2];
;
	lda     #>(_global_dlg_button+20)
	sta     _global_dlg+13+1
	lda     #<(_global_dlg_button+20)
	sta     _global_dlg+13
;
; global_dlg.btn_keycolor_[0] = COLOR_GREEN;
;
	lda     #$03
	sta     _global_dlg+15
	stz     _global_dlg+15+1
;
; global_dlg.btn_keycolor_[1] = COLOR_RED;
;
	lda     #$0D
	sta     _global_dlg+17
	stz     _global_dlg+17+1
;
; global_dlg.btn_keycolor_[2] = COLOR_BLUE;
;
	lda     #$02
	sta     _global_dlg+19
	stz     _global_dlg+19+1
;
; global_dlg.btn_shortcut_[0] = 'n';
;
	lda     #$6E
	sta     _global_dlg+21
;
; global_dlg.btn_shortcut_[1] = 'y';
;
	lda     #$79
	sta     _global_dlg+22
;
; global_dlg.default_button_id_ = 1;
;
	lda     #$01
	sta     _global_dlg+24
;
; global_dlg.default_button_shortcut_ = CH_ENTER;
;
	lda     #$0D
	sta     _global_dlg+25
;
; global_dlg.cancel_button_shortcut_ = CH_RUNSTOP;
;
	lda     #$03
	sta     _global_dlg+26
;
; }
;
	rts

.endproc
