; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import _Viewer_BeginText, _Viewer_BeginHex, _Viewer_ClearScreen
	.import _Viewer_TextRow, _Viewer_HexRow, _Viewer_WaitKey
	.import		_App_EMDataCopy
	.import		_General_GetString
	.import		_General_Strnlen
	.import		_Text_ClearScreen
	.import		_Text_SetXY
	.import		_Text_SetChar
	.import		_Text_DrawByteAsHexChars
	.import		_Text_DrawStringAtXY
	.export		_EM_DisplayAsText
	.export		_EM_DisplayAsHex
	.export		_EM_SearchMemory
	.import		_Buffer_NewMessage
	.import		_Keyboard_GetKeyIfPressed
	.import		_Keyboard_GetChar
	.import		_snprintf
	.import		_strlen
	.import		_memcpy
	.import		_memmove
	.import		_memset
	.import		_global_search_phrase_len
	.import		_global_search_phrase
	.import		_global_search_phrase_human_readable
	.import		_global_string_buff1
	.import		_global_find_next_enabled
	.importzp	_zp_search_loc_byte
	.importzp	_zp_search_loc_page
	.importzp	_zp_search_loc_bank

.segment	"DATA"

.segment	"OVERLAY_EM"
_em_temp_buffer_384b_storage:
	.byte	$00
	.res	383,$00
_em_temp_buffer_384b:
	.addr	_em_temp_buffer_384b_storage

; ---------------------------------------------------------------
; void __near__ EM_DisplayAsText (unsigned char, unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_EM"

.proc	_EM_DisplayAsText: near

.segment	"OVERLAY_EM"

	jsr     _Viewer_BeginText

;
; {
;
	jsr     pushax
;
; uint8_t  i = 0;
;
	lda     #$00
	jsr     pusha
;
; uint8_t  y = 0;
;
	jsr     pusha
;
; bool  keep_going = true;
;
	jsr     decsp4
	lda     #$01
	jsr     pusha
;
; bool  user_exit = false;
;
	dea
	jsr     pusha
;
; uint16_t remain_len = 0;
;
	ldy     #$0B
	jsr     subysp
	jsr     push0
;
; copy_buffer = em_temp_buffer_384b;
;
	lda     _em_temp_buffer_384b
	ldx     _em_temp_buffer_384b+1
	ldy     #$0A
	jsr     staxysp
;
; line_buffer = (char*)STORAGE_STRING_BUFFER_2;
;
	ldx     #$06
	lda     #$CC
	ldy     #$06
	jsr     staxysp
;
; line_buffer[0] = 0;
;
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; if (!num_pages) {
;
	ldy     #$17
	lda     (sp),y
	jne     L00B4
;
; Text_ClearScreen(FILE_CONTENTS_FOREGROUND_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	lda     #$0B
	jsr     pusha
	lda     #$00
	jsr     _Viewer_ClearScreen
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_TEXT_VIEW_INSTRUCTIONS), the_name);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$52
	jsr     _General_GetString
	jsr     pushax
	ldy     #$1E
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Text_DrawStringAtXY(0, 0, global_string_buff1, FILE_CONTENTS_ACCENT_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; while (keep_going == true && i < num_pages)
;
	jmp     L00B4
;
; App_EMDataCopy(copy_buffer, em_bank_num, i++, PARAM_COPY_FROM_EM);
;
L00A2:	ldy     #$0D
	jsr     pushwysp
	ldy     #$1A
	lda     (sp),y
	jsr     pusha
	ldy     #$17
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; buffer_curr_loc = copy_buffer;
;
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$08
	jsr     staxysp
;
; unprocessed_bytes = 256;
;
	ldx     #$01
	lda     #$00
	ldy     #$02
	jsr     staxysp
;
; copy_again = false;
;
	ldy     #$0C
	sta     (sp),y
;
; if (y == 0)
;
L00B3:	ldy     #$13
	ldx     #$00
	lda     (sp),y
	bne     L027E
;
; Text_ClearScreen(FILE_CONTENTS_FOREGROUND_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	lda     #$0B
	jsr     pusha
	txa
	jsr     _Viewer_ClearScreen
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_TEXT_VIEW_INSTRUCTIONS), the_name);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$52
	jsr     _General_GetString
	jsr     pushax
	ldy     #$1E
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Text_DrawStringAtXY(0, y++, global_string_buff1, FILE_CONTENTS_ACCENT_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	ldy     #$14
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; ++y;
;
	ldy     #$13
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; needed_bytes =  MEM_TEXT_VIEW_BYTES_PER_ROW - remain_len;
;
	ldx     #$00
L027E:	lda     #$50
	sec
	sbc     (sp)
	pha
	txa
	ldy     #$01
	sbc     (sp),y
	pla
	ldy     #$11
	sta     (sp),y
;
; if (unprocessed_bytes > 0)
;
	ldy     #$03
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L00CC
	eor     #$80
L00CC:	asl     a
	lda     #$00
	jcc     L0280
;
; if (unprocessed_bytes > needed_bytes)
;
	ldy     #$03
	jsr     ldaxysp
	sec
	ldy     #$11
	sbc     (sp),y
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	bcc     L00CD
;
; else
;
	bne     L028F
;
; available_bytes = unprocessed_bytes;
;
L00CD:	ldy     #$02
L028F:	lda     (sp),y
	ldy     #$10
	sta     (sp),y
;
; if (remain_len > 0)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	beq     L00D4
;
; memcpy(line_buffer + remain_len, buffer_curr_loc, available_bytes);
;
	jsr     ldax0sp
	clc
	ldy     #$06
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$14
	lda     (sp),y
	ldx     #$00
	jsr     _memcpy
;
; line_buffer[remain_len + available_bytes] = 0;
;
	ldy     #$10
	lda     (sp),y
	clc
	adc     (sp)
	pha
	lda     #$00
	ldy     #$01
	adc     (sp),y
	tax
	pla
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	txa
;
; else
;
	bra     L0295
;
; memcpy(line_buffer, buffer_curr_loc, available_bytes);
;
L00D4:	ldy     #$09
	jsr     pushwysp
	ldy     #$0D
	jsr     pushwysp
	ldy     #$14
	lda     (sp),y
	ldx     #$00
	jsr     _memcpy
;
; line_buffer[available_bytes] = 0;
;
	ldy     #$10
	lda     (sp),y
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	lda     #$00
L0295:	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; buffer_curr_loc += available_bytes;
;
	ldy     #$10
	lda     (sp),y
	ldx     #$00
	ldy     #$08
	jsr     addeqysp
;
; unprocessed_bytes -= available_bytes;
;
	ldy     #$10
	lda     (sp),y
	ldx     #$00
	ldy     #$02
	jsr     subeqysp
;
; else
;
	bra     L00EA
;
; keep_going = false;
;
L0280:	ldy     #$0E
	sta     (sp),y
;
; line_buffer_remainder = EM_DisplayStringWithLineBreaks(line_buffer, 0, y, MEM_TEXT_VIEW_BYTES_PER_ROW, 1);
;
L00EA:	ldy     #$09
	jsr     pushwysp
	lda     #$00
	jsr     pusha
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	lda     #$50
	jsr     pusha
	lda     #$01
	jsr     _Viewer_TextRow
	ldy     #$04
	jsr     staxysp
;
; if (line_buffer_remainder == NULL)
;
	cpx     #$00
	bne     L00F4
	cmp     #$00
	bne     L00F4
;
; bytes_not_displayed = 0;
;
	ldy     #$0F
	sta     (sp),y
;
; line_buffer_remainder = line_buffer;
;
	ldy     #$07
	jsr     ldaxysp
	ldy     #$04
	jsr     staxysp
;
; else
;
	bra     L00FB
;
; bytes_not_displayed = strlen(line_buffer_remainder);
;
L00F4:	ldy     #$05
	jsr     ldaxysp
	jsr     _strlen
	cmp     #$80
	ldy     #$0F
	sta     (sp),y
;
; if (bytes_not_displayed > 0)
;
L00FB:	ldy     #$0F
	lda     (sp),y
	sec
	sbc     #$01
	bvs     L0103
	eor     #$80
L0103:	bpl     L0100
;
; memmove(line_buffer, line_buffer_remainder, bytes_not_displayed);
;
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$13
	ldx     #$00
	lda     (sp),y
	cmp     #$80
	bcc     L0109
	dex
L0109:	jsr     _memmove
;
; line_buffer[bytes_not_displayed] = 0;
;
	ldx     #$00
	ldy     #$0F
	lda     (sp),y
	bpl     L010C
	dex
L010C:	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
;
; else
;
	bra     L0291
;
; line_buffer[0] = 0;
;
L0100:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
L0291:	lda     #$00
	sta     (ptr1)
;
; remain_len = General_Strnlen(line_buffer, STORAGE_STRING_BUFFER_1_LEN);
;
	ldy     #$09
	jsr     pushwysp
	ldx     #$00
	lda     #$CC
	jsr     _General_Strnlen
	jsr     stax0sp
;
; ++y;
;
	ldy     #$13
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; if (y == MAX_TEXT_VIEW_ROWS_PER_PAGE)
;
	cmp     #$3B
	bne     L0123
;
; user_input = Keyboard_GetChar();
;
	jsr     _Viewer_WaitKey
	ldy     #$12
	sta     (sp),y
;
; if (user_input == CH_ESC || user_input == 'q' || user_input == CH_RUNSTOP)
;
	cmp     #$1B
	beq     L0282
	lda     (sp),y
	cmp     #$71
	beq     L0282
	cmp     #$03
	beq     L0282
	lda     #$00
	bra     L0284
;
; keep_going = false;
;
L0282:	lda     #$00
	ldy     #$0E
	sta     (sp),y
;
; user_exit = true;
;
	ina
	dey
;
; else
;
	bra     L027C
;
; y = 0;
;
L0284:	iny
L027C:	sta     (sp),y
;
; if (remain_len + unprocessed_bytes >= MEM_TEXT_VIEW_BYTES_PER_ROW)
;
L0123:	ldy     #$03
	jsr     ldaxysp
	clc
	adc     (sp)
	pha
	txa
	ldy     #$01
	adc     (sp),y
	tax
	pla
	cmp     #$50
	txa
	sbc     #$00
;
; else
;
	jcs     L014C
;
; if (unprocessed_bytes > 0)
;
	ldy     #$03
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L012B
	eor     #$80
L012B:	jpl     L0129
;
; if (remain_len == 0)
;
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L012C
;
; memcpy(line_buffer, buffer_curr_loc, unprocessed_bytes);
;
	ldy     #$09
	jsr     pushwysp
	ldy     #$0D
	jsr     pushwysp
	ldy     #$07
	jsr     ldaxysp
	jsr     _memcpy
;
; line_buffer[unprocessed_bytes] = 0;
;
	ldy     #$03
	jsr     ldaxysp
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
;
; else
;
	bra     L0292
;
; memcpy(line_buffer + remain_len, buffer_curr_loc, unprocessed_bytes);
;
L012C:	jsr     ldax0sp
	clc
	ldy     #$06
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$07
	jsr     ldaxysp
	jsr     _memcpy
;
; line_buffer[remain_len + unprocessed_bytes] = 0;
;
	ldy     #$09
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$02
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
L0292:	lda     #$00
	sta     (ptr1)
;
; remain_len = General_Strnlen(line_buffer, STORAGE_STRING_BUFFER_1_LEN);
;
	ldy     #$09
	jsr     pushwysp
	ldx     #$00
	lda     #$CC
	jsr     _General_Strnlen
	jsr     stax0sp
;
; memset(line_buffer + remain_len, 0, MEM_TEXT_VIEW_BYTES_PER_ROW - remain_len);
;
	clc
	ldy     #$06
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	lda     #$50
	sec
	ldy     #$02
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	tax
	pla
	jsr     __bzero
;
; memset(copy_buffer, 0, STORAGE_FILE_BUFFER_1_LEN);
;
	ldy     #$0D
	jsr     pushwysp
	ldx     #$01
	lda     #$00
	jsr     __bzero
;
; unprocessed_bytes = 0;
;
	ldx     #$00
	txa
	ldy     #$02
	jsr     staxysp
;
; if (i < num_pages)
;
L0129:	ldy     #$14
	lda     (sp),y
	ldy     #$17
	cmp     (sp),y
	bcs     L014C
;
; copy_again = true;
;
	lda     #$01
	ldy     #$0C
	sta     (sp),y
;
; } while (copy_again == false && keep_going == true);
;
L014C:	ldy     #$0C
	lda     (sp),y
	bne     L00B4
	ldy     #$0E
	lda     (sp),y
	cmp     #$01
	jeq     L00B3
	bra     L028E
;
; while (keep_going == true && i < num_pages)
;
L00B4:	ldy     #$0E
L028E:	lda     (sp),y
	cmp     #$01
	bne     L0278
	ldy     #$14
	lda     (sp),y
	ldy     #$17
	cmp     (sp),y
	jcc     L00A2
;
; if (user_exit != true)
;
L0278:	ldy     #$0D
	lda     (sp),y
	cmp     #$01
	beq     L0154
;
; Keyboard_GetChar();
;
	jsr     _Viewer_WaitKey
;
; }
;
L0154:	ldy     #$19
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ EM_DisplayAsHex (unsigned char, unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"OVERLAY_EM"

.proc	_EM_DisplayAsHex: near

.segment	"OVERLAY_EM"

	jsr     _Viewer_BeginHex

;
; {
;
	jsr     pushax
;
; uint8_t  i = 0;
;
	jsr     decsp3
	lda     #$00
	jsr     pusha
;
; uint8_t  y = 0;
;
	jsr     pusha
;
; uint32_t loc_in_file = 0x0000; // will track the location within the file, so we can show to users on left side.
;
	stz     sreg
	stz     sreg+1
	jsr     pushl0
;
; bool  keep_going = true;
;
	lda     #$01
	jsr     pusha
;
; bool  user_exit = false;
;
	dea
	jsr     pusha
;
; copy_buffer = em_temp_buffer_384b;
;
	jsr     decsp5
	lda     _em_temp_buffer_384b
	ldx     _em_temp_buffer_384b+1
	ldy     #$02
	jsr     staxysp
;
; if (em_bank_num == EM_STORAGE_START_PHYS_BANK_NUM)
;
	ldy     #$13
	ldx     #$00
	lda     (sp),y
	cmp     #$14
	bne     L029A
;
; loc_in_file = 0x0000;
;
	txa
	ldy     #$07
	jsr     steaxysp
;
; else
;
	jmp     L0179
;
; loc_in_file = (uint32_t)((uint32_t)em_bank_num * (uint32_t)8192);
;
L029A:	lda     (sp),y
	jsr     aulong
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     shleax4
	jsr     shleax1
	ldy     #$07
	jsr     steaxysp
;
; while (keep_going == true && i < num_pages)
;
	jmp     L0179
;
; App_EMDataCopy(copy_buffer, em_bank_num, i++, PARAM_COPY_FROM_EM);
;
L0167:	ldy     #$05
	jsr     pushwysp
	ldy     #$15
	lda     (sp),y
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; buffer_curr_loc = copy_buffer;
;
	ldy     #$03
	jsr     ldaxysp
	jsr     stax0sp
;
; copy_again = false;
;
	lda     #$00
	ldy     #$04
	sta     (sp),y
;
; rows_displayed_this_chunk = 0;
;
	ldy     #$0E
	sta     (sp),y
;
; if (y == 0)
;
L0178:	ldy     #$0B
	lda     (sp),y
	bne     L017B
;
; Text_ClearScreen(FILE_CONTENTS_FOREGROUND_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	tya
	jsr     pusha
	lda     #$00
	jsr     _Viewer_ClearScreen
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_HEX_VIEW_INSTRUCTIONS), the_name);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$51
	jsr     _General_GetString
	jsr     pushax
	ldy     #$19
	jsr     pushwysp
	ldy     #$08
	jsr     _snprintf
;
; Text_DrawStringAtXY(0, y++, global_string_buff1, FILE_CONTENTS_ACCENT_COLOR, FILE_CONTENTS_BACKGROUND_COLOR);
;
	lda     #$00
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     pusha
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; ++y;
;
	ldy     #$0B
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; An empty file still gets its heading before the final key wait.
;
	ldy     #$12
	lda     (sp),y
	jeq     L0296
;
; Draw a complete hex row in RAM, then overwrite all 80 screen cells.
;
L017B:	ldy     #$0A
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0F
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	jsr     _Viewer_HexRow
;
; loc_in_file += MEM_DUMP_BYTES_PER_ROW;
;
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$10
	ldy     #$07
	jsr     laddeqysp
;
; buffer_curr_loc += MEM_DUMP_BYTES_PER_ROW;
;
	ldx     #$00
	lda     #$10
	jsr     addeq0sp
;
; ++rows_displayed_this_chunk;
;
	ldy     #$0E
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; ++y;
;
	ldy     #$0B
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
;
; if (y == MAX_TEXT_VIEW_ROWS_PER_PAGE)
;
	cmp     #$3B
	bne     L01CE
;
; user_input = Keyboard_GetChar();
;
	jsr     _Viewer_WaitKey
	ldy     #$0F
	sta     (sp),y
;
; if (user_input == CH_ESC || user_input == 'q' || user_input == CH_RUNSTOP)
;
	cmp     #$1B
	beq     L02A0
	lda     (sp),y
	cmp     #$71
	beq     L02A0
	cmp     #$03
	beq     L02A0
	lda     #$00
	bra     L02A2
;
; keep_going = false;
;
L02A0:	lda     #$00
	ldy     #$06
	sta     (sp),y
;
; user_exit = true;
;
	ina
	dey
;
; else
;
	bra     L0297
;
; y = 0;
;
L02A2:	ldy     #$0B
L0297:	sta     (sp),y
;
; if (rows_displayed_this_chunk > 15)
;
L01CE:	ldy     #$0E
	lda     (sp),y
	cmp     #$10
	bcc     L01D7
;
; if (i < num_pages)
;
	ldy     #$0C
	lda     (sp),y
	ldy     #$12
	cmp     (sp),y
	lda     #$00
	bcs     L02AA
;
; copy_again = true;
;
	ina
	ldy     #$04
;
; else
;
	bra     L0298
;
; keep_going = false;
;
L02AA:	ldy     #$06
L0298:	sta     (sp),y
;
; } while (copy_again == false && keep_going == true);
;
L01D7:	ldy     #$04
	lda     (sp),y
	bne     L0179
	ldy     #$06
	lda     (sp),y
	cmp     #$01
	jeq     L0178
	bra     L02AB
;
; while (keep_going == true && i < num_pages)
;
L0179:	ldy     #$12
	lda     (sp),y
	bne     check_more
	jmp     L0178
check_more:
	ldy     #$06
L02AB:	lda     (sp),y
	cmp     #$01
	bne     L0296
	ldy     #$0C
	lda     (sp),y
	ldy     #$12
	cmp     (sp),y
	jcc     L0167
;
; if (user_exit != true)
;
L0296:	ldy     #$05
	lda     (sp),y
	cmp     #$01
	beq     L01DD
;
; Keyboard_GetChar();
;
	jsr     _Viewer_WaitKey
;
; }
;
L01DD:	ldy     #$14
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ EM_SearchMemory (unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_EM"

.proc	_EM_SearchMemory: near

.segment	"RODATA"

L024C:
	.word	$0000
L0263:
	.word	$0000

.segment	"OVERLAY_EM"

;
; {
;
	jsr     pusha
;
; uint16_t remain_len = 0;
;
	jsr     decsp4
	jsr     push0
;
; uint8_t* copy_buffer = (uint8_t*)STORAGE_FILE_BUFFER_1;
;
	ldy     #$0A
	jsr     subysp
	ldx     #$05
	lda     #$00
	jsr     pushax
;
; DEBUG_OUT(("%s %d: search_len=%u, new_search=%u, first 6 of search phrase = %x%x%x%x%x%x", __func__ , __LINE__, global_search_phrase_len, new_search, global_search_phrase[0], global_search_phrase[1], global_search_phrase[2], global_search_phrase[3], global_search_phrase[4], global_search_phrase[5]));
;
	jsr     decsp2
;
; global_find_next_enabled = false;
;
	stz     _global_find_next_enabled
;
; if (!global_search_phrase_len) return false;
;
	lda     _global_search_phrase_len
	bne     L01E5
	tax
	jmp     L01E0
;
; if (new_search == false)
;
L01E5:	ldy     #$14
	lda     (sp),y
	bne     L02B2
;
; if (zp_search_loc_byte < 255)
;
	lda     _zp_search_loc_byte
	cmp     #$FF
	bcs     L02AF
;
; ++zp_search_loc_byte;
;
	inc     _zp_search_loc_byte
;
; else
;
	bra     L02B2
;
; zp_search_loc_byte = 0;
;
L02AF:	stz     _zp_search_loc_byte
;
; if (zp_search_loc_page < PAGES_PER_BANK - 1)
;
	lda     _zp_search_loc_page
	cmp     #$1F
	bcs     L02B0
;
; ++zp_search_loc_page;
;
	inc     _zp_search_loc_page
;
; else
;
	bra     L02B2
;
; zp_search_loc_page = 0;
;
L02B0:	stz     _zp_search_loc_page
;
; if (zp_search_loc_bank < NUM_MEMORY_BANKS - 1)
;
	ldx     #$00
	lda     _zp_search_loc_bank
	cmp     #$7F
	jcs     L02AD
;
; ++zp_search_loc_bank;
;
	inc     _zp_search_loc_bank
;
; starting_offset = zp_search_loc_byte;
;
L02B2:	lda     _zp_search_loc_byte
	ldy     #$0A
	sta     (sp),y
;
; remain_len = 256 - starting_offset;
;
	lda     #$00
	sec
	sbc     (sp),y
	pha
	lda     #$01
	sbc     #$00
	tax
	pla
	ldy     #$0E
	jsr     staxysp
;
; while (zp_search_loc_bank < NUM_MEMORY_BANKS) //NUM_MEMORY_BANKS
;
	jmp     L0201
;
; App_EMDataCopy(copy_buffer, zp_search_loc_bank, zp_search_loc_page, PARAM_COPY_FROM_EM);
;
L0203:	ldy     #$05
	jsr     pushwysp
	lda     _zp_search_loc_bank
	jsr     pusha
	lda     _zp_search_loc_page
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; buffer_curr_loc = copy_buffer + starting_offset;
;
	ldy     #$0A
	lda     (sp),y
	clc
	ldy     #$02
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	iny
	jsr     staxysp
;
; starting_offset = 0; // only need this on the first page we copy in
;
	lda     #$00
	ldy     #$0A
	sta     (sp),y
;
; for (; remain_len > 0; buffer_curr_loc++, --remain_len, ++zp_search_loc_byte)
;
L0210:	ldy     #$0E
	lda     (sp),y
	iny
	ora     (sp),y
	jeq     L0211
;
; if (*buffer_curr_loc != *global_search_phrase)
;
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	lda     _global_search_phrase+1
	sta     ptr1+1
	lda     _global_search_phrase
	sta     ptr1
	lda     (ptr1)
	jsr     tosicmp0
;
; continue;
;
	jne     L0212
;
; this_phrase = global_search_phrase;
;
	lda     _global_search_phrase
	ldx     _global_search_phrase+1
	ldy     #$06
	jsr     staxysp
;
; this_memory_loc = buffer_curr_loc;
;
	ldy     #$05
	jsr     ldaxysp
	jsr     stax0sp
;
; this_remain_len = remain_len;
;
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$0C
	jsr     staxysp
;
; for (i = 1; i < global_search_phrase_len; ++i, --this_remain_len)
;
	lda     #$01
	ldy     #$0B
	sta     (sp),y
L0222:	ldy     #$0B
	ldx     #$00
	lda     (sp),y
	cmp     _global_search_phrase_len
	jcs     L02B7
;
; ++this_phrase;
;
	ldy     #$06
	lda     #$01
	jsr     addeqysp
;
; ++this_memory_loc;
;
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
;
; if (this_remain_len == 1)
;
	ldy     #$0D
	lda     (sp),y
	bne     L024A
	dey
	lda     (sp),y
	cmp     #$01
	bne     L024A
;
; if (i == global_search_phrase_len)
;
	dey
	lda     (sp),y
	cmp     _global_search_phrase_len
;
; else
;
	beq     L024A
;
; if (zp_search_loc_bank < NUM_MEMORY_BANKS - 1 || zp_search_loc_page < PAGES_PER_BANK - 1)
;
	lda     _zp_search_loc_bank
	cmp     #$7F
	bcc     L02B3
	lda     _zp_search_loc_page
	cmp     #$1F
	jcs     L02B9
;
; this_temp_bank_num = zp_search_loc_bank;
;
L02B3:	lda     _zp_search_loc_bank
	ldy     #$09
	sta     (sp),y
;
; if (zp_search_loc_page < PAGES_PER_BANK - 1)
;
	lda     _zp_search_loc_page
	cmp     #$1F
	bcs     L02B5
;
; this_temp_page_num = zp_search_loc_page + 1;
;
	ina
	dey
;
; else
;
	bra     L02AE
;
; this_temp_page_num = 0;
;
L02B5:	lda     #$00
	dey
	sta     (sp),y
;
; ++this_temp_bank_num;
;
	iny
	clc
	ina
	adc     (sp),y
L02AE:	sta     (sp),y
;
; App_EMDataCopy(em_temp_buffer_384b, this_temp_bank_num, this_temp_page_num, PARAM_COPY_FROM_EM);
;
	lda     _em_temp_buffer_384b
	ldx     _em_temp_buffer_384b+1
	jsr     pushax
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _App_EMDataCopy
;
; this_remain_len = 256;
;
	ldx     #$01
	lda     #$00
	ldy     #$0C
	jsr     staxysp
;
; this_memory_loc = em_temp_buffer_384b;
;
	lda     _em_temp_buffer_384b
	ldx     _em_temp_buffer_384b+1
	jsr     stax0sp
;
; if (*this_phrase != *this_memory_loc)
;
L024A:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     tosicmp0
;
; break;
;
	bne     L0223
;
; for (i = 1; i < global_search_phrase_len; ++i, --this_remain_len)
;
	ldy     #$0B
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldx     #$00
	lda     #$01
	iny
	jsr     subeqysp
	jmp     L0222
;
; if (i == global_search_phrase_len)
;
L0223:	ldy     #$0B
L02B7:	lda     (sp),y
	jsr     pusha0
	lda     _global_search_phrase_len
	jsr     tosicmp0
	jne     L0212
;
; find_location = (uint32_t)((uint32_t)zp_search_loc_bank * (uint32_t)8192) + (uint32_t)zp_search_loc_page * 256 + zp_search_loc_byte;
;
	ldx     #$00
	lda     _zp_search_loc_bank
	jsr     aulong
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     shleax4
	jsr     shleax1
	jsr     pusheax
	ldx     #$00
	lda     _zp_search_loc_page
	jsr     aulong
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$00
	lda     _zp_search_loc_byte
	jsr     axulong
	jsr     tosaddeax
	ldy     #$10
	jsr     steaxysp
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_SEARCH_BANK_SUCCESS), global_search_phrase_human_readable, find_location, zp_search_loc_bank);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$54
	jsr     _General_GetString
	jsr     pushax
	lda     _global_search_phrase_human_readable
	ldx     _global_search_phrase_human_readable+1
	jsr     pushax
	ldy     #$1B
	jsr     ldeaxysp
	jsr     pusheax
	lda     _zp_search_loc_bank
	jsr     pusha0
	ldy     #$0E
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; return true;
;
	ldx     #$00
	lda     #$01
	jmp     L01E0
;
; for (; remain_len > 0; buffer_curr_loc++, --remain_len, ++zp_search_loc_byte)
;
L0212:	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	ina
	bne     L0217
	inx
L0217:	ldy     #$04
	jsr     staxysp
	ldx     #$00
	lda     #$01
	ldy     #$0E
	jsr     subeqysp
	inc     _zp_search_loc_byte
	jmp     L0210
;
; remain_len = 256;
;
L0211:	ldx     #$01
	dey
	jsr     staxysp
;
; if (Keyboard_GetKeyIfPressed() == CH_RUNSTOP)
;
	jsr     _Keyboard_GetKeyIfPressed
	cmp     #$03
;
; goto no_match;
;
	beq     L02B9
;
; ++zp_search_loc_page; // == page counter
;
	inc     _zp_search_loc_page
;
; zp_search_loc_byte = 0; // start the byte-in-page counter over again
;
	stz     _zp_search_loc_byte
;
; while (zp_search_loc_page < PAGES_PER_BANK)
;
L02B8:	lda     _zp_search_loc_page
	cmp     #$20
	jcc     L0203
;
; zp_search_loc_page = 0; // start the page counter over again.
;
	stz     _zp_search_loc_page
;
; ++zp_search_loc_bank; // == bank number
;
	inc     _zp_search_loc_bank
;
; while (zp_search_loc_bank < NUM_MEMORY_BANKS) //NUM_MEMORY_BANKS
;
L0201:	lda     _zp_search_loc_bank
	cmp     #$80
	bcc     L02B8
;
; zp_search_loc_byte = 255; // to make it doubly clear we didn't find anything
;
L02B9:	lda     #$FF
	sta     _zp_search_loc_byte
;
; snprintf(global_string_buff1, STORAGE_STRING_BUFFER_1_LEN, General_GetString(ID_STR_MSG_SEARCH_BANK_FAILURE), global_search_phrase_human_readable);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     pushax
	lda     #$CC
	jsr     pusha0
	lda     #$55
	jsr     _General_GetString
	jsr     pushax
	lda     _global_search_phrase_human_readable
	ldx     _global_search_phrase_human_readable+1
	jsr     pushax
	ldy     #$08
	jsr     _snprintf
;
; Buffer_NewMessage(global_string_buff1);
;
	lda     _global_string_buff1
	ldx     _global_string_buff1+1
	jsr     _Buffer_NewMessage
;
; return false;
;
	ldx     #$00
L02AD:	txa
;
; }
;
L01E0:	ldy     #$15
	jmp     addysp

.endproc
