; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_Sys_InitSystem
	.export		_Sys_AutoConfigure
	.export		_Sys_AutoDetectMachine
	.export		_Sys_DetectScreenSize
	.export		_Sys_EnableTextModeCursor
	.export		_Sys_SetBorderSize
	.export		_Sys_DisableIOBank
	.export		_Sys_SwapIOPage
	.export		_Sys_RestoreIOPage
	.export		_Sys_UpdateRTC
	.import		_strlen
	.import		_memcpy
	.importzp	_zp_old_io_page
	.export		_io_bank_value_kernel
	.export		_overlay_bank_value_kernel
	.export		_global_system
	.export		_Sys_SetGammaMode
	.export		_Sys_DecimalToBCD

.segment	"DATA"

_standard_text_color_lut:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$66
	.byte	$66
	.byte	$66
	.byte	$00
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$EA
	.byte	$41
	.byte	$C0
	.byte	$00
	.byte	$00
	.byte	$48
	.byte	$87
	.byte	$00
	.byte	$00
	.byte	$88
	.byte	$FF
	.byte	$00
	.byte	$FF
	.byte	$DB
	.byte	$57
	.byte	$00
	.byte	$28
	.byte	$3F
	.byte	$3F
	.byte	$00
	.byte	$8A
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$FF
	.byte	$55
	.byte	$55
	.byte	$00
	.byte	$55
	.byte	$FF
	.byte	$55
	.byte	$00
	.byte	$ED
	.byte	$8D
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$FF
	.byte	$00
	.byte	$55
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
_global_system:
	.addr	_system_storage

.segment	"BSS"

_io_bank_value_kernel:
	.res	1,$00
_overlay_bank_value_kernel:
	.res	1,$00
_system_storage:
	.res	5,$00

; ---------------------------------------------------------------
; unsigned char __near__ Sys_InitSystem (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_InitSystem: near

.segment	"OVERLAY_STARTUP"

;
; if (Sys_AutoDetectMachine() == false)
;
	jsr     _Sys_AutoDetectMachine
	cmp     #$00
	bne     L0079
;
; return false;
;
	tax
	rts
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
L0079:	lda     #$00
	jsr     _Sys_SwapIOPage
;
; R8(VICKY_TEXT_CURSOR_CHAR) = 7; // 18=light 4x4 grid char, 181=medium box; 227=empty box; 7=filled space=CH_HFILL_UP_8
;
	lda     #$07
	sta     $D012
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; if (Sys_AutoConfigure() == false)
;
	jsr     _Sys_AutoConfigure
	cmp     #$00
	bne     L0083
;
; return false;
;
	tax
	rts
;
; return true;
;
L0083:	ldx     #$00
	lda     #$01
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Sys_AutoConfigure (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_AutoConfigure: near

.segment	"OVERLAY_STARTUP"

;
; Sys_SetGammaMode(true);
;
	lda     #$01
	jsr     _Sys_SetGammaMode
;
; switch (global_system->model_number_)
;
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	ldx     #$00
	lda     (ptr1)
;
; }
;
	cmp     #$02
	beq     L009E
	cmp     #$03
	beq     L009E
	cmp     #$11
	beq     L009E
	cmp     #$12
	beq     L009E
	cmp     #$13
	beq     L009E
	cmp     #$14
	bne     L01F5
;
; if (Sys_DetectScreenSize() == false)
;
L009E:	jsr     _Sys_DetectScreenSize
	cmp     #$00
	bne     L00A9
;
; return false;
;
	tax
	rts
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
L00A9:	lda     #$00
	jsr     _Sys_SwapIOPage
;
; memcpy((uint8_t*)(TEXT_FORE_LUT), &standard_text_color_lut, 64);
;
	ldy     #$3F
L00B3:	lda     _standard_text_color_lut,y
	sta     $D800,y
	dey
	bpl     L00B3
;
; memcpy((uint8_t*)(TEXT_BACK_LUT), &standard_text_color_lut, 64);
;
	ldy     #$3F
L00B9:	lda     _standard_text_color_lut,y
	sta     $D840,y
	dey
	bpl     L00B9
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; break;
;
	bra     L009C
;
; return false;
;
L01F5:	txa
	rts
;
; return true;
;
L009C:	ldx     #$00
	lda     #$01
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Sys_AutoDetectMachine (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_AutoDetectMachine: near

.segment	"OVERLAY_STARTUP"

;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	jsr     decsp1
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; the_machine_id = (R8(MACHINE_ID_REGISTER) & MACHINE_MODEL_MASK);
;
	lda     $D6A7
	and     #$1F
	sta     (sp)
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; global_system->model_number_ = the_machine_id;
;
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	lda     (sp)
	sta     (ptr1)
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Sys_DetectScreenSize (void)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_DetectScreenSize: near

.segment	"OVERLAY_STARTUP"

;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	jsr     decsp7
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; the_video_mode_bits = R8(VICKY_MASTER_CTRL_REG_H);
;
	lda     $D001
	ldy     #$06
	sta     (sp),y
;
; border_x_pixels = R8(VICKY_BORDER_X_SIZE);
;
	lda     $D008
	ldx     #$00
	ldy     #$02
	jsr     staxysp
;
; border_y_pixels = R8(VICKY_BORDER_Y_SIZE);
;
	lda     $D009
	jsr     stax0sp
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; if (the_video_mode_bits & VIDEO_MODE_FREQ_BIT)
;
	ldy     #$06
	lda     (sp),y
	and     #$01
	beq     L00D0
;
; global_system->text_mem_rows_ = TEXT_ROW_COUNT_70HZ; // 2 options in JR. the_screen->height_ / TEXT_FONT_HEIGHT;
;
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	lda     #$32
;
; else
;
	bra     L01F7
;
; global_system->text_mem_rows_ = TEXT_ROW_COUNT_60HZ; // 2 options in JR. the_screen->height_ / TEXT_FONT_HEIGHT;
;
L00D0:	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	lda     #$3C
L01F7:	ldy     #$04
	sta     (ptr1),y
;
; border_x_cols = (border_x_pixels * 2) / TEXT_FONT_WIDTH;
;
	dey
	jsr     ldaxysp
	jsr     aslax1
	jsr     asrax3
	ldy     #$05
	sta     (sp),y
;
; border_y_cols = (border_y_pixels * 2) / TEXT_FONT_HEIGHT;
;
	jsr     ldax0sp
	jsr     aslax1
	jsr     asrax3
	ldy     #$04
	sta     (sp),y
;
; global_system->text_mem_cols_ = TEXT_COL_COUNT_FOR_PLOTTING; // only 1 option in JR. the_screen->width_ / TEXT_FONT_WIDTH;
;
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	lda     #$50
	dey
	sta     (ptr1),y
;
; global_system->text_cols_vis_ = global_system->text_mem_cols_ - border_x_cols;
;
	lda     _global_system+1
	sta     sreg+1
	lda     _global_system
	sta     sreg
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	lda     (ptr1),y
	sec
	ldy     #$05
	sbc     (sp),y
	ldy     #$01
	sta     (sreg),y
;
; global_system->text_rows_vis_ = global_system->text_mem_rows_ - border_y_cols;
;
	lda     _global_system+1
	sta     sreg+1
	lda     _global_system
	sta     sreg
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	ldy     #$04
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     (sp),y
	ldy     #$02
	sta     (sreg),y
;
; return true;
;
	lda     #$01
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_EnableTextModeCursor (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_EnableTextModeCursor: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	jsr     decsp2
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; the_cursor_mode_bits = R8(VICKY_TEXT_CURSOR_ENABLE);
;
	lda     $D010
	ldy     #$01
	sta     (sp),y
;
; if (enable_it)
;
	iny
	lda     (sp),y
	beq     L01FA
;
; new_mode_flag = 0xFF;
;
	lda     #$FF
;
; new_mode_flag = 0x00;
;
L01FA:	sta     (sp)
;
; the_cursor_mode_bits  = (the_cursor_mode_bits & ~CURSOR_ONOFF_BITS) | (new_mode_flag & CURSOR_ONOFF_BITS);
;
	dey
	lda     (sp),y
	and     #$FE
	sta     ptr1
	lda     (sp)
	and     #$01
	ora     ptr1
	ldy     #$01
	sta     (sp),y
;
; the_cursor_mode_bits  = (the_cursor_mode_bits & ~CURSOR_FLASH_RATE_BITS) | CURSOR_FLASH_RATE_1S; // always use 1 blink per 1 sec rate
;
	and     #$F9
	sta     (sp),y
;
; R8(VICKY_TEXT_CURSOR_ENABLE) = the_cursor_mode_bits;
;
	sta     $D010
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_SetBorderSize (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_SetBorderSize: near

.segment	"OVERLAY_STARTUP"

;
; {
;
	jsr     pusha
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	jsr     decsp2
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; R8(VICKY_BORDER_X_SIZE) = border_width;
;
	ldy     #$03
	lda     (sp),y
	sta     $D008
;
; R8(VICKY_BORDER_Y_SIZE) = border_height;
;
	dey
	lda     (sp),y
	sta     $D009
;
; if (border_width > 0 || border_height > 0)
;
	iny
	lda     (sp),y
	bne     L01FE
	dey
	lda     (sp),y
	beq     L01FD
;
; R8(VICKY_BORDER_CTRL_REG) = 1;
;
L01FE:	lda     #$01
;
; R8(VICKY_BORDER_CTRL_REG) = 0;
;
L01FD:	sta     $D004
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; border_x_cols = (border_width * 2) / TEXT_FONT_WIDTH;
;
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L01FB
	inx
L01FB:	jsr     shrax3
	ldy     #$01
	sta     (sp),y
;
; border_y_cols = (border_height * 2) / TEXT_FONT_HEIGHT;
;
	iny
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L01FC
	inx
L01FC:	jsr     shrax3
	sta     (sp)
;
; global_system->text_cols_vis_ = global_system->text_mem_cols_ - border_x_cols;
;
	lda     _global_system+1
	sta     sreg+1
	lda     _global_system
	sta     sreg
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	iny
	lda     (ptr1),y
	sec
	ldy     #$01
	sbc     (sp),y
	sta     (sreg),y
;
; global_system->text_rows_vis_ = global_system->text_mem_rows_ - border_y_cols;
;
	lda     _global_system+1
	sta     sreg+1
	lda     _global_system
	sta     sreg
	lda     _global_system+1
	sta     ptr1+1
	lda     _global_system
	sta     ptr1
	ldy     #$04
	lda     (ptr1),y
	sec
	sbc     (sp)
	ldy     #$02
	sta     (sreg),y
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_DisableIOBank (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_DisableIOBank: near

.segment	"CODE"

;
; Sys_SwapIOPage(4);
;
	lda     #$04
	jmp     _Sys_SwapIOPage

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_SwapIOPage (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_SwapIOPage: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; zp_old_io_page = R8(MMU_IO_CTRL);
;
	lda     $0001
	sta     _zp_old_io_page
;
; R8(MMU_IO_CTRL) = the_page_number;
;
	lda     (sp)
	sta     $0001
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_RestoreIOPage (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_RestoreIOPage: near

.segment	"CODE"

;
; R8(MMU_IO_CTRL) = zp_old_io_page;
;
	lda     _zp_old_io_page
	sta     $0001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Sys_UpdateRTC (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_UpdateRTC: near

.segment	"DATA"

L0136:
	.byte	$0C
	.byte	$09
	.byte	$06
	.byte	$03
	.byte	$00
L013D:
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$01
L0144:
	.byte	$3B
	.byte	$17
	.byte	$1F
	.byte	$0C
	.byte	$63

.segment	"RODATA"

L014C:
	.byte	$1F
	.byte	$1C
	.byte	$1F
	.byte	$1E
	.byte	$1F
	.byte	$1E
	.byte	$1F
	.byte	$1F
	.byte	$1E
	.byte	$1F
	.byte	$1E
	.byte	$1F

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; if (strlen(datetime_from_user) != 14 || datetime_from_user[2] != '-' ||
;
	ldy     #$0C
	jsr     subysp
	ldy     #$0D
	jsr     ldaxysp
	jsr     _strlen
	cpx     #$00
	bne     L0200
	cmp     #$0E
	bne     L021A
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	cmp     #$2D
	bne     L0200
;
; datetime_from_user[5] != '-' || datetime_from_user[8] != ' ' || datetime_from_user[11] != ':') return false;
;
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	cmp     #$2D
	bne     L0200
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	cmp     #$20
	bne     L0200
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (ptr1),y
	cmp     #$3A
	bne     L0200
	lda     #$00
	bra     L0203
L0200:	ldx     #$00
L021A:	txa
	jmp     L0134
;
; for (i = 0; i < 5; i++)
;
L0203:	sta     (sp),y
	cmp     #$05
	jcs     L020A
;
; this_digit = datetime_from_user[string_offsets[i]];
;
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0D
	lda     (sp),y
	tay
	lda     L0136,y
	jsr     tosadda0
	ldy     #$00
	jsr     ldaidx
	ldy     #$0A
	sta     (sp),y
;
; if (this_digit < CH_ZERO || this_digit > CH_NINE)
;
	sec
	sbc     #$30
	bvc     L0173
	eor     #$80
L0173:	bmi     L0206
	lda     (sp),y
	sec
	sbc     #$3A
	bvs     L0175
	eor     #$80
L0175:	bmi     L0206
	ldx     #$00
	bra     L0208
;
; return false;
;
L0206:	ldx     #$00
	txa
	jmp     L0134
;
; tens_digit = this_digit - CH_ZERO;
;
L0208:	lda     (sp),y
	bpl     L017A
	dex
L017A:	ldy     #$30
	jsr     decaxy
	cmp     #$80
	ldy     #$09
	sta     (sp),y
;
; this_digit = datetime_from_user[string_offsets[i] + 1];
;
	ldy     #$0B
	lda     (sp),y
	tay
	ldx     #$00
	lda     L0136,y
	ina
	bne     L0181
	inx
L0181:	clc
	ldy     #$0C
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$00
	jsr     ldaidx
	ldy     #$0A
	sta     (sp),y
;
; if (this_digit < CH_ZERO || this_digit > CH_NINE)
;
	sec
	sbc     #$30
	bvc     L0185
	eor     #$80
L0185:	bmi     L0209
	lda     (sp),y
	sec
	sbc     #$3A
	bvs     L0187
	eor     #$80
L0187:	bpl     L0182
;
; return false;
;
L0209:	ldx     #$00
	txa
	jmp     L0134
;
; rtc_array[i] = (this_digit - CH_ZERO) + (tens_digit * 10);
;
L0182:	lda     #$04
	jsr     leaa0sp
	iny
	clc
	adc     (sp),y
	bcc     L018C
	inx
L018C:	jsr     pushax
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	bpl     L018F
	dex
L018F:	ldy     #$30
	jsr     decaxy
	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (sp),y
	bpl     L0191
	dex
L0191:	jsr     mulax10
	jsr     tosaddax
	ldy     #$00
	jsr     staspidx
;
; for (i = 0; i < 5; i++)
;
	ldy     #$0B
	lda     (sp),y
	ina
	jmp     L0203
;
; for (i = 0; i < 5; i++)
;
L020A:	lda     #$00
L0217:	sta     (sp),y
	cmp     #$05
	bcs     L0193
;
; if (rtc_array[i] > bounds[i])
;
	lda     #$04
	jsr     leaa0sp
	clc
	adc     (sp),y
	bcc     L019D
	inx
L019D:	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$0D
	lda     (sp),y
	tay
	lda     L0144,y
	jsr     tosicmp0
	bcc     L0194
	beq     L0194
;
; return false;
;
	ldx     #$00
	txa
	jmp     L0134
;
; for (i = 0; i < 5; i++)
;
L0194:	ldy     #$0B
	lda     (sp),y
	ina
	bra     L0217
;
; if (!rtc_array[2] || !rtc_array[3]) return false;
;
L0193:	ldy     #$06
	lda     (sp),y
	beq     L020D
	iny
	lda     (sp),y
	beq     L020D
	ldx     #$00
	bra     L020F
L020D:	tax
	jmp     L0134
;
; days = month_days[rtc_array[3]-1];
;
L020F:	lda     (sp),y
	jsr     decax1
	sta     ptr1
	txa
	clc
	adc     #>(L014C)
	sta     ptr1+1
	ldy     #<(L014C)
	lda     (ptr1),y
	ldy     #$01
	sta     (sp),y
;
; if (rtc_array[3] == 2 && rtc_array[4] % 4 == 0) ++days;
;
	ldy     #$07
	lda     (sp),y
	cmp     #$02
	bne     L01AB
	iny
	lda     (sp),y
	and     #$03
	bne     L01AB
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
;
; if (rtc_array[2] > days) return false;
;
L01AB:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$01
	sbc     (sp),y
	bcc     L0212
	beq     L0212
	txa
	jmp     L0134
;
; for (i = 0; i < 5; i++)
;
L0212:	txa
	ldy     #$0B
L0218:	sta     (sp),y
	cmp     #$05
	bcs     L01B8
;
; rtc_array[i] = Sys_DecimalToBCD(rtc_array[i]);
;
	lda     #$04
	jsr     leaa0sp
	clc
	adc     (sp),y
	bcc     L01C1
	inx
L01C1:	jsr     pushax
	lda     #$06
	jsr     leaa0sp
	ldy     #$0D
	clc
	adc     (sp),y
	bcc     L01C5
	inx
L01C5:	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     _Sys_DecimalToBCD
	ldy     #$00
	jsr     staspidx
;
; for (i = 0; i < 5; i++)
;
	ldy     #$0B
	lda     (sp),y
	ina
	bra     L0218
;
; asm("PHP");
;
L01B8:	php
;
; asm("SEI");
;
	sei
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; old_control = R8(RTC_CONTROL);
;
	lda     $D69E
	sta     (sp)
;
; R8(RTC_CONTROL) = old_control | MASK_RTC_CTRL_UTI; // stop it from updating external registers
;
	ora     #$08
	sta     $D69E
;
; rtc_addr = (uint8_t*)RTC_MINUTES;
;
	ldx     #$D6
	lda     #$92
	ldy     #$02
	jsr     staxysp
;
; for (i = 0; i < 5; i++)
;
	lda     #$00
	ldy     #$0B
L0219:	sta     (sp),y
	cmp     #$05
	bcs     L01D7
;
; R8(MMU_IO_CTRL) = VICKY_IO_PAGE_REGISTERS; // just make sure i/o page is still up.
;
	stz     $0001
;
; rtc_addr += rtc_offsets[i];
;
	lda     (sp),y
	tay
	lda     L013D,y
	ldx     #$00
	ldy     #$02
	jsr     addeqysp
;
; R8(rtc_addr) = rtc_array[i];
;
	ldy     #$05
	jsr     pushwysp
	lda     #$06
	jsr     leaa0sp
	ldy     #$0D
	clc
	adc     (sp),y
	bcc     L01EB
	inx
L01EB:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
;
; for (i = 0; i < 5; i++)
;
	ldy     #$0B
	lda     (sp),y
	ina
	bra     L0219
;
; R8(RTC_CONTROL) = (old_control | MASK_RTC_CTRL_12_24) & ~MASK_RTC_CTRL_UTI;
;
L01D7:	lda     (sp)
	ora     #$02
	and     #$F7
	sta     $D69E
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; asm("PLP"); // restore the caller's interrupt state
;
	plp
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
L0134:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Sys_SetGammaMode (unsigned char)
; ---------------------------------------------------------------

.segment	"OVERLAY_STARTUP"

.proc	_Sys_SetGammaMode: near

.segment	"OVERLAY_STARTUP"

;
; {
;
	jsr     pusha
;
; if (enable_it)
;
	jsr     decsp2
	ldy     #$02
	lda     (sp),y
	beq     L0053
;
; new_mode_flag = 0xFF;
;
	lda     #$FF
;
; new_mode_flag = 0x00;
;
L0053:	sta     (sp)
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; the_gamma_mode_bits = R8(VICKY_MASTER_CTRL_REG_L);
;
	lda     $D000
	ldy     #$01
	sta     (sp),y
;
; the_gamma_mode_bits  = (the_gamma_mode_bits & ~GAMMA_MODE_ONOFF_BITS) | (new_mode_flag & GAMMA_MODE_ONOFF_BITS);
;
	and     #$BF
	sta     ptr1
	lda     (sp)
	and     #$40
	ora     ptr1
	ldy     #$01
	sta     (sp),y
;
; R8(VICKY_MASTER_CTRL_REG_L) = the_gamma_mode_bits;
;
	sta     $D000
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Sys_DecimalToBCD (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Sys_DecimalToBCD: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t  bcd_number = 0;
;
	lda     #$00
	jsr     pusha
;
; while (dec_number >= 10)
;
	bra     L006E
;
; ++bcd_number;
;
L006C:	clc
	lda     #$01
	adc     (sp)
	sta     (sp)
;
; dec_number -= 10;
;
	ldy     #$01
	lda     (sp),y
	sec
	sbc     #$0A
	sta     (sp),y
;
; while (dec_number >= 10)
;
L006E:	ldy     #$01
	lda     (sp),y
	cmp     #$0A
	bcs     L006C
;
; bcd_number = bcd_number << 4;
;
	lda     (sp)
	asl     a
	asl     a
	asl     a
	asl     a
	sta     (sp)
;
; return (bcd_number | dec_number);
;
	ldx     #$00
	ldy     #$01
	lda     (sp),y
	ora     (sp)
;
; }
;
	jmp     incsp2

.endproc
