; Derived from Micah Bly / Wildbits File Manager, GPL-3.0.
; Imported from cc65 2.19 output as the behavior-preserving conversion baseline.
;
; File generated by cc65 v 2.18 - Git 5552824
;
	.fopt		compiler,"cc65 v 2.18 - Git 5552824"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_General_Strnlen
	.import		_Keyboard_GetChar
	.export		_Text_CopyMemBoxLinearBuffer
	.export		_Text_ClearScreen
	.export		_Text_FillMemory
	.export		_Text_FillBox
	.export		_Text_FillBoxAttrOnly
	.export		_Text_SetXY
	.export		_Text_SetCharAtXY
	.export		_Text_SetColorAtXY
	.export		_Text_SetCharAndColorAtXY
	.import		_Text_SetChar
	.export		_Text_SetAttr
	.export		_Text_SetCharAndColor
	.export		_Text_DrawCharsAtXY
	.import		_Text_DrawChars
	.export		_Text_DrawHLine
	.export		_Text_DrawVLine
	.export		_Text_DrawBoxCoordsFancy
	.export		_Text_DrawStringAtXY
	.export		_Text_DrawString
	.export		_Text_DrawWindow
	.export		_Text_DisplayDialog
	.export		_Text_DisplayTextEntryDialog
	.export		_Text_GetStringFromUser
	.import		_Sys_EnableTextModeCursor
	.import		_Sys_SwapIOPage
	.import		_Sys_RestoreIOPage
	.import		_memcpy
	.import		_memmove
	.import		_memset
	.importzp	_zp_ptr
	.importzp	_zp_vram_ptr
	.importzp	_zp_x
	.importzp	_zp_y
	.import		_Text_SetMemLocForXY
	.export		_Text_FillMemoryBoxBoth
	.export		_Text_FillMemoryBox

; ---------------------------------------------------------------
; unsigned char __near__ Text_CopyMemBoxLinearBuffer (__near__ unsigned char *, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_CopyMemBoxLinearBuffer: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (x2 < x1)
;
	jsr     decsp5
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	ldy     #$0A
	cmp     (sp),y
	bcs     L0079
;
; x2 = x1;
;
	lda     (sp),y
	ldy     #$08
	sta     (sp),y
;
; if (y2 < y1)
;
L0079:	ldy     #$07
	lda     (sp),y
	ldy     #$09
	cmp     (sp),y
	bcs     L007D
;
; y2 = y1;
;
	lda     (sp),y
	ldy     #$07
	sta     (sp),y
;
; if (x1 > SCREEN_LAST_COL)
;
L007D:	ldy     #$0A
	lda     (sp),y
	cmp     #$50
	bcc     L0081
;
; return false;
;
	txa
	jmp     L0078
;
; if (x2 > SCREEN_LAST_COL)
;
L0081:	ldy     #$08
	lda     (sp),y
	cmp     #$50
	bcc     L0085
;
; x2 = SCREEN_LAST_COL;
;
	lda     #$4F
	sta     (sp),y
;
; if (y1 > SCREEN_LAST_ROW)
;
L0085:	iny
	lda     (sp),y
	cmp     #$3C
	bcc     L008B
;
; return false;
;
	txa
	jmp     L0078
;
; if (y2 > SCREEN_LAST_ROW)
;
L008B:	ldy     #$07
	lda     (sp),y
	cmp     #$3C
	bcc     L008F
;
; y2 = SCREEN_LAST_ROW;
;
	lda     #$3B
	sta     (sp),y
;
; orig_vram_loc = zp_vram_ptr;
;
L008F:	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	ldy     #$03
	jsr     staxysp
;
; Text_SetXY(x1,y1);
;
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     _Text_SetXY
;
; if (for_attr)
;
	ldy     #$05
	lda     (sp),y
	beq     L009A
;
; Sys_SwapIOPage(VICKY_IO_PAGE_ATTR_MEM);
;
	lda     #$03
;
; else
;
	bra     L040D
;
; Sys_SwapIOPage(VICKY_IO_PAGE_CHAR_MEM);
;
L009A:	lda     #$02
L040D:	jsr     _Sys_SwapIOPage
;
; the_buffer_loc = the_buffer;
;
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$01
	jsr     staxysp
;
; the_write_len = x2 - x1 + 1;
;
	ldy     #$08
	lda     (sp),y
	sec
	ldy     #$0A
	sbc     (sp),y
	ina
	sta     (sp)
;
; for (; y1 <= y2; y1++)
;
	dey
L0410:	lda     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	bcc     L00A9
	bne     L00A7
;
; if (to_screen)
;
L00A9:	dey
	lda     (sp),y
	beq     L00AC
;
; memcpy(zp_vram_ptr, the_buffer_loc, the_write_len);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
;
; else
;
	bra     L0414
;
; memcpy(the_buffer_loc, zp_vram_ptr, the_write_len);
;
L00AC:	ldy     #$04
	jsr     pushwysp
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
L0414:	jsr     pushax
	ldy     #$04
	lda     (sp),y
	ldx     #$00
	jsr     _memcpy
;
; the_buffer_loc += the_write_len;
;
	lda     (sp)
	ldx     #$00
	ldy     #$01
	jsr     addeqysp
;
; zp_vram_ptr += SCREEN_NUM_COLS;
;
	lda     #$50
	clc
	adc     _zp_vram_ptr
	sta     _zp_vram_ptr
	bcc     L00BB
	inc     _zp_vram_ptr+1
;
; for (; y1 <= y2; y1++)
;
L00BB:	ldy     #$09
	lda     (sp),y
	ina
	sta     (sp),y
	bra     L0410
;
; Sys_RestoreIOPage();
;
L00A7:	jsr     _Sys_RestoreIOPage
;
; zp_vram_ptr = orig_vram_loc;
;
	ldy     #$04
	jsr     ldaxysp
	sta     _zp_vram_ptr
	stx     _zp_vram_ptr+1
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
L0078:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Text_ClearScreen (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_ClearScreen: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	jsr     decsp1
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; Text_FillMemory(PARAM_FOR_TEXT_CHAR, ' ');
;
	lda     #$00
	jsr     pusha
	lda     #$20
	jsr     _Text_FillMemory
;
; Text_FillMemory(PARAM_FOR_TEXT_ATTR, the_attribute_value);
;
	lda     #$01
	jsr     pusha
	tay
	lda     (sp),y
	jsr     _Text_FillMemory
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_FillMemory (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_FillMemory: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (for_attr)
;
	jsr     decsp2
	ldy     #$03
	lda     (sp),y
	beq     L0010
;
; Sys_SwapIOPage(VICKY_IO_PAGE_ATTR_MEM);
;
	tya
;
; else
;
	bra     L0415
;
; Sys_SwapIOPage(VICKY_IO_PAGE_CHAR_MEM);
;
L0010:	lda     #$02
L0415:	jsr     _Sys_SwapIOPage
;
; the_write_loc = (uint8_t*)SCREEN_TEXT_MEMORY_LOC;
;
	ldx     #$C0
	lda     #$00
	jsr     stax0sp
;
; memset(the_write_loc, the_fill, SCREEN_TOTAL_BYTES);
;
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldx     #$12
	lda     #$C0
	jsr     _memset
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_FillBox (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_FillBox: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; dx = x2 - x1 + 1;
;
	jsr     decsp3
	ldy     #$07
	lda     (sp),y
	sec
	ldy     #$09
	sbc     (sp),y
	ina
	ldy     #$01
	sta     (sp),y
;
; dy = y2 - y1 + 1;
;
	ldy     #$06
	lda     (sp),y
	sec
	ldy     #$08
	sbc     (sp),y
	ina
	ldy     #$02
	sta     (sp),y
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; return Text_FillMemoryBoxBoth(x1, y1, dx, dy, the_char, the_attribute_value);
;
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_FillMemoryBoxBoth
;
; }
;
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_FillBoxAttrOnly (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_FillBoxAttrOnly: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (x1 > x2 || y1 > y2)
;
	jsr     decsp3
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$06
	sbc     (sp),y
	sta     tmp1
	lda     tmp1
	beq     L0416
	bcs     L041A
L0416:	iny
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	sta     tmp1
	lda     tmp1
	beq     L00DE
	bcc     L00DE
;
; return false;
;
L041A:	txa
	bra     L00DD
;
; dx = x2 - x1 + 1;
;
L00DE:	iny
	lda     (sp),y
	sec
	ldy     #$08
	sbc     (sp),y
	ina
	ldy     #$01
	sta     (sp),y
;
; dy = y2 - y1 + 1;
;
	ldy     #$05
	lda     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	ina
	ldy     #$02
	sta     (sp),y
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; return Text_FillMemoryBox(x1, y1, dx, dy, PARAM_FOR_TEXT_ATTR, the_attribute_value);
;
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_FillMemoryBox
;
; }
;
L00DD:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ Text_SetXY (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetXY: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; zp_x = x;
;
	ldy     #$01
	lda     (sp),y
	sta     _zp_x
;
; zp_y = y;
;
	lda     (sp)
	sta     _zp_y
;
; Text_SetMemLocForXY();
;
	jsr     _Text_SetMemLocForXY
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_SetCharAtXY (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetCharAtXY: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; Text_SetXY(x, y);
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_SetChar(the_char);
;
	lda     (sp)
	jsr     _Text_SetChar
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_SetColorAtXY (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetColorAtXY: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	jsr     decsp1
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; Text_SetXY(x, y);
;
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_SetAttr(the_attribute_value);
;
	lda     (sp)
	jsr     _Text_SetAttr
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_SetCharAndColorAtXY (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetCharAndColorAtXY: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; Text_SetXY(x, y);
;
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_SetCharAndColor(the_char, fore_color, back_color);
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _Text_SetCharAndColor
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_SetAttr (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetAttr: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; Sys_SwapIOPage(VICKY_IO_PAGE_ATTR_MEM);
;
	lda     #$03
	jsr     _Sys_SwapIOPage
;
; *zp_vram_ptr = the_attribute_value;
;
	lda     _zp_vram_ptr+1
	sta     ptr1+1
	lda     _zp_vram_ptr
	sta     ptr1
	lda     (sp)
	sta     (ptr1)
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; zp_vram_ptr++;
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	ina
	bne     L0123
	inx
L0123:	sta     _zp_vram_ptr
	stx     _zp_vram_ptr+1
;
; zp_x++;
;
	inc     _zp_x
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; if (zp_x > SCREEN_LAST_COL && zp_y < SCREEN_LAST_ROW)
;
	lda     _zp_x
	cmp     #$50
	bcc     L041E
	lda     _zp_y
	cmp     #$3B
	bcs     L041E
;
; zp_x = 0;
;
	stz     _zp_x
;
; zp_y++;
;
	inc     _zp_y
;
; R8(VICKY_TEXT_Y_POS) = zp_y;
;
	lda     _zp_y
	sta     $D016
;
; R8(VICKY_TEXT_X_POS) = zp_x;
;
L041E:	lda     _zp_x
	sta     $D014
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_SetCharAndColor (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_SetCharAndColor: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	jsr     decsp1
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; Sys_SwapIOPage(VICKY_IO_PAGE_ATTR_MEM);
;
	lda     #$03
	jsr     _Sys_SwapIOPage
;
; *zp_vram_ptr = the_attribute_value;
;
	lda     _zp_vram_ptr+1
	sta     ptr1+1
	lda     _zp_vram_ptr
	sta     ptr1
	lda     (sp)
	sta     (ptr1)
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; Sys_SwapIOPage(VICKY_IO_PAGE_CHAR_MEM);
;
	lda     #$02
	jsr     _Sys_SwapIOPage
;
; *zp_vram_ptr = the_char;
;
	lda     _zp_vram_ptr+1
	sta     ptr1+1
	lda     _zp_vram_ptr
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	sta     (ptr1)
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; zp_vram_ptr++;
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	ina
	bne     L014A
	inx
L014A:	sta     _zp_vram_ptr
	stx     _zp_vram_ptr+1
;
; zp_x++;
;
	inc     _zp_x
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; if (zp_x > SCREEN_LAST_COL && zp_y < SCREEN_LAST_ROW)
;
	lda     _zp_x
	cmp     #$50
	bcc     L0422
	lda     _zp_y
	cmp     #$3B
	bcs     L0422
;
; zp_x = 0;
;
	stz     _zp_x
;
; zp_y++;
;
	inc     _zp_y
;
; R8(VICKY_TEXT_Y_POS) = zp_y;
;
	lda     _zp_y
	sta     $D016
;
; R8(VICKY_TEXT_X_POS) = zp_x;
;
L0422:	lda     _zp_x
	sta     $D014
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ Text_DrawCharsAtXY (unsigned char, unsigned char, __near__ unsigned char *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawCharsAtXY: near

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; Text_SetXY(x, y);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_SetXY
;
; zp_ptr = the_buffer;
;
	ldy     #$03
	jsr     ldaxysp
	sta     _zp_ptr
	stx     _zp_ptr+1
;
; Text_DrawChars(the_len);
;
	jsr     ldax0sp
	jsr     _Text_DrawChars
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ Text_DrawHLine (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawHLine: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (the_draw_choice == CHAR_ONLY)
;
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	bne     L0162
;
; Text_FillMemoryBox(x, y, the_line_len, 1, PARAM_FOR_TEXT_CHAR, the_char);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	dea
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _Text_FillMemoryBox
;
; else
;
	jmp     incsp8
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
L0162:	ldy     #$03
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	dey
	lda     (sp),y
	ora     ptr1
	sta     (sp)
;
; if (the_draw_choice == ATTR_ONLY)
;
	dey
	lda     (sp),y
	cmp     #$01
	bne     L0170
;
; Text_FillMemoryBox(x, y, the_line_len, 1, PARAM_FOR_TEXT_ATTR, the_attribute_value);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_FillMemoryBox
;
; else
;
	jmp     incsp8
;
; Text_FillMemoryBoxBoth(x, y, the_line_len, 1, the_char, the_attribute_value);
;
L0170:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_FillMemoryBoxBoth
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ Text_DrawVLine (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawVLine: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; switch (the_draw_choice)
;
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
;
; }
;
	beq     L0430
	cmp     #$01
	beq     L042A
	cmp     #$02
	beq     L042D
	bra     L042D
;
; for (dy = 0; dy < the_line_len; dy++)
;
L0430:	sta     (sp)
	ldy     #$05
	cmp     (sp),y
	bcc     L0433
;
; }
;
	jmp     incsp8
;
; Text_SetCharAtXY(x, y + dy, the_char);
;
L0433:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAtXY
;
; for (dy = 0; dy < the_line_len; dy++)
;
	lda     (sp)
	ina
	bra     L0430
;
; for (dy = 0; dy < the_line_len; dy++)
;
L042A:	dea
L0431:	sta     (sp)
	ldy     #$05
	cmp     (sp),y
	bcs     L0184
;
; Text_SetColorAtXY(x, y + dy, fore_color, back_color);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_SetColorAtXY
;
; for (dy = 0; dy < the_line_len; dy++)
;
	lda     (sp)
	ina
	bra     L0431
;
; for (dy = 0; dy < the_line_len; dy++)
;
L042D:	lda     #$00
L0432:	sta     (sp)
	ldy     #$05
	cmp     (sp),y
	bcs     L0184
;
; Text_SetCharAndColorAtXY(x, y + dy, the_char, fore_color, back_color);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAndColorAtXY
;
; for (dy = 0; dy < the_line_len; dy++)
;
	lda     (sp)
	ina
	bra     L0432
;
; }
;
L0184:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ Text_DrawBoxCoordsFancy (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawBoxCoordsFancy: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; dx = x2 - x1 + 0;
;
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	sta     (sp)
;
; dy = y2 - y1 + 0;
;
	ldy     #$04
	lda     (sp),y
	sec
	ldy     #$06
	sbc     (sp),y
	ldy     #$01
	sta     (sp),y
;
; Text_DrawHLine(x1+1, y1, dx, SC_HLINE, fore_color, back_color, CHAR_AND_ATTR);
;
	ldy     #$07
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     #$96
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawHLine
;
; Text_DrawHLine(x1+1, y2, dx, SC_HLINE, fore_color, back_color, CHAR_AND_ATTR);
;
	ldy     #$07
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     #$96
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawHLine
;
; Text_DrawVLine(x2, y1+1, dy, SC_VLINE, fore_color, back_color, CHAR_AND_ATTR);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$82
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawVLine
;
; Text_DrawVLine(x1, y1+1, dy, SC_VLINE, fore_color, back_color, CHAR_AND_ATTR);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     #$82
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawVLine
;
; Text_SetCharAndColorAtXY(x1, y1, SC_ULCORNER, fore_color, back_color);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$A0
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAndColorAtXY
;
; Text_SetCharAndColorAtXY(x2, y1, SC_URCORNER, fore_color, back_color);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$A1
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAndColorAtXY
;
; Text_SetCharAndColorAtXY(x2, y2, SC_LRCORNER, fore_color, back_color);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$A3
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAndColorAtXY
;
; Text_SetCharAndColorAtXY(x1, y2, SC_LLCORNER, fore_color, back_color);
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$A2
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _Text_SetCharAndColorAtXY
;
; zp_x++;
;
	inc     _zp_x
;
; Sys_SwapIOPage(VICKY_IO_PAGE_REGISTERS);
;
	lda     #$00
	jsr     _Sys_SwapIOPage
;
; if (zp_x > SCREEN_LAST_COL && zp_y < SCREEN_LAST_ROW)
;
	lda     _zp_x
	cmp     #$50
	bcc     L043B
	lda     _zp_y
	cmp     #$3B
	bcs     L043B
;
; zp_x = 0;
;
	stz     _zp_x
;
; zp_y++;
;
	inc     _zp_y
;
; R8(VICKY_TEXT_Y_POS) = zp_y;
;
	lda     _zp_y
	sta     $D016
;
; R8(VICKY_TEXT_X_POS) = zp_x;
;
L043B:	lda     _zp_x
	sta     $D014
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_DrawStringAtXY (unsigned char, unsigned char, __near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawStringAtXY: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; Text_SetXY(x, y);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_SetXY
;
; Text_DrawString(the_string, fore_color, back_color);
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     _Text_DrawString
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_DrawString (__near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawString: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; the_attribute_value = ((fore_color << 4) | back_color);
;
	jsr     decsp3
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	ldx     #$00
	dey
	lda     (sp),y
	ora     ptr1
	dey
	sta     (sp),y
;
; if (!the_string || zp_x >= SCREEN_NUM_COLS || zp_y >= SCREEN_NUM_ROWS) return false;
;
	ldy     #$06
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0443
	lda     _zp_x
	cmp     #$50
	bcs     L0440
	lda     _zp_y
	cmp     #$3C
	bcc     L0217
L0440:	txa
L0443:	jmp     incsp7
;
; the_len = General_Strnlen(the_string, SCREEN_NUM_COLS - zp_x); // can't be wider than the screen anyway
;
L0217:	ldy     #$08
	jsr     pushwysp
	lda     #$50
	sec
	sbc     _zp_x
	ldx     #$00
	jsr     _General_Strnlen
	sta     (sp)
;
; max_col = SCREEN_NUM_COLS - 1;
;
	lda     #$4F
	ldy     #$01
	sta     (sp),y
;
; if (zp_x + the_len > max_col)
;
	ldx     #$00
	lda     (sp)
	clc
	adc     _zp_x
	bcc     L043C
	inx
L043C:	sec
	ldy     #$01
	sbc     (sp),y
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	bcc     L0221
	beq     L0221
;
; the_len = (max_col - zp_x) + 1;
;
	lda     (sp),y
	sec
	sbc     _zp_x
	ina
	sta     (sp)
;
; Sys_SwapIOPage(VICKY_IO_PAGE_CHAR_MEM);
;
L0221:	lda     #$02
	jsr     _Sys_SwapIOPage
;
; memcpy(zp_vram_ptr, the_string, the_len);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$0A
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	ldx     #$00
	jsr     _memcpy
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; Sys_SwapIOPage(VICKY_IO_PAGE_ATTR_MEM);
;
	lda     #$03
	jsr     _Sys_SwapIOPage
;
; memset(zp_vram_ptr, the_attribute_value, the_len);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	jsr     _memset
;
; Sys_RestoreIOPage();
;
	jsr     _Sys_RestoreIOPage
;
; if (zp_x + the_len >= SCREEN_NUM_COLS) {
;
	ldx     #$00
	lda     (sp)
	clc
	adc     _zp_x
	bcc     L043D
	inx
L043D:	cmp     #$50
	txa
	sbc     #$00
	bcc     L0442
;
; if (zp_y < SCREEN_LAST_ROW) Text_SetXY(0, zp_y + 1);
;
	lda     _zp_y
	cmp     #$3B
	bcs     L0237
	lda     #$00
	jsr     pusha
	lda     _zp_y
	ina
	bne     L043F
;
; else Text_SetXY(SCREEN_LAST_COL, SCREEN_LAST_ROW);
;
	bra     L043F
L0237:	lda     #$4F
	jsr     pusha
	lda     #$3B
;
; } else Text_SetXY(zp_x + the_len, zp_y);
;
	bra     L043F
L0442:	lda     (sp)
	clc
	adc     _zp_x
	jsr     pusha
	lda     _zp_y
L043F:	jsr     _Text_SetXY
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_DrawWindow (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, __near__ unsigned char *, __near__ unsigned char *, __near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DrawWindow: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (attr_save_mem != NULL && char_save_mem != NULL)
;
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L024A
	iny
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L024A
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)char_save_mem, x1, y1, x2, y2, PARAM_COPY_FROM_SCREEN, PARAM_FOR_TEXT_CHAR);
;
	ldy     #$07
	jsr     pushwysp
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _Text_CopyMemBoxLinearBuffer
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)attr_save_mem, x1, y1, x2, y2, PARAM_COPY_FROM_SCREEN, PARAM_FOR_TEXT_ATTR);
;
	ldy     #$05
	jsr     pushwysp
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	ldy     #$10
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	ina
	jsr     _Text_CopyMemBoxLinearBuffer
;
; if (clear_first)
;
L024A:	ldy     #$01
	lda     (sp),y
	beq     L0262
;
; if (Text_FillBox(x1, y1, x2, y2, CH_SPACE, accent_color, back_color) == false)
;
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     _Text_FillBox
	cmp     #$00
	bne     L0262
;
; return false;
;
	tax
	jmp     L0249
;
; Text_DrawBoxCoordsFancy(x1, y1, x2, y2, accent_color, back_color);
;
L0262:	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	jsr     _Text_DrawBoxCoordsFancy
;
; if (enclose_header)
;
	lda     (sp)
	beq     L0273
;
; uint8_t num_cols = (x2 - x1) + 1;
;
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$0E
	sbc     (sp),y
	ina
	jsr     pusha
;
; Text_DrawHLine(x1 + 1, y1 + 2, num_cols - 2, SC_HLINE, accent_color, back_color, CHAR_AND_ATTR);
;
	ldy     #$0F
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$02
	jsr     pusha
	lda     #$96
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     _Text_DrawHLine
;
; Text_SetCharAtXY(x1, y1 + 2, SC_T_RIGHT);
;
	ldy     #$0F
	lda     (sp),y
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     #$9A
	jsr     _Text_SetCharAtXY
;
; Text_SetCharAtXY(x2, y1 + 2, SC_T_LEFT);
;
	ldy     #$0D
	lda     (sp),y
	jsr     pusha
	ldy     #$0F
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     #$9E
	jsr     _Text_SetCharAtXY
;
; }
;
	jsr     incsp1
;
; if (the_header_text != NULL)
;
L0273:	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L0289
;
; Text_DrawStringAtXY(x1 + 1, y1 + 1, the_header_text, fore_color, back_color);
;
	ldy     #$0E
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	ina
	jsr     pusha
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0D
	lda     (sp),y
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	jsr     _Text_DrawStringAtXY
;
; return true;
;
L0289:	ldx     #$00
	lda     #$01
;
; }
;
L0249:	ldy     #$0F
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; signed char __near__ Text_DisplayDialog (__near__ struct TextDialogTemplate *, __near__ unsigned char *, __near__ unsigned char *, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DisplayDialog: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t   total_btn_width = 0;
;
	jsr     decsp7
	lda     #$00
	jsr     pusha
;
; uint8_t   x1 = the_dialog_template->x_;
;
	ldy     #$12
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha
;
; uint8_t   y1 = the_dialog_template->y_;
;
	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha
;
; uint8_t   x2 = x1 + the_dialog_template->width_;
;
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
;
; uint8_t   y2 = y1 + the_dialog_template->height_;
;
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$17
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
;
; int8_t   the_result = DIALOG_ERROR;
;
	lda     #$FE
	jsr     pusha
;
; if (the_dialog_template->num_buttons_ < 1 || the_dialog_template->num_buttons_ > 3)
;
	jsr     decsp1
	ldy     #$18
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jeq     L045F
	ldy     #$18
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	cmp     #$04
;
; return the_result;
;
	jcs     L045F
;
; if (the_dialog_template->title_text_ == NULL || the_dialog_template->body_text_ == NULL)
;
	ldy     #$18
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaxidx
	cpx     #$00
	bne     L0454
	cmp     #$00
	beq     L02A3
L0454:	ldy     #$18
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
	cpx     #$00
	bne     L02A2
	cmp     #$00
	bne     L02A2
;
; return the_result;
;
L02A3:	ldy     #$01
	jmp     L045C
;
; avail_width = the_dialog_template->width_ - 2; // account for draw characters on edges
;
L02A2:	ldy     #$18
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	sec
	sbc     #$02
	ldy     #$0A
	sta     (sp),y
;
; for (i = 0; i < the_dialog_template->num_buttons_; i++)
;
	lda     #$00
L0457:	sta     (sp)
	ldx     #$00
	lda     (sp)
	bpl     L02B2
	dex
L02B2:	jsr     pushax
	ldy     #$1A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jsr     tosicmp0
	jcs     L02AC
;
; if (the_dialog_template->btn_label_[i] == NULL)
;
	ldy     #$18
	jsr     ldaxysp
	ldy     #$09
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	bpl     L02B8
	dex
L02B8:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	bne     L02B5
	cmp     #$00
	bne     L02B5
;
; return the_result;
;
	ldy     #$01
	jmp     L045C
;
; btn_width[i] = (uint8_t)General_Strnlen(the_dialog_template->btn_label_[i], TEXT_DIALOG_MAX_BTN_LABEL_LEN) + 2; // +2 because we force 2 spaces to right of all buttons
;
L02B5:	lda     #$0B
	jsr     leaa0sp
	clc
	adc     (sp)
	bcc     L02BF
	inx
L02BF:	jsr     pushax
	ldy     #$1A
	jsr     ldaxysp
	ldy     #$09
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L02C3
	dex
L02C3:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	ldx     #$00
	lda     #$4D
	jsr     _General_Strnlen
	clc
	adc     #$02
	ldy     #$00
	jsr     staspidx
;
; total_btn_width += btn_width[i];
;
	lda     #$0B
	jsr     leaa0sp
	clc
	adc     (sp)
	bcc     L02C9
	inx
L02C9:	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$06
	clc
	adc     (sp),y
	sta     (sp),y
;
; for (i = 0; i < the_dialog_template->num_buttons_; i++)
;
	lda     (sp)
	ina
	jmp     L0457
;
; if (total_btn_width > avail_width)
;
L02AC:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$0A
	sbc     (sp),y
	bcc     L02CA
	beq     L02CA
;
; return the_result;
;
	ldy     #$01
	jmp     L045C
;
; x1, y1,
;
L02CA:	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
;
; accent_color, fore_color, back_color,
;
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	ldy     #$16
	lda     (sp),y
	jsr     pusha
;
; the_dialog_template->title_text_,
;
	ldy     #$1F
	jsr     ldaxysp
	ldy     #$06
	jsr     pushwidx
;
; char_save_mem, attr_save_mem,
;
	ldy     #$21
	jsr     pushwysp
	ldy     #$21
	jsr     pushwysp
;
; PARAM_CLEAR_FIRST,
;
	lda     #$01
	jsr     pusha
;
; ) == false)
;
	jsr     _Text_DrawWindow
	cmp     #$00
;
; return the_result;
;
	jeq     L045F
;
; the_dialog_template->x_ + 1, the_dialog_template->y_ + 3,
;
	ldy     #$18
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ina
	jsr     pusha
	ldy     #$19
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	clc
	adc     #$03
	jsr     pusha
;
; the_dialog_template->body_text_,
;
	ldy     #$1A
	jsr     ldaxysp
	ldy     #$08
	jsr     pushwidx
;
; fore_color, back_color
;
	ldy     #$15
	lda     (sp),y
	jsr     pusha
;
; );
;
	ldy     #$15
	lda     (sp),y
	jsr     _Text_DrawStringAtXY
;
; btn_y = y2 - 2; // -2: 1 for bottom line char, 1 for a spacer below button
;
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$02
	ldy     #$08
	sta     (sp),y
;
; btn_x = x2 - 0; // -1: account for right line char, but space is built into button width -> set to 0 to get right results.
;
	ldy     #$03
	lda     (sp),y
	ldy     #$09
	sta     (sp),y
;
; i = the_dialog_template->num_buttons_ - 1;
;
	ldy     #$18
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	sec
	sbc     #$01
	cmp     #$80
L0459:	sta     (sp)
;
; for (; i >= 0; i--)
;
	tax
	jmi     L02ED
;
; btn_x -= btn_width[i];
;
	jsr     decsp1
	lda     #$0C
	jsr     leaa0sp
	ldy     #$01
	clc
	adc     (sp),y
	bcc     L02F8
	inx
L02F8:	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$0A
	eor     #$FF
	sec
	adc     (sp),y
	sta     (sp),y
;
; if (the_dialog_template->default_button_id_ == i)
;
	ldy     #$19
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$18
	ldx     #$00
	lda     (ptr1),y
	sta     ptr1
	stz     ptr1+1
	ldy     #$01
	lda     (sp),y
	bpl     L02FB
	dex
L02FB:	cpx     ptr1+1
	bne     L02F9
	cmp     ptr1
	bne     L02F9
;
; btn_color = affirm_color;
;
	ldy     #$0F
;
; else
;
	bra     L045D
;
; btn_color = cancel_color;
;
L02F9:	ldy     #$10
L045D:	lda     (sp),y
	sta     (sp)
;
; Text_DrawStringAtXY(btn_x, btn_y, the_dialog_template->btn_label_[i], btn_color, back_color);
;
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$1B
	jsr     ldaxysp
	ldy     #$09
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$03
	lda     (sp),y
	bpl     L0306
	dex
L0306:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$16
	lda     (sp),y
	jsr     _Text_DrawStringAtXY
;
; }
;
	jsr     incsp1
;
; for (; i >= 0; i--)
;
	lda     (sp)
	dea
	jmp     L0459
;
; player_input = Keyboard_GetChar();
;
L02ED:	jsr     _Keyboard_GetChar
	ldy     #$07
	sta     (sp),y
;
; if (player_input == CH_ESC || player_input == CH_RUNSTOP)
;
	cmp     #$1B
	jeq     L030A
	lda     (sp),y
	cmp     #$03
	jeq     L030A
	lda     #$00
;
; for (i = 0; i < the_dialog_template->num_buttons_; i++)
;
L045A:	sta     (sp)
	ldx     #$00
	lda     (sp)
	bpl     L0318
	dex
L0318:	jsr     pushax
	ldy     #$1A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jsr     tosicmp0
	bcs     L0312
;
; if (the_dialog_template->btn_shortcut_[i] == player_input)
;
	ldy     #$18
	jsr     ldaxysp
	ldy     #$15
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	bpl     L031E
	dex
L031E:	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$07
	cmp     (sp),y
	bne     L031B
;
; the_result = i;
;
	lda     (sp)
	ldy     #$01
	sta     (sp),y
;
; break;
;
	bra     L0453
;
; else if (i == the_dialog_template->default_button_id_ && player_input == the_dialog_template->default_button_shortcut_)
;
L031B:	lda     (sp)
	bpl     L0325
	dex
L0325:	jsr     pushax
	ldy     #$1A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$18
	lda     (ptr1),y
	jsr     tosicmp0
	bne     L0313
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$1A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$19
	lda     (ptr1),y
	jsr     tosicmp0
	bne     L0313
;
; the_result =i;
;
	lda     (sp)
	ldy     #$01
	sta     (sp),y
;
; break;
;
	bra     L0453
;
; for (i = 0; i < the_dialog_template->num_buttons_; i++)
;
L0313:	lda     (sp)
	ina
	jmp     L045A
;
; if (the_result == DIALOG_ERROR && player_input == the_dialog_template->cancel_button_shortcut_)
;
L0312:	ldy     #$01
L0453:	lda     (sp),y
	cmp     #$FE
	bne     L045B
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$1A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$1A
	lda     (ptr1),y
	jsr     tosicmp0
	bne     L032B
;
; the_result = DIALOG_CANCEL;
;
	lda     #$FF
	ldy     #$01
	sta     (sp),y
;
; while (the_result == DIALOG_ERROR);
;
L032B:	ldy     #$01
L045B:	lda     (sp),y
	cmp     #$FE
	jeq     L02ED
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)char_save_mem,
;
L030A:	ldy     #$18
	jsr     pushwysp
;
; x1, y1,
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
;
; PARAM_COPY_TO_SCREEN, PARAM_FOR_TEXT_CHAR
;
	lda     #$01
	jsr     pusha
;
; );
;
	dea
	jsr     _Text_CopyMemBoxLinearBuffer
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)attr_save_mem,
;
	ldy     #$16
	jsr     pushwysp
;
; x1, y1,
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
;
; PARAM_COPY_TO_SCREEN, PARAM_FOR_TEXT_ATTR
;
	lda     #$01
	jsr     pusha
;
; );
;
	jsr     _Text_CopyMemBoxLinearBuffer
;
; return the_result;
;
L045F:	ldy     #$01
	ldx     #$00
L045C:	lda     (sp),y
	bpl     L0295
	dex
;
; }
;
L0295:	ldy     #$19
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; signed char __near__ Text_DisplayTextEntryDialog (__near__ struct TextDialogTemplate *, __near__ unsigned char *, __near__ unsigned char *, __near__ unsigned char *, signed char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_DisplayTextEntryDialog: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t   x1 = the_dialog_template->x_;
;
	jsr     decsp3
	ldy     #$0E
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha
;
; uint8_t   y1 = the_dialog_template->y_;
;
	ldy     #$0F
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha
;
; uint8_t   x2 = x1 + the_dialog_template->width_;
;
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$12
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
;
; uint8_t   y2 = y1 + the_dialog_template->height_;
;
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
;
; int8_t   the_result = false;
;
	lda     #$00
	jsr     pusha
;
; if (the_dialog_template->title_text_ == NULL || the_dialog_template->body_text_ == NULL)
;
	ldy     #$13
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaxidx
	cpx     #$00
	bne     L0463
	cmp     #$00
	beq     L034D
L0463:	ldy     #$13
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
	cpx     #$00
	bne     L034C
	cmp     #$00
	bne     L034C
;
; return the_result;
;
L034D:	jmp     L0466
;
; avail_width = the_dialog_template->width_ - 2; // account for draw characters on edges
;
L034C:	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	sec
	sbc     #$02
	ldy     #$07
	sta     (sp),y
;
; if (the_max_length > avail_width)
;
	ldy     #$0B
	ldx     #$00
	lda     (sp),y
	bpl     L0357
	dex
L0357:	sec
	ldy     #$07
	sbc     (sp),y
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	bcc     L0355
;
; return the_result;
;
	jne     L0468
;
; x1, y1,
;
L0355:	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
;
; accent_color, fore_color, back_color,
;
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
;
; the_dialog_template->title_text_,
;
	ldy     #$1A
	jsr     ldaxysp
	ldy     #$06
	jsr     pushwidx
;
; char_save_mem, attr_save_mem,
;
	ldy     #$1C
	jsr     pushwysp
	ldy     #$1C
	jsr     pushwysp
;
; PARAM_CLEAR_FIRST,
;
	lda     #$01
	jsr     pusha
;
; ) == false)
;
	jsr     _Text_DrawWindow
	cmp     #$00
;
; return the_result;
;
	jeq     L0468
;
; the_dialog_template->x_ + 1, the_dialog_template->y_ + 3,
;
	ldy     #$13
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ina
	jsr     pusha
	ldy     #$14
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	clc
	adc     #$03
	jsr     pusha
;
; the_dialog_template->body_text_,
;
	ldy     #$15
	jsr     ldaxysp
	ldy     #$08
	jsr     pushwidx
;
; fore_color, back_color
;
	ldy     #$0D
	lda     (sp),y
	jsr     pusha
;
; );
;
	ldy     #$0D
	lda     (sp),y
	jsr     _Text_DrawStringAtXY
;
; input_y = y2 - 2; // -2: 1 for bottom line char, 1 for a spacer below button
;
	ldy     #$01
	lda     (sp),y
	sec
	sbc     #$02
	ldy     #$05
	sta     (sp),y
;
; input_x = x1 + 1; // +1: get past box char
;
	dey
	lda     (sp),y
	ina
	ldy     #$06
	sta     (sp),y
;
; the_result = Text_GetStringFromUser(the_buffer, the_max_length, input_x, input_y, PARAM_USE_INSERT_MODE);
;
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0D
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _Text_GetStringFromUser
	sta     (sp)
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)char_save_mem,
;
	ldy     #$13
	jsr     pushwysp
;
; x1, y1,
;
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
;
; PARAM_COPY_TO_SCREEN, PARAM_FOR_TEXT_CHAR
;
	lda     #$01
	jsr     pusha
;
; );
;
	dea
	jsr     _Text_CopyMemBoxLinearBuffer
;
; Text_CopyMemBoxLinearBuffer((uint8_t*)attr_save_mem,
;
	ldy     #$11
	jsr     pushwysp
;
; x1, y1,
;
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
;
; x2, y2,
;
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
;
; PARAM_COPY_TO_SCREEN, PARAM_FOR_TEXT_ATTR
;
	lda     #$01
	jsr     pusha
;
; );
;
	jsr     _Text_CopyMemBoxLinearBuffer
;
; return the_result;
;
L0468:	ldx     #$00
L0466:	lda     (sp)
	bpl     L0346
	dex
;
; }
;
L0346:	ldy     #$14
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_GetStringFromUser (__near__ unsigned char *, signed char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_GetStringFromUser: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; if (!the_buffer || the_max_length < 1 || start_y >= SCREEN_NUM_ROWS ||
;
	jsr     decsp3
	ldy     #$08
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L046D
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bvc     L0393
	eor     #$80
L0393:	bmi     L046D
	ldy     #$04
	lda     (sp),y
	cmp     #$3C
	bcs     L046D
;
; start_x + the_max_length >= SCREEN_NUM_COLS) return false;
;
	ldx     #$00
	ldy     #$06
	lda     (sp),y
	bpl     L0394
	dex
L0394:	clc
	dey
	adc     (sp),y
	bcc     L0469
	inx
L0469:	cmp     #$50
	txa
	sbc     #$00
	bcc     L0390
L046D:	ldx     #$00
	txa
	jmp     L03A5
;
; length = General_Strnlen(the_buffer, the_max_length);
;
L0390:	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	cmp     #$80
	bcc     L039C
	dex
L039C:	jsr     _General_Strnlen
	ldy     #$02
	sta     (sp),y
;
; the_buffer[length] = 0;
;
	clc
	ldy     #$07
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; cursor = length;
;
	ldy     #$02
	lda     (sp),y
	dey
	sta     (sp),y
;
; Sys_EnableTextModeCursor(true);
;
	tya
	jsr     _Sys_EnableTextModeCursor
;
; Text_FillBox(start_x, start_y, start_x + the_max_length, start_y, CH_SPACE, COLOR_BRIGHT_WHITE, COLOR_BLACK);
;
L03A7:	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	clc
	dey
	adc     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$0F
	jsr     pusha
	lda     #$00
	jsr     _Text_FillBox
;
; Text_DrawStringAtXY(start_x, start_y, the_buffer, COLOR_BRIGHT_WHITE, COLOR_BLACK);
;
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	jsr     pushwysp
	lda     #$0F
	jsr     pusha
	lda     #$00
	jsr     _Text_DrawStringAtXY
;
; Text_SetXY(start_x + cursor, start_y);
;
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$05
	adc     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _Text_SetXY
;
; key = Keyboard_GetChar();
;
	jsr     _Keyboard_GetChar
	sta     (sp)
;
; if (key == CH_ESC || key == CH_RUNSTOP || key == CH_ENTER) {
;
	cmp     #$1B
	beq     L046F
	lda     (sp)
	cmp     #$03
	beq     L046F
	cmp     #$0D
	bne     L0474
;
; Sys_EnableTextModeCursor(false);
;
L046F:	lda     #$00
	jsr     _Sys_EnableTextModeCursor
;
; return key == CH_ENTER && length != 0;
;
	ldx     #$00
	lda     (sp)
	cmp     #$0D
	bne     L0470
	ldy     #$02
	lda     (sp),y
	bne     L0471
L0470:	txa
	jmp     L03A5
L0471:	lda     #$01
	jmp     L03A5
;
; if (key == CH_CURS_LEFT) { if (cursor) --cursor; }
;
L0474:	lda     (sp)
	cmp     #$02
	bne     L0476
	ldy     #$01
	lda     (sp),y
	jeq     L03FD
	sec
	sbc     #$01
;
; else if (key == CH_CURS_RIGHT) { if (cursor < length) ++cursor; }
;
	jmp     L046C
L0476:	lda     (sp)
	cmp     #$06
	bne     L0478
	ldy     #$01
	lda     (sp),y
	iny
	cmp     (sp),y
	jcs     L0488
	dey
;
; else if (key == CH_CURS_UP) cursor = 0;
;
	jmp     L048A
L0478:	lda     (sp)
	cmp     #$10
	bne     L047A
	lda     #$00
	ldy     #$01
;
; else if (key == CH_CURS_DOWN) cursor = length;
;
	jmp     L046C
L047A:	lda     (sp)
	cmp     #$0E
	bne     L047C
	ldy     #$02
	lda     (sp),y
	dey
;
; else if (key == CH_BKSP) {
;
	jmp     L046C
L047C:	lda     (sp)
	cmp     #$08
	bne     L047E
;
; if (cursor) { --cursor; memmove(the_buffer + cursor, the_buffer + cursor + 1, length - cursor); --length; }
;
	ldy     #$01
	lda     (sp),y
	jeq     L03FD
	sec
	sbc     #$01
	sta     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	ina
	bne     L03E2
	inx
L03E2:	jsr     pushax
	ldy     #$06
	lda     (sp),y
	sec
	dey
	sbc     (sp),y
	ldx     #$00
	jsr     _memmove
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
;
; } else if (key == CH_DEL) {
;
	jmp     L046C
L047E:	lda     (sp)
	cmp     #$7F
	bne     L0480
;
; if (cursor < length) { memmove(the_buffer + cursor, the_buffer + cursor + 1, length - cursor); --length; }
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	iny
	cmp     (sp),y
	jcs     L0488
	dey
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	ina
	bne     L03ED
	inx
L03ED:	jsr     pushax
	ldy     #$06
	lda     (sp),y
	sec
	dey
	sbc     (sp),y
	ldx     #$00
	jsr     _memmove
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
;
; } else if (key >= 32 && key < 127) {
;
	jmp     L046C
L0480:	lda     (sp)
	cmp     #$20
	jcc     L03FD
	cmp     #$7F
	jcs     L03FD
;
; if (overwrite_mode == PARAM_USE_OVERWRITE_MODE && cursor < length) the_buffer[cursor++] = key;
;
	ldy     #$03
	lda     (sp),y
	cmp     #$01
	bne     L03F5
	tay
	lda     (sp),y
	iny
	cmp     (sp),y
	bcs     L0487
	ldy     #$0A
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
;
; else if (length < the_max_length) {
;
	bra     L03FD
L03F5:	dey
L0487:	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	lda     (sp),y
	bpl     L03FF
	ldx     #$FF
L03FF:	jsr     tosicmp
	bcs     L03FD
;
; memmove(the_buffer + cursor + 1, the_buffer + cursor, length - cursor + 1);
;
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	ina
	bne     L0402
	inx
L0402:	jsr     pushax
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	sec
	dey
	sbc     (sp),y
	ldx     #$00
	ina
	bne     L0405
	inx
L0405:	jsr     _memmove
;
; the_buffer[cursor++] = key;
;
	ldy     #$0A
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
;
; ++length;
;
	ldy     #$02
L048A:	clc
	lda     #$01
	adc     (sp),y
L046C:	sta     (sp),y
;
; the_buffer[length] = 0;
;
L03FD:	ldy     #$02
L0488:	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; }
;
	jmp     L03A7
;
; }
;
L03A5:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_FillMemoryBoxBoth (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_FillMemoryBoxBoth: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t old_io = R8(MMU_IO_CTRL);
;
	jsr     decsp1
	lda     $0001
	jsr     pusha
;
; if (!width || !height || x >= SCREEN_NUM_COLS || y >= SCREEN_NUM_ROWS ||
;
	ldy     #$05
	lda     (sp),y
	beq     L048E
	dey
	lda     (sp),y
	beq     L048E
	ldy     #$07
	lda     (sp),y
	cmp     #$50
	bcs     L048E
	dey
	lda     (sp),y
	cmp     #$3C
	bcs     L048E
;
; width > SCREEN_NUM_COLS - x || height > SCREEN_NUM_ROWS - y) return false;
;
	dey
	lda     (sp),y
	jsr     pusha0
	lda     #$50
	sec
	ldy     #$09
	sbc     (sp),y
	jsr     tosicmp0
	beq     L048C
	bcs     L048E
L048C:	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$3C
	sec
	ldy     #$08
	sbc     (sp),y
	jsr     tosicmp0
	beq     L0024
	bcc     L0024
L048E:	ldx     #$00
	txa
	jmp     incsp8
;
; Text_SetXY(x, y);
;
L0024:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _Text_SetXY
;
; for (row = 0; row < height; ++row) {
;
	lda     #$00
	ldy     #$01
L048B:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L002C
;
; R8(MMU_IO_CTRL) = VICKY_IO_PAGE_ATTR_MEM;
;
	lda     #$03
	sta     $0001
;
; memset(zp_vram_ptr, the_attribute_value, width);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$09
	lda     (sp),y
	jsr     _memset
;
; R8(MMU_IO_CTRL) = VICKY_IO_PAGE_CHAR_MEM;
;
	lda     #$02
	sta     $0001
;
; memset(zp_vram_ptr, the_char, width);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$09
	lda     (sp),y
	jsr     _memset
;
; zp_vram_ptr += SCREEN_NUM_COLS;
;
	lda     #$50
	clc
	adc     _zp_vram_ptr
	sta     _zp_vram_ptr
	bcc     L0045
	inc     _zp_vram_ptr+1
;
; for (row = 0; row < height; ++row) {
;
L0045:	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L048B
;
; Text_SetXY(x, y);
;
L002C:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _Text_SetXY
;
; R8(MMU_IO_CTRL) = old_io;
;
	lda     (sp)
	sta     $0001
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Text_FillMemoryBox (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Text_FillMemoryBox: near

.segment	"CODE"

;
; {
;
	jsr     pusha
;
; uint8_t old_io = R8(MMU_IO_CTRL);
;
	jsr     decsp1
	lda     $0001
	jsr     pusha
;
; if (!width || !height || x >= SCREEN_NUM_COLS || y >= SCREEN_NUM_ROWS ||
;
	ldy     #$05
	lda     (sp),y
	beq     L0492
	dey
	lda     (sp),y
	beq     L0492
	ldy     #$07
	lda     (sp),y
	cmp     #$50
	bcs     L0492
	dey
	lda     (sp),y
	cmp     #$3C
	bcs     L0492
;
; width > SCREEN_NUM_COLS - x || height > SCREEN_NUM_ROWS - y) return false;
;
	dey
	lda     (sp),y
	jsr     pusha0
	lda     #$50
	sec
	ldy     #$09
	sbc     (sp),y
	jsr     tosicmp0
	beq     L0490
	bcs     L0492
L0490:	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$3C
	sec
	ldy     #$08
	sbc     (sp),y
	jsr     tosicmp0
	beq     L0052
	bcc     L0052
L0492:	ldx     #$00
	txa
	jmp     incsp8
;
; Text_SetXY(x, y);
;
L0052:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _Text_SetXY
;
; for (row = 0; row < height; ++row) {
;
	lda     #$00
	ldy     #$01
L048F:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L005A
;
; R8(MMU_IO_CTRL) = for_attr ? VICKY_IO_PAGE_ATTR_MEM : VICKY_IO_PAGE_CHAR_MEM;
;
	dey
	lda     (sp),y
	beq     L0493
	tya
	bra     L0494
L0493:	lda     #$02
L0494:	sta     $0001
;
; memset(zp_vram_ptr, the_fill, width);
;
	lda     _zp_vram_ptr
	ldx     _zp_vram_ptr+1
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$09
	lda     (sp),y
	jsr     _memset
;
; zp_vram_ptr += SCREEN_NUM_COLS;
;
	lda     #$50
	clc
	adc     _zp_vram_ptr
	sta     _zp_vram_ptr
	bcc     L006F
	inc     _zp_vram_ptr+1
;
; for (row = 0; row < height; ++row) {
;
L006F:	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L048F
;
; Text_SetXY(x, y);
;
L005A:	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _Text_SetXY
;
; R8(MMU_IO_CTRL) = old_io;
;
	lda     (sp)
	sta     $0001
;
; return true;
;
	ldx     #$00
	lda     #$01
;
; }
;
	jmp     incsp8

.endproc
